--[[
-- XUiEquipPartnerEnhanceProgressCell.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-08 12:06:34
--]]

---@class XUiEquipPartnerEnhanceProgressCell : XUiNode
---@field _Control XPartnerControl
---@field GoBgItemWaiting UnityEngine.RectTransform
---@field GoBgItemProcessing UnityEngine.RectTransform
---@field GoBgItemDone UnityEngine.RectTransform
---@field TxtUnitTitleName UnityEngine.UI.Text
---@field TxtPreview UnityEngine.UI.Text
---@field RImgCurQuality UnityEngine.UI.RawImage
---@field GoStatusWaiting UnityEngine.RectTransform
---@field GoStatusProcessing UnityEngine.RectTransform
---@field GoStatusDone UnityEngine.RectTransform
---@field TxtWaitingTip UnityEngine.UI.Text
---@field TxtProcessingTip UnityEngine.UI.Text
---@field private _CultureType XPartnerEnum.CultureType
local XUiEquipPartnerEnhanceProgressCell = XClass(XUiNode, "XUiEquipPartnerEnhanceProgressCell")

XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType = {
    Waiting = 0,
    Processing = 1,
    Done = 2,
}

function XUiEquipPartnerEnhanceProgressCell:InitComponents()
end

function XUiEquipPartnerEnhanceProgressCell:OnStart(...)
    self.RImgCurQuality.gameObject:SetActiveEx(false)
    self:InitComponents()
end

function XUiEquipPartnerEnhanceProgressCell:OnEnable()
end

function XUiEquipPartnerEnhanceProgressCell:OnDisable()
end

function XUiEquipPartnerEnhanceProgressCell:OnDestroy()
end

---region ui event

---endregion

---region event

---endregion

---@param cultureType XPartnerEnum.CultureType
function XUiEquipPartnerEnhanceProgressCell:RefreshByCultureType(cultureType)
    self._CultureType = cultureType
    local XPartnerEnum = XMVCA.XPartner.Enum
    local commitControl = self._Control:GetOneKeyCultureMainControl():GetCommitControl()

    self.RImgCurQuality.gameObject:SetActiveEx(false)

    if cultureType == XPartnerEnum.CultureType.LevelUp then
        self.TxtUnitTitleName.text = XUiHelper.GetText("PartnerOneKeyUnitLevelUp")
        self.TxtPreview.text = XUiHelper.GetText("PartnerOneKeyPreviewLevelUp", commitControl:GetCanReachLevel())
    elseif cultureType == XPartnerEnum.CultureType.StarUp then
        self.TxtUnitTitleName.text = XUiHelper.GetText("PartnerOneKeyUnitStarUp")
        self.TxtPreview.text = XUiHelper.GetText("PartnerOneKeyPreviewStarUp", "")
    elseif cultureType == XPartnerEnum.CultureType.SkillLevelUp then
        self.TxtUnitTitleName.text = XUiHelper.GetText("PartnerOneKeyUnitSkill")
        self.TxtPreview.text = XUiHelper.GetText("PartnerOneKeyPreviewSkill", commitControl:GetCanReachSkillAvgLevel())
    end
end

---@param status XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType
function XUiEquipPartnerEnhanceProgressCell:RefreshByProgressStatus(status)
    local EnhanceProgressType = self.EnhanceProgressType

    self.GoBgItemWaiting.gameObject:SetActiveEx(false)
    self.GoBgItemProcessing.gameObject:SetActiveEx(false)
    self.GoBgItemDone.gameObject:SetActiveEx(false)
    self.GoStatusWaiting.gameObject:SetActiveEx(false)
    self.GoStatusProcessing.gameObject:SetActiveEx(false)
    self.GoStatusDone.gameObject:SetActiveEx(false)

    if status == EnhanceProgressType.Waiting then
        self.GoBgItemWaiting.gameObject:SetActiveEx(true)
        self.GoStatusWaiting.gameObject:SetActiveEx(true)
        self.TxtWaitingTip.text = XUiHelper.GetText("PartnerOneKeyStatusWaiting")
    elseif status == EnhanceProgressType.Processing then
        self.GoBgItemProcessing.gameObject:SetActiveEx(true)
        self.GoStatusProcessing.gameObject:SetActiveEx(true)
        self.TxtProcessingTip.text = self:GetProcessingTip()
    elseif status == EnhanceProgressType.Done then
        self.GoBgItemDone.gameObject:SetActiveEx(true)
        self.GoStatusDone.gameObject:SetActiveEx(true)
    end
end

function XUiEquipPartnerEnhanceProgressCell:RefreshQualityIcon()
    local partner = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partner then
        return
    end

    self.RImgCurQuality:SetRawImage(XMVCA.XCharacter:GetCharQualityIcon(partner:GetQuality()))
    self.RImgCurQuality.gameObject:SetActiveEx(true)
end

---@return string
function XUiEquipPartnerEnhanceProgressCell:GetProcessingTip()
    local XPartnerEnum = XMVCA.XPartner.Enum
    if self._CultureType == XPartnerEnum.CultureType.LevelUp then
        return XUiHelper.GetText("PartnerOneKeyProcessingLevelUp")
    elseif self._CultureType == XPartnerEnum.CultureType.StarUp then
        return XUiHelper.GetText("PartnerOneKeyProcessingStarUp")
    elseif self._CultureType == XPartnerEnum.CultureType.SkillLevelUp then
        return XUiHelper.GetText("PartnerOneKeyProcessingSkillUp")
    end
    return XUiHelper.GetText("PartnerOneKeyProcessingDefault")
end

return XUiEquipPartnerEnhanceProgressCell
