--[[
-- XUiPunishaarEventSelectionBtnEvent.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-17 16:05:40
--]]

---@class XUiPunishaarEventSelectionBtnEvent : XUiNode
---@field _Control XPunishaarControl
---@field GridBtn XUiComponent.XUiButton
---@field TxtName TMPro.TextMeshProUGUI
---@field TxtDesc TMPro.TextMeshProUGUI
local XUiPunishaarEventSelectionBtnEvent = XClass(XUiNode, "XUiPunishaarEventSelectionBtnEvent")

function XUiPunishaarEventSelectionBtnEvent:OnStart()
end

function XUiPunishaarEventSelectionBtnEvent:OnEnable()
end

function XUiPunishaarEventSelectionBtnEvent:OnDisable()
end

function XUiPunishaarEventSelectionBtnEvent:OnDestroy()
end

--- 刷新选项显示内容（选中态由 PanelEvent ButtonGroup 统一管理，无需传入）
---@param optionData table { Name: string, Desc: string }
function XUiPunishaarEventSelectionBtnEvent:Refresh(optionData)
    self.GridBtn:SetNameByGroup(0, optionData.Name)
    
    local desc = optionData.Desc

    if not string.IsNilOrEmpty(desc) then
        desc = XUiHelper.ReplaceTextNewLine(desc)
    end
    
    self.GridBtn:SetNameByGroup(1, desc)
end

return XUiPunishaarEventSelectionBtnEvent
