--[[
-- XUiMusicPlayerMusicListView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-03 20:40:54
--]]

---@class XUiMusicPlayerMainPanelMusicListView : XUiNode
---@field _Control XMusicPlayerControl
---@field _MusicListControl XMusicPlayerMusicListControl
---@field _musicPlayerconfig XMusicPlayerConfigControl
---@field GoTitleRoot UnityEngine.RectTransform
---@field GoTitleNormal UnityEngine.RectTransform
---@field BtnManageMusic XUiComponent.XUiButton
---@field TxtMusicListTitle UnityEngine.UI.Text
---@field BtnSearchMusic XUiComponent.XUiButton
---@field GoSearchRoot UnityEngine.RectTransform
---@field TxtMusicNum UnityEngine.UI.Text
---@field InMusicSearch UnityEngine.RectTransform
---@field BtnSearchRootHide XUiComponent.XUiButton
---@field ScrollViewListMusic UnityEngine.RectTransform
---@field PanelManage UnityEngine.RectTransform
---@field GoDontHasMusic UnityEngine.RectTransform
---@field GoDontSearchMusic UnityEngine.RectTransform
---@field TxtDontHasMusic UnityEngine.UI.Text
---@field BtnTabAllMusic XUiComponent.XUiButton
---@field BtnTabLike XUiComponent.XUiButton
---@field BtnTabBgm XUiComponent.XUiButton
---@field BtnHideListView XUiComponent.XUiButton
---@field GoMusicListCellCopySource UnityEngine.RectTransform
---@field GoManageRoot UnityEngine.RectTransform
---@field BtnManageApply XUiComponent.XUiButton 
---@field BtnAllLike XUiComponent.XUiButton
---@field BtnSortMusic XUiComponent.XUiButton 
---@field BtnAllLickSetBGM XUiComponent.XUiButton
---@field BtnResetBgm  XUiComponent.XUiButton
---@field TxtNormalListSortTip UnityEngine.UI.Text
---@field InputSearchMusic UnityEngine.UI.InputField
---@field GoAllMusicIsPlaying UnityEngine.RectTransform
---@field GoLikeIsPlaying UnityEngine.RectTransform
---@field GoBgmPlaying UnityEngine.RectTransform
local XUiMusicPlayerMusicListView = XClass(XUiNode, "XUiMusicPlayerMusicListView")

function XUiMusicPlayerMusicListView:InitComponents()
    -- Button
    self.BtnManageMusic:AddEventListener(function() self:OnBtnManageMusicClick() end)
    self.BtnSearchMusic:AddEventListener(function() self:OnBtnSearchMusicClick() end)
    self.BtnSearchRootHide:AddEventListener(function() self:OnBtnSearchRootHideClick() end)
    self.BtnHideListView:AddEventListener(function() self:OnBtnHideListViewClick() end)
    self.BtnManageApply:AddEventListener(function() self:OnBtnManageApplyClick() end)
    self.BtnTabAllMusic:AddEventListener(function() self:OnBtnTabAllMusicClick() end)
    self.BtnTabLike:AddEventListener(function() self:OnBtnTabLikeClick() end)
    self.BtnTabBgm:AddEventListener(function() self:OnBtnTabBgmClick() end)

    self.BtnSortMusic:AddEventListener(function() self:OnBtnSortMusicClick() end)
    self.BtnAllLickSetBGM:AddEventListener(function() self:OnBtnAllLickSetBGMClick() end)
    self.BtnResetBgm:AddEventListener(function() self:OnBtnResetBgmClick() end)
    self.InputSearchMusic.onValueChanged:AddListener(Handler(self, self.OnSearchMusicChanged))

    local XDynamicTableNormal = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableNormal")

    local XUiMusicPlayerMusicListCellView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUiMusicPlayerMusicListCellView")
    self._MusicListTable = XDynamicTableNormal.New(self.ScrollViewListMusic)
    self._MusicListTable:SetProxy(XUiMusicPlayerMusicListCellView,self)
    self._MusicListTable:SetDelegate(self)
    self.GoMusicListCellCopySource.gameObject:SetActive(false)

    local XMusicPlayerEnum =XMVCA.XMusicPlayer.Enum
    self._TitleShowByStatus = {
        [XMusicPlayerEnum.MusicListUIStatus.normal] = {self.GoTitleNormal},
        [XMusicPlayerEnum.MusicListUIStatus.manager] = {self.GoManageRoot},
        [XMusicPlayerEnum.MusicListUIStatus.search] = {self.GoSearchRoot},
    }
end

function XUiMusicPlayerMusicListView:OnStart(...)
    self._MusicListControl = self._Control:GetMusicmusicListControl()

    self._SearchList = {}
    self._ListType = nil
    self._Status = nil


    self:InitComponents()
end

function XUiMusicPlayerMusicListView:OnEnable()
    self:_SetEvent(true)

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 

    local switchType = self._Control:GetCDPlayerControl():GetCurMusicListType()
    if switchType == nil or switchType == XMusicPlayerEnum.MusicListType.unInit then
        switchType = XMusicPlayerEnum.MusicListType.Normal
    end

    self:_SwitchMusicListTypeAndStatus(switchType,XMusicPlayerEnum.MusicListUIStatus.normal)
    self:_RefreshPlayingListType()


    self:_DoJumpIfNeed()
end

 
function XUiMusicPlayerMusicListView:OnDisable()
    self:_SetEvent(false)
end
 

function XUiMusicPlayerMusicListView:OnDestroy()
end

 
 
---region UI事件处理
function XUiMusicPlayerMusicListView:OnBtnManageMusicClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.manager)
end

function XUiMusicPlayerMusicListView:OnBtnSearchMusicClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.search)
end

function XUiMusicPlayerMusicListView:OnBtnSearchRootHideClick(eventData)
    self.InputSearchMusic.text = ""
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.normal)
end

function XUiMusicPlayerMusicListView:OnBtnManageApplyClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.normal)
end

function XUiMusicPlayerMusicListView:OnBtnHideListViewClick(eventData)
    local enum = XMVCA.XMusicPlayer.Enum.MusicMainUIStatus.mainCD 
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE,enum)
end

function XUiMusicPlayerMusicListView:OnBtnTabAllMusicClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListType(XMusicPlayerEnum.MusicListType.Normal)
end

function XUiMusicPlayerMusicListView:OnBtnTabLikeClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListType(XMusicPlayerEnum.MusicListType.Favorite)
end

function XUiMusicPlayerMusicListView:OnBtnTabBgmClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self:_SwitchMusicListType(XMusicPlayerEnum.MusicListType.BGM)
end

function XUiMusicPlayerMusicListView:OnBtnSortMusicClick(eventData)
    local isAscending = self._Control:GetMusicmusicListControl():GetDefaultMusicListIsAscending()
    self._Control:GetMusicmusicListControl():SetDefaultMusicListSortType(not isAscending)
end

function XUiMusicPlayerMusicListView:OnBtnAllLickSetBGMClick(eventData)
    local content = CS.XTextManager.GetText("MusicPlayerConfirmLikeAllSetBgm")
    XUiManager.DialogTip("", content, XUiManager.DialogType.Normal, nil, function()
        self._Control:GetMusicPlayerNetWorkControl():SendAllLickSetBGMRequest()
    end)
end

function XUiMusicPlayerMusicListView:OnBtnResetBgmClick(eventData)
    local content = CS.XTextManager.GetText("MusicPlayerConfirmBgmReset")
    XUiManager.DialogTip("", content, XUiManager.DialogType.Normal, nil, function()
        self._Control:GetMusicPlayerNetWorkControl():SendBGMListResetRequest()
    end)
end


function XUiMusicPlayerMusicListView:OnSearchMusicChanged(text)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    if self._Status == XMusicPlayerEnum.MusicListUIStatus.search then
        self:_SearchByInput(self:_GetCurSeverDataList(), text)
        self:_RefreshMusicListByData(self._ListType,self._Status)

    end
end

---endregion


---region event
function XUiMusicPlayerMusicListView:_SetEvent(flag)
    local XMusicPlayerEventId = XMVCA.XMusicPlayer.EventIds
    if flag then
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_MUSICLIST_UPDATE,self._OnMusicListDataChange,self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._RefreshPlayingListType,self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_REPLY_LIKE_ALL_SET_BGM,self._OnLikeAllSetBgmSuccess,self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_REPLY_BGMLIST_RESET,self._OnBgmListResetSuccess,self)
    else
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_MUSICLIST_UPDATE,self._OnMusicListDataChange,self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._RefreshPlayingListType,self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_REPLY_LIKE_ALL_SET_BGM,self._OnLikeAllSetBgmSuccess,self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_REPLY_BGMLIST_RESET,self._OnBgmListResetSuccess,self)
    end
end

function XUiMusicPlayerMusicListView:_RefreshPlayingListType()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local curListType = self._Control:GetCDPlayerControl():GetCurMusicListType()
    self.GoAllMusicIsPlaying.gameObject:SetActive(curListType == XMusicPlayerEnum.MusicListType.Normal)
    self.GoLikeIsPlaying.gameObject:SetActive(curListType == XMusicPlayerEnum.MusicListType.Favorite)
    self.GoBgmPlaying.gameObject:SetActive(curListType == XMusicPlayerEnum.MusicListType.BGM)
end

function XUiMusicPlayerMusicListView:_OnMusicListDataChange(listType)
    if listType == self._ListType then
        local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
        if self._Status == XMusicPlayerEnum.MusicListUIStatus.search then
            self:_SearchByInput(self:_GetCurSeverDataList(), self.InputSearchMusic.text or "")
        end
        self:_RefreshAll(self._ListType,self._Status)
    end
end

function XUiMusicPlayerMusicListView:_OnLikeAllSetBgmSuccess()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.normal)
end

function XUiMusicPlayerMusicListView:_OnBgmListResetSuccess()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self:_SwitchMusicListStatus(XMusicPlayerEnum.MusicListUIStatus.normal)
end
---endregion




function XUiMusicPlayerMusicListView:_SwitchMusicListTypeAndStatus(listType,status) 
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self._Status = status
    self._ListType = listType

    if status == XMusicPlayerEnum.MusicListUIStatus.search then
        self:_SearchByInput(self:_GetCurSeverDataList(), self.InputSearchMusic.text or "")
    end

    self:_RefreshAll(listType,status)
end

function XUiMusicPlayerMusicListView:_SwitchMusicListStatus(status)
    local listType = self._ListType 
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if status == XMusicPlayerEnum.MusicListUIStatus.search then
        self:_SearchByInput(self:_GetCurSeverDataList(), self.InputSearchMusic.text or "")
    end
    
    self:_RefreshTablBtn(listType)
    if self._Status == XMusicPlayerEnum.MusicListUIStatus.search or  status == XMusicPlayerEnum.MusicListUIStatus.search then
        self:_RefreshMusicListByData(listType,status)
    end
    self:_RefreshMusicShow(listType,status)
    self:_RefreshManageBtn(listType,status)

    self._Status = status
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_MUSIC_LIST_MANAGER_STATE_CHANGE, status)
end

function XUiMusicPlayerMusicListView:_SwitchMusicListType(listType)
    self:_SwitchMusicListTypeAndStatus(listType,self._Status) 

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if self._Status ~= XMusicPlayerEnum.MusicListUIStatus.search then
        local curMusicID = self._Control:GetCDPlayerControl():GetCurPlayingMusicID()
        self:SetJumpMusicIdAndDo(curMusicID, true)
    end
end

function XUiMusicPlayerMusicListView:_RefreshAll(listType,status)
    self:_RefreshTablBtn (listType)
    self:_RefreshMusicListByData(listType,status)
    self:_RefreshMusicShow(listType,status)
    self:_RefreshManageBtn(listType,status)
end

function XUiMusicPlayerMusicListView:_RefreshManageBtn(listType,status)
    XMVCA.XMusicPlayer.Util.ShowUIByStatus(self._TitleShowByStatus,status)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self.BtnSortMusic.gameObject:SetActive(false)
    self.BtnAllLickSetBGM.gameObject:SetActive(false)
    self.BtnResetBgm.gameObject:SetActive(false)

    if status == XMusicPlayerEnum.MusicListUIStatus.manager then
        if listType == XMusicPlayerEnum.MusicListType.BGM then
            self.BtnResetBgm.gameObject:SetActive(true)
        elseif listType == XMusicPlayerEnum.MusicListType.Favorite then
            self.BtnAllLickSetBGM.gameObject:SetActive(true)
        elseif listType == XMusicPlayerEnum.MusicListType.Normal then
            self.BtnSortMusic.gameObject:SetActive(true)
            local isAscending = self._Control:GetMusicmusicListControl():GetDefaultMusicListIsAscending()
            if  isAscending then
                self.TxtNormalListSortTip.text = CS.XTextManager.GetText("MusicPlayerMusicListSortTipOld2New")
            else
                self.TxtNormalListSortTip.text =  CS.XTextManager.GetText("MusicPlayerMusicListSortTipNew2Old")  
            end
        end
    end
end

function XUiMusicPlayerMusicListView:_RefreshTablBtn (listType)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum 
    self.BtnTabLike:SetButtonState(CS.UiButtonState.Normal)
    self.BtnTabBgm:SetButtonState(CS.UiButtonState.Normal)
    self.BtnTabAllMusic:SetButtonState(CS.UiButtonState.Normal)
    if listType == XMusicPlayerEnum.MusicListType.Normal then
        self.BtnTabAllMusic:SetButtonState(CS.UiButtonState.Select)
    elseif listType == XMusicPlayerEnum.MusicListType.Favorite then
        self.BtnTabLike:SetButtonState(CS.UiButtonState.Select)
    elseif listType == XMusicPlayerEnum.MusicListType.BGM then
        self.BtnTabBgm:SetButtonState(CS.UiButtonState.Select)
    end
end

function XUiMusicPlayerMusicListView:_RefreshMusicListByData(listType,status)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local dataList = self:_GetCurShowListDataList()
    self._MusicListTable:SetDataSource(dataList)
    self._MusicListTable:ReloadDataSync(1)
    self.GoDontSearchMusic.gameObject:SetActive(status == XMusicPlayerEnum.MusicListUIStatus.search and #dataList == 0)
end

function XUiMusicPlayerMusicListView:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        grid:UpdateXMusicListCellData(index,self)
    end
end

function XUiMusicPlayerMusicListView:GetMusicListViewStatusAndType()
    return self._Status,self._ListType
end


function XUiMusicPlayerMusicListView:GetMusicIdByIndex(index)
    local dataList = self:_GetCurShowListDataList()
    if index >= 1 and index <= #dataList then 
        return dataList[index]
    end
    return nil
end


function XUiMusicPlayerMusicListView:_GetCurSeverDataList()
    return self._MusicListControl:GetSeverMusicListByListType(self._ListType)
end

function XUiMusicPlayerMusicListView:SetJumpMusicIdAndDo(musicID, doNow)
    self._JumpMusicID = musicID
    if doNow then
        self:_DoJumpIfNeed()
    end
end

function XUiMusicPlayerMusicListView:_DoJumpIfNeed()
    if not XTool.IsNumberValid(self._JumpMusicID) then
        return
    end
    local dataList = self:_GetCurShowListDataList()
    local index = dataList and table.indexof(dataList, self._JumpMusicID) or 1
    self._JumpMusicID = nil
    self._MusicListTable:ReloadDataSync(index)
end


function XUiMusicPlayerMusicListView:_RefreshMusicShow(listType,status)
    self.GoSearchRoot.gameObject:SetActive(false)
    self.GoTitleRoot.gameObject:SetActive(true)

    self.GoDontHasMusic.gameObject:SetActive(false)
    local musicCount = #self:_GetCurSeverDataList()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    
    local musicTitleStr = "" 
    if listType == XMusicPlayerEnum.MusicListType.BGM then
        musicTitleStr = CS.XTextManager.GetText("MusicPlayerListTitleBgm" ) 
    elseif listType == XMusicPlayerEnum.MusicListType.Favorite then
        musicTitleStr = CS.XTextManager.GetText("MusicPlayerListTitleLike")
        if status ~= XMusicPlayerEnum.MusicListUIStatus.search and musicCount == 0 then
            self.GoDontHasMusic.gameObject:SetActive(true)
        end
    elseif listType == XMusicPlayerEnum.MusicListType.Normal then
        musicTitleStr = CS.XTextManager.GetText("MusicPlayerListTitleTotle" )
    end
    
    self.TxtMusicListTitle.text = musicTitleStr
    self.TxtMusicNum.text = #self:_GetCurSeverDataList()
end








function XUiMusicPlayerMusicListView:_GetCurShowListDataList()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if self._Status == XMusicPlayerEnum.MusicListUIStatus.search then
        return self._SearchList
    end
    return self:_GetCurSeverDataList()

end



--- 在给定的歌曲 id 集合内，按关键字搜索 MusicPlayerAlbum.Name
---@param musicIdList number[] 当前展示集（一组音乐 id）
---@param input string 关键字
---@return number[] 命中的音乐 id 列表（已按匹配度/ID 排序）
function XUiMusicPlayerMusicListView:_SearchByInput(musicIdList, input)
    if musicIdList == nil or input == nil then
        return  table.empty
    end

    local keyword = string.gsub(input, "^%s*(.-)%s*$", "%1")
    if keyword == "" then
        table.clear(self._SearchList)
        for _, musicID in ipairs(musicIdList) do
            table.insert(self._SearchList, musicID)
        end
        return self._SearchList
    end

    -- 最少关键字门槛:英文 2 个字母 / 中日韩繁 1 个字。
    -- 利用 UTF-8 编码特性:ASCII 1 字节、CJK(BMP)3 字节、其它非 ASCII 也 >=2 字节,
    -- 关键词太短无法触发搜索: 清空搜索结果
    if #keyword < 2 then
        table.clear(self._SearchList)
        return self._SearchList
    end

    local configControl = self._Control:GetMusicPlayerconfigControl()
    local lowerKeyword = string.lower(keyword)

    -- 3. 遍历集合做连续字面匹配，记录命中项（缓存写到 self._TempSearchXXX）
    if  self._TempSearchResult == nil then
         self._TempSearchResult = {}
    else
        table.clear(self._TempSearchResult)
    end

    for _, musicID in pairs(musicIdList) do
        local musicCO = configControl:GetMusicPlayerAlbumCOByid(musicID)
        local name = musicCO and musicCO.Name
        if name and name ~= "" then
            local lowerName = string.lower(name)
            -- plain=true：纯字面连续匹配，不走 Lua 模式；UTF-8 中文按字节连续匹配等价子串匹配
            if string.find(lowerName, lowerKeyword, 1, true) then
                table.insert(self._TempSearchResult, {
                    id = musicID,
                    isExact = (lowerName == lowerKeyword), -- 完全匹配优先
                    matchLen = #keyword,                   -- 匹配字符数（连续匹配下即关键字长度）
                })
            end
        end
    end

    -- 4. 排序：①完全匹配优先 ②匹配字符数多优先 ③同匹配度按 ID 从小到大
    table.sort(self._TempSearchResult, function(a, b)
        if a.isExact ~= b.isExact then
            return a.isExact
        end
        if a.matchLen ~= b.matchLen then
            return a.matchLen > b.matchLen
        end
        return a.id < b.id
    end)

    -- 5. 输出纯 id 列表
    table.clear(self._SearchList)
    for _, v in ipairs(self._TempSearchResult) do
        table.insert(self._SearchList, v.id)
    end
    return self._SearchList

end

return XUiMusicPlayerMusicListView
