--[[
-- XUIMusciPlayerAlbumCollectionView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-01 20:02:28
--]]


---@class XUIMusciPlayerAlbumCollectionView : XUiNode
---@field DynamicAlbumList UnityEngine.RectTransform Prefab 上挂的滚动列表 RectTransform,作为 XDynamicTableCurve 的容器
---@field GoGridAlbumBeClone UnityEngine.RectTransform
---@field _Control XMusicPlayerControl
---@field _MusicListControl XMusicPlayerMusicListControl 
---@field _DynamicTable XDynamicTableCurve 
---@field TxtMusicName UnityEngine.UI.Text 
---@field TxtComposer UnityEngine.UI.Text 
---@field TxtLockdesc UnityEngine.UI.Text
---@field GoMusicDecorate UnityEngine.RectTransform
---@field RImgMusicCurve4  UnityEngine.RawImage
local XUIMusciPlayerAlbumCollectionView = XClass(XUiNode, "XUIMusciPlayerAlbumCollectionView")

function XUIMusciPlayerAlbumCollectionView:OnStart(...)
    self._MusicListControl = self._Control:GetMusicmusicListControl()

    self.BtnCloseAlbum:AddEventListener(function() self:OnBtnCloseAlbumClick() end)
    
    local XDynamicTableCurve = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableCurve")
    local XUiGridMusicPlayer = require("XUi/XUiMusicPlayer/XUiGridMusicPlayer")
    ---@type XDynamicTableCurve
    self._DynamicTable = XDynamicTableCurve.New(self.DynamicAlbumList.gameObject)
    self._DynamicTable:SetProxy(XUiGridMusicPlayer)
    self._DynamicTable:SetDelegate(self)
    self.GoGridAlbumBeClone.gameObject:SetActive(false)

    local XUiTextScrolling = require("XUi/XUiTaikoMaster/XUiTaikoMasterFlowText")
    self._MusicNameScrolling = XUiTextScrolling.New(self.TxtMusicName, self.TxtMusicName.transform.parent)
    self._MusicNameScrolling:Stop()
end

function XUIMusciPlayerAlbumCollectionView:OnEnable()
    self:_SetEvent(true)
    self:_refreshColorFX()
    self:_UpdateDynamicTable()
    self:_UpdateSelect()
end

function XUIMusciPlayerAlbumCollectionView:OnDisable()
    self:_SetEvent(false)
end

function XUIMusciPlayerAlbumCollectionView:OnDestroy()
end



function XUIMusciPlayerAlbumCollectionView:_UpdateDynamicTable()
    local dataList = self:_GetCurSeverDataList()
    self._DynamicTable:SetDataSource(dataList)
    self._DynamicTable:ReloadData(#dataList > 0 and (self:_GetCurIndex() - 1) or -1)
end

---把当前居中那一格的 grid 高亮(选中态由 controller 当前播放索引决定)
function XUIMusciPlayerAlbumCollectionView:_UpdateSelect()
    if not self._DynamicTable or not self._DynamicTable.Imp then
        return
    end
    local startIndex = self._DynamicTable.Imp.StartIndex
    for idx, grid in pairs(self._DynamicTable:GetGrids()) do
        grid:UpdateSelect(idx == startIndex)
    end

    self:_RefreshSelectMusicInfo(self:_GetSelectMusicID())
end

---@return number|nil 当前居中选中那一首的 musicID(算法与 DYNAMIC_TWEEN_OVER 一致)
function XUIMusciPlayerAlbumCollectionView:_GetSelectMusicID()
    if not self._DynamicTable or not self._DynamicTable.Imp then
        return nil
    end
    local totalCount = self._DynamicTable.Imp.TotalCount
    if not totalCount or totalCount <= 0 then
        return nil
    end
    local selectIndex = self._DynamicTable.Imp.StartIndex % totalCount + 1
    return self:_GetCurSeverDataList()[selectIndex]
end

---刷新顶部选中歌曲信息区:歌名/作曲始终显示;已解锁(含试听)显示播放中icon,纯未解锁显示解锁条件文本
---@param musicID number|nil
function XUIMusciPlayerAlbumCollectionView:_RefreshSelectMusicInfo(musicID)
    if not self.GoMusicDecorate then return end
    if not XTool.IsNumberValid(musicID) then
        self.GoMusicDecorate.gameObject:SetActive(false)
        self.TxtLockdesc.gameObject:SetActive(false)
        return
    end

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local co = self:_GetMusicCO(musicID)
    self.TxtMusicName.text = co and co.Name or ""
    self._MusicNameScrolling:Play()

    local composerBrief = co and co.ComposeBrief
    if string.IsNilOrEmpty(composerBrief) then
        self.TxtComposer.text = XUiHelper.ConvertLineBreakSymbol(co and co.Composer or "")
    else
        self.TxtComposer.text = XUiHelper.ConvertLineBreakSymbol(composerBrief)
    end

    local cdControl = self._Control:GetCDPlayerControl()
    local useStatus, conditionDesc = cdControl:GetMusicUseStatusAndConditionDesc(musicID)
    local isLocked = useStatus == XMusicPlayerEnum.MusicUseStatus.unlock

    -- 仅纯未解锁(unlock)显示解锁条件文本;gain 与试听(limitedFree)均视为可玩,显示播放中icon
    self.TxtLockdesc.gameObject:SetActive(isLocked)
    self.GoMusicDecorate.gameObject:SetActive(not isLocked)
    if isLocked then
        self.TxtLockdesc.text = conditionDesc or ""
    end
end



---_DynamicTable 委托回调(基于 XUiMusicPlayer:OnDynamicTableEvent 改造,数据源换成 musicID 列表)
function XUIMusciPlayerAlbumCollectionView:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local dataList = self:_GetCurSeverDataList()
        index = index % self._DynamicTable.Imp.TotalCount + 1
        local musicID = dataList[index]
        -- 关键差异:musicID -> musicCO,然后把 CO 喂进去走 grid 的 else 分支(避免 grid 把 number 当 albumId 查)
        grid:Refresh(self:_GetMusicCO(musicID))
        grid:UpdateSelect(false)
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_TWEEN_OVER then
        local startIndex = self._DynamicTable.Imp.StartIndex
        local selectIndex = startIndex % self._DynamicTable.Imp.TotalCount + 1
        self:_UpdateSelect()
        -- 滑动停下时把"当前选中"以 musicID 发起跳转播放(随机模式内部会重建随机序列)

        local selectMusicID = self:_GetCurSeverDataList()[selectIndex]
        local cdControl = self._Control:GetCDPlayerControl()
        local useStatus = cdControl:GetMusicUseStatusAndConditionDesc(selectMusicID)
        if useStatus ~= XMVCA.XMusicPlayer.Enum.MusicUseStatus.unlock then
            cdControl:JumpPlayByMusicIDWithNotify(self:_GetCurListType(), selectMusicID)
        end
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_TOUCHED then
        self._DynamicTable.Imp:TweenToIndex(index)
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_BEGIN_DRAG then
        -- 原界面这里调 self:PlayFrontEffect(false) 关闭前景特效,本视图暂无对应资源,留空
    end
end


function XUIMusciPlayerAlbumCollectionView:_SetEvent(flag)
    local XMusicPlayerEventId = XMVCA.XMusicPlayer.EventIds
    if flag then
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_MUSICLIST_UPDATE, self._OnMusicListUpdate, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_PLAYER_MUSIC_CHANGE, self._OnCurPlayMusicChange, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_CHANGE_UI_COLOR_STYLE, self._OnColorStyleChange, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_COLOR_MATERIAL_LOADED, self._OnColorMaterialLoaded, self)
    else
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_MUSICLIST_UPDATE, self._OnMusicListUpdate, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_PLAYER_MUSIC_CHANGE, self._OnCurPlayMusicChange, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_CHANGE_UI_COLOR_STYLE, self._OnColorStyleChange, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_COLOR_MATERIAL_LOADED, self._OnColorMaterialLoaded, self)
    end
end


function XUIMusciPlayerAlbumCollectionView:_OnMusicListUpdate(listType)
    if listType ~= nil and listType ~= self:_GetCurListType() then
        return
    end
    self:_UpdateDynamicTable()
    self:_UpdateSelect()
end

function XUIMusciPlayerAlbumCollectionView:_OnCurPlayMusicChange()
    self:_UpdateDynamicTable()
    self:_UpdateSelect()
end

function XUIMusciPlayerAlbumCollectionView:_OnColorStyleChange()
    self:_refreshColorFX()
end

function XUIMusciPlayerAlbumCollectionView:_OnColorMaterialLoaded()
    self:_refreshColorFX()
end

function XUIMusciPlayerAlbumCollectionView:OnBtnCloseAlbumClick()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE,XMusicPlayerEnum.MusicMainUIStatus.mainCD)
end

---@param musicID number   
---@return table musicCO 形似 album template,带 Cover / ConditionId / Name 等字段,可直接喂给 XUiGridMusicPlayer
function XUIMusciPlayerAlbumCollectionView:_GetMusicCO(musicID)
    return self._Control:GetMusicPlayerconfigControl():GetMusicPlayerAlbumCOByid(musicID)
end


---@return number 当前展示的歌单类型(始终跟随 CDPlayerControl 当前播放的列表类型)
function XUIMusciPlayerAlbumCollectionView:_GetCurListType()
    return self._Control:GetCDPlayerControl():GetCurMusicListType()
end

---@return number[] 服务端原始歌单 musicID 列表(取数方式与 XUiMusicPlayerMusicListView:_GetCurSeverDataList 一致)
function XUIMusciPlayerAlbumCollectionView:_GetCurSeverDataList()
    return self._MusicListControl:GetSeverMusicListByListType(self:_GetCurListType()) 
end

---@return number 当前正在播放的索引(1-based,基于服务端原始歌单);列表为空时返回 0
function XUIMusciPlayerAlbumCollectionView:_GetCurIndex()
    local list = self:_GetCurSeverDataList()
    if #list <= 0 then
        return 0
    end
    -- 优先使用 cell 点击跳转的 musicID,没有则用当前播放的歌
    local jumpMusicID = self._Control:GetJumpAlbumCollectionClickMusicID()
    self._Control:ClearJumpAlbumCollectionClickMusicID()
    local curMusicID = jumpMusicID or self._Control:GetCDPlayerControl():GetCurPlayingMusicID()
    local idx = table.indexof(list, curMusicID)
    if not idx or idx < 1 or idx > #list then
        return 1
    end
    return idx
end

function XUIMusciPlayerAlbumCollectionView:_refreshColorFX()
    local UiMaterialKey = XMVCA.XMusicPlayer.Enum.UiMaterialKey

    local mat = self._Control:GetCurColorMat(UiMaterialKey.MusicCurve4)
    if mat and self.RImgMusicCurve4 then
        self.RImgMusicCurve4.material = mat
    end
end

return XUIMusciPlayerAlbumCollectionView
