--[[
-- XUiMusicPlayerConsoleBtnView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-01 20:02:28
--]]

---@class XUiMusicPlayerConsoleBtnView : XUiNode
---@field _Control XMusicPlayerControl
---@field BtnPlayerMode XUiComponent.XUiButton
---@field BtnSwitchLast XUiComponent.XUiButton
---@field BtnPlayMusic XUiComponent.XUiButton
---@field BtnStopMusic XUiComponent.XUiButton
---@field BtnSwitchNext XUiComponent.XUiButton
---@field TxtMusicCurrent UnityEngine.UI.Text
---@field TxtMusicTotal UnityEngine.UI.Text
---@field ImgProgress UnityEngine.UI.Image
---@field GoPlayerModeNormalListLoop UnityEngine.RectTransform
---@field GoPlayerModeNormalSingleLoop UnityEngine.RectTransform
---@field GoPlayerModeNormalRandomLoop UnityEngine.RectTransform
---@field GoPlayerModePressListLoop UnityEngine.RectTransform
---@field GoPlayerModePressSingleLoop UnityEngine.RectTransform
---@field GoPlayerModePressRandomLoop UnityEngine.RectTransform
---@field BtnPlaylist XUiComponent.XUiButton
---@field GoProgressBar UnityEngine.RectTransform
---@field GOImgBg UnityEngine.RectTransform
---@field TxtPlaylistNTip UnityEngine.UI.Text
---@field TxtPlaylistPTip UnityEngine.UI.Text
---@field TxtPlaylistLTip UnityEngine.UI.Text
---@field ImgPlay UnityEngine.UI.Image
---@field ImgColorPlay1 UnityEngine.UI.Image    
---@field ImgColorPlay2 UnityEngine.UI.Image
---@field ImgColorStop1 UnityEngine.UI.Image
---@field ImgColorStop2 UnityEngine.UI.Image
local XUiMusicPlayerConsoleBtnView = XClass(XUiNode, "XUiMusicPlayerConsoleBtnView")
function XUiMusicPlayerConsoleBtnView:InitComponents()
    -- Button
    self.BtnPlayerMode:AddEventListener(function() self:OnBtnPlayerModeClick() end)
    self.BtnSwitchLast:AddEventListener(function() self:OnBtnSwitchLastClick() end)
    self.BtnPlayMusic:AddEventListener(function() self:OnBtnPlayMusicClick() end)
    self.BtnStopMusic:AddEventListener(function() self:OnBtnStopMusicClick() end)
    self.BtnSwitchNext:AddEventListener(function() self:OnBtnSwitchNextClick() end)
    self.BtnPlaylist:AddEventListener(function() self:OnBtnPlaylistClick() end)
end

function XUiMusicPlayerConsoleBtnView:OnStart(...)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self._LoopModelShow = {
        [XMusicPlayerEnum.LoopType.ListLoop] = {self.GoPlayerModeNormalListLoop,self.GoPlayerModePressListLoop},
        [XMusicPlayerEnum.LoopType.SingleLoop] = {self.GoPlayerModeNormalSingleLoop,self.GoPlayerModePressSingleLoop},
        [XMusicPlayerEnum.LoopType.RandomLoop] = {self.GoPlayerModeNormalRandomLoop,self.GoPlayerModePressRandomLoop}
    }

 
    self:InitComponents()

    local XUiTextScrolling = require("XUi/XUiTaikoMaster/XUiTaikoMasterFlowText")
    self._PlaylistNTipScrolling = XUiTextScrolling.New(self.TxtPlaylistNTip, self.TxtPlaylistNTip.transform.parent)
    self._PlaylistNTipScrolling:Stop()
    self._PlaylistPTipScrolling = XUiTextScrolling.New(self.TxtPlaylistPTip, self.TxtPlaylistPTip.transform.parent)
    self._PlaylistPTipScrolling:Stop()
    self._PlaylistLTipScrolling = XUiTextScrolling.New(self.TxtPlaylistLTip, self.TxtPlaylistLTip.transform.parent)
    self._PlaylistLTipScrolling:Stop()

    self:_Refresh()
end

--- 启用时注册定时器，每100毫秒调用一次_Tick方法
function XUiMusicPlayerConsoleBtnView:OnEnable()
    self:_SetEvent(true)
    self:_OnUIColorStyleChange()
end

function XUiMusicPlayerConsoleBtnView:OnDisable()
    self:_SetEvent(false)
end

-- 当前播放所属列表类型变化时,刷新播放列表提示文本
function XUiMusicPlayerConsoleBtnView:_OnCurPlayListTypeChange(listType)
    self:_RefreshPlaylistTip()
end

function XUiMusicPlayerConsoleBtnView:_OnPlayStateChange(isPlaying)
    self:_RefreshPlayBtnState()
end

function XUiMusicPlayerConsoleBtnView:OnDestroy()

end


---region 控制台按钮事件
function XUiMusicPlayerConsoleBtnView:OnBtnPlayerModeClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local cur = self._Control:GetCDPlayerControl():GetMusicCycleType()

    local next
    if cur == XMusicPlayerEnum.LoopType.ListLoop then
        next = XMusicPlayerEnum.LoopType.SingleLoop
    elseif cur == XMusicPlayerEnum.LoopType.SingleLoop then
        next = XMusicPlayerEnum.LoopType.RandomLoop
    else
        next = XMusicPlayerEnum.LoopType.ListLoop
    end
    self._Control:GetCDPlayerControl():SwitchMusicCycleType(next)
 
    self:_RefreshLoopBtnState()
    self:_PopupLoopModeTip(next)
    self:_DispatchConsoleBtnClick()
end

function XUiMusicPlayerConsoleBtnView:_PopupLoopModeTip(loopType)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local textKey
    if loopType == XMusicPlayerEnum.LoopType.SingleLoop then
        textKey = "MusicPlayerLoopTypeSingleLoop"
    elseif loopType == XMusicPlayerEnum.LoopType.RandomLoop then
        textKey = "MusicPlayerLoopTypeRandomLoop"
    else
        textKey = "MusicPlayerLoopTypeListLoop"
    end
    XUiManager.PopupLeftTip(nil, CS.XTextManager.GetText(textKey), nil)
end


function XUiMusicPlayerConsoleBtnView:OnBtnSwitchLastClick(eventData)
    self._Control:GetCDPlayerControl():PlayPrevMusic()
    self:_Refresh()
    self:_DispatchConsoleBtnClick()
end

function XUiMusicPlayerConsoleBtnView:OnBtnSwitchNextClick(eventData)
    self._Control:GetCDPlayerControl():PlayNextMusic()
    self:_Refresh()
    self:_DispatchConsoleBtnClick()
end


function XUiMusicPlayerConsoleBtnView:OnBtnPlayMusicClick(eventData)
    self._Control:GetCDPlayerControl():ResumeMusic()
    self:_RefreshPlayBtnState()
    self:_DispatchConsoleBtnClick()
end

function XUiMusicPlayerConsoleBtnView:OnBtnPlaylistClick(eventData)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local cdControl = self._Control:GetCDPlayerControl()
    local curMusicID = cdControl:GetCurPlayingMusicID()
    local useStatus = cdControl:GetMusicUseStatusAndConditionDesc(curMusicID)
    if useStatus == XMusicPlayerEnum.MusicUseStatus.limitedFree then
        local co = self._Control:GetMusicPlayerconfigControl():GetMusicPlayerAlbumCOByid(curMusicID)
        if co and XTool.IsNumberValid(co.SkipId) then
            XFunctionManager.SkipInterface(co.SkipId)
        end
    else
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_JUMP_PLAYLIST, curMusicID)
    end
end 

function XUiMusicPlayerConsoleBtnView:OnBtnStopMusicClick(eventData)
    self._Control:GetCDPlayerControl():PauseMusic()
    self:_RefreshPlayBtnState()
    self:_DispatchConsoleBtnClick()
end


 
function XUiMusicPlayerConsoleBtnView:_DispatchConsoleBtnClick()
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CONSOLE_BTN_CLICK)
end


---endregion


---region event
function XUiMusicPlayerConsoleBtnView:_SetEvent(flag)
    local EventIds = XMVCA.XMusicPlayer.EventIds
    if flag then
        self._TickScheduleId = XScheduleManager.ScheduleForever(function()
            self:_Tick()
        end, 100, 0)
        self._Control:AddEventListener(EventIds.EVENT_VIEW_UPDATE_STATE, self._OnMainViewStatusChange, self)
        self._Control:AddEventListener(EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE, self._OnCurPlayListTypeChange, self)
        self._Control:AddEventListener(EventIds.EVENT_CHANGE_UI_COLOR_STYLE, self._OnUIColorStyleChange, self)
        self._Control:AddEventListener(EventIds.EVENT_PLAYER_PLAY_STATE_CHANGE, self._OnPlayStateChange, self)
    else
        if self._TickScheduleId then
            XScheduleManager.UnSchedule(self._TickScheduleId)
            self._TickScheduleId = nil
        end
        self._Control:RemoveEventListener(EventIds.EVENT_VIEW_UPDATE_STATE, self._OnMainViewStatusChange, self)
        self._Control:RemoveEventListener(EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE, self._OnCurPlayListTypeChange, self)
        self._Control:RemoveEventListener(EventIds.EVENT_CHANGE_UI_COLOR_STYLE, self._OnUIColorStyleChange, self)
        self._Control:RemoveEventListener(EventIds.EVENT_PLAYER_PLAY_STATE_CHANGE, self._OnPlayStateChange, self)
    end
end

function XUiMusicPlayerConsoleBtnView:_OnUIColorStyleChange()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local playSpritePath = self._Control:GetCurColorUiSprite(XMusicPlayerEnum.UiSpriteKey.PlayMusicBtn)
    if playSpritePath then
        self.ImgColorPlay1:SetSprite(playSpritePath)
        self.ImgColorPlay2:SetSprite(playSpritePath)
    end
    local stopSpritePath = self._Control:GetCurColorUiSprite(XMusicPlayerEnum.UiSpriteKey.StopMusicBtn)
    if stopSpritePath then
        self.ImgColorStop1:SetSprite(stopSpritePath)
        self.ImgColorStop2:SetSprite(stopSpritePath)
    end
end

function XUiMusicPlayerConsoleBtnView:_Tick()
    local audioInfo = XLuaAudioManager.GetCurrentMusicAudioInfo()
    if audioInfo then
        local CueId = self._Control:GetCDPlayerControl():GetCurPlayingMusicCO().CueId
        -- GetCueWavRealDuration 返回毫秒，统一转换为秒处理
        local musicTimeSec = CS.XAudioManager.GetCueWavRealDuration(CueId) / 1000

        if musicTimeSec > 0 then
            -- audioInfo.Time 单位为秒，对总时长取模，避免循环播放时超出
            local currentTimeSec = (audioInfo.Time/1000) % musicTimeSec
            local curTotalSec = math.floor(currentTimeSec)
            local curMin = math.floor(curTotalSec / 60)
            local curSec = curTotalSec % 60
            self.TxtMusicCurrent.text = string.format("%02d:%02d", curMin, curSec)

            local durationSec = math.floor(musicTimeSec)
            local totalMin = math.floor(durationSec / 60)
            local totalSec = durationSec % 60
            self.TxtMusicTotal.text = string.format("%02d:%02d", totalMin, totalSec)

            local progress = currentTimeSec / musicTimeSec
            self.ImgProgress.fillAmount = progress
        else
            local curTotalSec = math.floor(audioInfo.Time or 0)
            local curMin = math.floor(curTotalSec / 60)
            local curSec = curTotalSec % 60
            self.TxtMusicCurrent.text = string.format("%02d:%02d", curMin, curSec)
            self.TxtMusicTotal.text = "--:--"
            self.ImgProgress.fillAmount = 0
        end
    else
        self.TxtMusicCurrent.text = "00:00"
        self.TxtMusicTotal.text = "00:00"
        self.ImgProgress.fillAmount = 0
    end
end
---endregion


function XUiMusicPlayerConsoleBtnView:_Refresh()
    self:_RefreshPlayBtnState()
    self:_UpdateAlbumInfoText()
    self:_RefreshLoopBtnState()
    self:_RefreshPlaylistTip()
    self:_Tick()
end

-- 刷新播放列表提示:限时免费优先显示限免提示,否则按当前播放歌曲所属列表显示对应描述
function XUiMusicPlayerConsoleBtnView:_RefreshPlaylistTip()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local cdControl = self._Control:GetCDPlayerControl()
    local curMusicID = cdControl:GetCurPlayingMusicID()
    local useStatus = cdControl:GetMusicUseStatusAndConditionDesc(curMusicID)

    local tip
    if useStatus == XMusicPlayerEnum.MusicUseStatus.limitedFree then
        tip = CS.XTextManager.GetText("MusicPlayerPlaylistTipLimitedFree")
    else
        local listType = cdControl:GetCurMusicListType()
        if listType == XMusicPlayerEnum.MusicListType.BGM then
            tip = CS.XTextManager.GetText("MusicPlayerPlaylistTipBgm")
        elseif listType == XMusicPlayerEnum.MusicListType.Favorite then
            tip = CS.XTextManager.GetText("MusicPlayerPlaylistTipFavorite")
        else
            tip = CS.XTextManager.GetText("MusicPlayerPlaylistTipNormal")
        end
    end
    self.TxtPlaylistNTip.text = tip
    self._PlaylistNTipScrolling:Play()
    self.TxtPlaylistPTip.text = tip
    self._PlaylistPTipScrolling:Play()
    self.TxtPlaylistLTip.text = tip
    self._PlaylistLTipScrolling:Play()
end

function XUiMusicPlayerConsoleBtnView:_RefreshLoopBtnState()
    local cur = self._Control:GetCDPlayerControl():GetMusicCycleType()
    XMVCA.XMusicPlayer.Util.ShowUIByStatus(self._LoopModelShow, cur)   
end

function XUiMusicPlayerConsoleBtnView:_RefreshPlayBtnState()
    local isPlaying = self._Control:GetCDPlayerControl():IsPlaying()
    self.BtnPlayMusic.gameObject:SetActive(not isPlaying)
    self.BtnStopMusic.gameObject:SetActive(isPlaying)
end

function XUiMusicPlayerConsoleBtnView:_UpdateAlbumInfoText()
    local musicCO = self._Control:GetCDPlayerControl():GetCurPlayingMusicCO()
end

function XUiMusicPlayerConsoleBtnView:_OnMainViewStatusChange(lastStatus,curStatus)

    local MusicMainUIStatus = XMVCA.XMusicPlayer.Enum.MusicMainUIStatus
    
    if  lastStatus == MusicMainUIStatus.immersePro then
        self.GameObject:SetActive(true)
    end
    if lastStatus == MusicMainUIStatus.immerse and curStatus ~= MusicMainUIStatus.immersePro then
        self.BtnPlaylist.gameObject:SetActive(true)
        self.GoProgressBar.gameObject:SetActive(true)
        self.GoImgBg.gameObject:SetActive(true)
    end

    if curStatus == MusicMainUIStatus.immerse then
        self.BtnPlaylist.gameObject:SetActive(false)
        self.GoProgressBar.gameObject:SetActive(false)
        self.GoImgBg.gameObject:SetActive(false)
    elseif curStatus == MusicMainUIStatus.immersePro   then
        self.GameObject:SetActive(false)
    end
end

return XUiMusicPlayerConsoleBtnView
