--[[
-- XUiPunishaarFightMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-23 16:11:24
--]]

local XUiPunishaarFightMainPanelShop       = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiShop/XUiPunishaarFightMainPanelShop")
local XUiPunishaarFightMainPanelFightBefore = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiPreFight/XUiPunishaarFightMainPanelFightBefore")
local XUiPunishaarFightMainPanelFighting    = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiFighting/XUiPunishaarFightMainPanelFighting")
local XUiPunishaarFightMainPanelBase        = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiBase/XUiPunishaarFightMainPanelBase")
local XUiPunishaarFightMainCommonFightMain = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiCommonTop/XUiPunishaarFightMainCommonFightMain")
local XUiPanelPunishaarTipsRoot = require("XUi/XUiPunishaar/XUiPunishaarCommonCardDetail/XUiPanelPunishaarTipsRoot")
local XUiPunishaarModelShow = require("XUi/XUiPunishaar/XUiPunishaarFightMain/CommonUiTemplate/XUiPunishaarModelShow")
local XUiPanelPunishaarGuideTips = require("XUi/XUiPunishaar/XUiPunishaarFightMain/XUiPanelPunishaarGuideTips")

---@class XUiPunishaarFightMain : XLuaUi
---@field _Control XPunishaarControl
---@field PanelShop UnityEngine.RectTransform
---@field PanelFightBefore UnityEngine.RectTransform
---@field PanelFighting UnityEngine.RectTransform
---@field PanelBase UnityEngine.RectTransform 基底态内容面板（背包编排，独立于 PanelFightBefore）#66
---@field CommonFightMain UnityEngine.RectTransform
---@field CardTipsPanelRoot UnityEngine.RectTransform
---@field TipsRoot XUiPanelPunishaarTipsRoot
---@field ModelShow XUiPunishaarModelShow 卡牌/敌人 3D 模型控制（挂点经 prefab UiObject 引用 PanelRoleModel1..N + PanelEnemyModel）#63
---@field PanelGuideTips UnityEngine.RectTransform HUD 引导提示子节点（挂 XUiPanelPunishaarGuideTips，头像+文案，condition 驱动显隐 TODO）#86
local XUiPunishaarFightMain = XLuaUiManager.Register(XLuaUi, "UiPunishaarFightMain")

function XUiPunishaarFightMain:OnAwake()
    self:InitComponents()
end

function XUiPunishaarFightMain:InitComponents()
    -- 面板根节点先默认隐藏
    self.PanelShop.gameObject:SetActiveEx(false)
    self.PanelFightBefore.gameObject:SetActiveEx(false)
    self.PanelFighting.gameObject:SetActiveEx(false)
    if self.PanelBase then
        self.PanelBase.gameObject:SetActiveEx(false)
    end
    self.CommonFightMain.gameObject:SetActiveEx(false)
    
    ---@type XUiPunishaarFightMainCommonFightMain
    self.PanelTop = XUiPunishaarFightMainCommonFightMain.New(self.CommonFightMain, self)
    self.PanelTop:Open()

    -- TipsRoot：常驻 Open，挂在 CardTipsPanelRoot 下，按对象路由 3 个子 Tips
    self.CardTipsPanelRoot.gameObject:SetActiveEx(false)
    ---@type XUiPanelPunishaarTipsRoot
    self.TipsRoot = XUiPanelPunishaarTipsRoot.New(self.CardTipsPanelRoot, self)
    self.TipsRoot:Open()

    -- ModelShow：3D 模型控制（uiRoot=UiModelGo，其 UiObject 引用 PanelRoleModel1..N + PanelEnemyModel 挂点）。#63
    ---@type XUiPunishaarModelShow
    self.ModelShow = XUiPunishaarModelShow.New(self.UiModelGo, self)
    self.ModelShow:Open()

    -- 注入 ModelShow 给 RoleModelUiShow（消除其上行读 Parent.Parent.ModelShow #UI-R3）
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:SetModelShow(self.ModelShow)
    end

    -- HUD 引导提示（PanelGuideTips：头像+文案+BtnClose 关闭；节点推进选+缓存，SwitchToState 刷新显隐 #86/#93）
    if self.PanelGuideTips then
        self._GuideTips = XUiPanelPunishaarGuideTips.New(self.PanelGuideTips, self)
        self.PanelGuideTips.gameObject:SetActiveEx(false)
        self._GuideTips:SetOnClose(handler(self, self._DismissGuideTips))  -- BtnClose 点击关：标 DismissHud + Hide
    end
end

function XUiPunishaarFightMain:OnStart(state)
    -- 不在此切态：OnStart 时机可能早于 root 激活，切子面板会触发"父节点 inactive"报错。
    -- 子态切换统一放 OnEnable（此时 EnableChildNodes 已激活 root），见 SwitchToState 调用点。
end

--- 切换到指定 FightState 子面板（OnEnable 主动同步 + 局内事件刷态共用入口）。
--- 幂等：目标态与当前一致时重复切换无副作用（各 _OpenXxxPanel 会先关旧 panel 再开目标）。
---@param state number FightState 枚举
function XUiPunishaarFightMain:SwitchToState(state)
    local FightState = XMVCA.XPunishaar.EnumConst.FightState
    if state == FightState.Base then
        self:_OpenBasePanel()
    elseif state == FightState.Shopping then
        self:_OpenShopPanel()
    elseif state == FightState.PreFight then
        self:_OpenPreFightPanel()
    elseif state == FightState.Fighting then
        self:_OpenFightingPanel()
    end
    -- 切态后刷新 HUD 引导提示（FightMain 显时，规则3b：读 GetDisplayHud 显/隐）#86
    self:_RefreshGuideTips()
    -- 内部状态切换手动触发引导检测（FightMain 已打开，子态切换需重新检测当前界面引导；仿 XGuideManager:424 先例）#引导触发
    XDataCenter.GuideManager.CheckGuideOpen()
end

--- 刷新 HUD 引导提示（读 GameControl:GetDisplayHud 显/隐；未手动关闭则显当前节点选的 HUD）。#86
function XUiPunishaarFightMain:_RefreshGuideTips()
    local gc = self._Control and self._Control.GameControl
    if not gc or not self._GuideTips then
        return
    end
    local hudCfg = gc:GetDisplayHud()
    XLog.Debug("[HudTrace][3传达] _RefreshGuideTips GetDisplayHud=" .. (hudCfg and hudCfg.Id or "nil"))
    if hudCfg then
        self._GuideTips:Show(hudCfg)
    else
        self._GuideTips:Hide()
    end
end

--- 玩家手动关闭 HUD（标记本次节点不再显 + 隐）。#86
--- 由 GuideTips:BtnClose 点击触发（SetOnClose 注入回调，GuideTips:OnStart 绑定）。
function XUiPunishaarFightMain:_DismissGuideTips()
    local gc = self._Control and self._Control.GameControl
    if gc then
        gc:DismissHud()
    end
    if self._GuideTips then
        self._GuideTips:Hide()
    end
end

--- 背包暂存区展开：纯遮蔽隐 HUD（仅 Hide，不标 DismissHud，收起后 _RefreshGuideTips 可恢复）#背包HUD互斥
function XUiPunishaarFightMain:_OnBagOpen()
    if self._GuideTips then
        self._GuideTips:Hide()
    end
end

--- 背包暂存区收起：恢复 HUD 显隐（读 GetDisplayHud，未手动关且当前有 cfg 才显）#背包HUD互斥
function XUiPunishaarFightMain:_OnBagClose()
    self:_RefreshGuideTips()
end

--- 商店刷新成功：播 ReShow 根动画（服务端下发新商品，商品列表刷新动效）。#商店刷新动效
function XUiPunishaarFightMain:_OnShopRefreshSuccess()
    self:PlayAnimation("ReShow")
end

--- 商店刷新链路失败：播 ReShowFail 根动画（服务端 Code 失败 / 网络异常）。#商店刷新动效
function XUiPunishaarFightMain:_OnShopRefreshFail()
    self:PlayAnimation("ReShowFail")
end

--- 商店栏展开动效：播 PanelShopAnimEnable 根动画（切态进入/BtnExpand/互斥还原/PickHost退出）。#商店栏动效
function XUiPunishaarFightMain:_OnShopPanelAnimEnable()
    self:PlayAnimation("PanelShopAnimEnable")
end

--- 商店栏收起动效：播 PanelShopDisable 根动画（BtnFoldUp/背包展开前/PickHost进入）。#商店栏动效
function XUiPunishaarFightMain:_OnShopPanelAnimDisable()
    self:PlayAnimation("PanelShopDisable")
end

function XUiPunishaarFightMain:OnEnable()
    -- root 此时已由 OnEnableUi 的 EnableChildNodes 激活，切子面板不会触发父节点 inactive 报错。
    -- 子面板启停控制权收归本逻辑：OnDisable 已主动 Close 掉 CurPanel（其 _IsNodeShow=false），
    -- 故框架 EnableChildNodes 不会自动恢复旧子面板；这里按流程管理器当前状态显式 Open 正确子面板。
    -- 好处：状态若已变，不会让上一子面板的 OnEnable 逻辑（如 FightingPanel 的 EnterFight）被误激活一遍；
    -- 状态不变也走同样的显式 Open 流程，控制交给逻辑而非框架自动级联。
    if not (self._Control and self._Control.GameControl) and XMain.IsWindowsEditor then
        -- 测试工具路径（CommitBattleTest 直开本界面，未走 EnterRun）：无 GameControl。
        -- 仅 Editor 环境走测试豁免（非 Editor 静默跳过，让正常流程处理——可能是 bug 误入此分支）。
        -- 就地建 GameControl + 设 FightState=Fighting + 标记 _IsTestMode，随后 fall-through 走与正式相同的
        -- OnEnable 同步路径：SwitchToState(Fighting) → FightingPanel.OnEnable → Control:EnterFight
        -- → 从 Model 取调试契约 StartBattle。OnBattleEnded 据 _IsTestMode 走测试结算（不调服务端）。
        self._Control:InitGameControl()
        local runControl = self._Control.GameControl.RunControl
        runControl._IsTestMode = true
        runControl._CurrentFightState = XMVCA.XPunishaar.EnumConst.FightState.Fighting
    end
    local runControl = self._Control.GameControl.RunControl
    local gc = self._Control.GameControl
    -- 商店栏动效订阅放 SwitchToState 前：首次切态开 PanelShop 时 OnEnable 派发 ShopPanelAnimEnable，须已订阅 #商店栏动效
    gc:AddEventListener(gc.ShopEventId.ShopPanelAnimEnable, self._OnShopPanelAnimEnable, self)
    gc:AddEventListener(gc.ShopEventId.ShopPanelAnimDisable, self._OnShopPanelAnimDisable, self)
    -- 背包↔HUD 互斥订阅（局内事件 gc.BagEventId；背包开合派发→隐/恢复 HUD）#背包HUD互斥
    gc:AddEventListener(gc.BagEventId.Open, self._OnBagOpen, self)
    gc:AddEventListener(gc.BagEventId.Close, self._OnBagClose, self)
    -- 拖拽开始自动关 Tips（防视觉遮挡；BtnClose 射线穿透不阻塞拖拽，此为视觉优化）§11
    XEventManager.AddEventListener(XEventId.EVENT_PUNISHAAR_DRAG_BEGIN, self._OnDragBegin, self)
    local state = runControl:GetCurrentFightState()
    if state then
        self:SwitchToState(state)
    end
    runControl:AddEventListener(
        runControl.RunEventId.FightStateChanged,
        self.SwitchToState, self)
    -- 商店刷新动效：订阅 RefreshShopSuccess/Fail 播根动画 #商店刷新动效
    gc:AddEventListener(gc.ShopEventId.RefreshShopSuccess, self._OnShopRefreshSuccess, self)
    gc:AddEventListener(gc.ShopEventId.RefreshShopFail, self._OnShopRefreshFail, self)
    -- FightMain OnEnable 就绪（监听已注册）后主动触发节点路由，替代 OpenWithCallback onReady（不等 AnimEnable 动画）。#OpenAfterAnim
    -- 子态分支 sync 立即切消入场动画 ~2秒等待；新面板分支受 OperatingMask 自动排队等动画。仅首次进入触发（_PendingRouteNode 由 EnterRun 设）。
    runControl:OnFightMainReady()
end

function XUiPunishaarFightMain:OnDisable()
    -- 主动 Close 当前子面板（Close 幂等）：置其 _IsNodeShow=false，使框架 EnableChildNodes 在
    -- 本界面恢复时跳过它、不自动重激活——子面板由 OnEnable 按最新状态显式开，避免旧状态逻辑误激活。
    if self.CurPanel then
        self.CurPanel:Close()
    end
    self:_HideTalkTips()
    -- 注销状态切换事件：避免 root inactive 期间仍收到切态事件去激活子节点导致报错。
    self:_UnregisterStateListener()
    -- 注销商店刷新动效事件（对称）
    if self._Control and self._Control.GameControl then
        local gc = self._Control.GameControl
        gc:RemoveEventListener(gc.ShopEventId.RefreshShopSuccess, self._OnShopRefreshSuccess, self)
        gc:RemoveEventListener(gc.ShopEventId.RefreshShopFail, self._OnShopRefreshFail, self)
        gc:RemoveEventListener(gc.ShopEventId.ShopPanelAnimEnable, self._OnShopPanelAnimEnable, self)
        gc:RemoveEventListener(gc.ShopEventId.ShopPanelAnimDisable, self._OnShopPanelAnimDisable, self)
        -- 背包↔HUD 互斥注销（对称，幂等；同 ShopEventId 注销同级，依赖 gc）#背包HUD互斥
        gc:RemoveEventListener(gc.BagEventId.Open, self._OnBagOpen, self)
        gc:RemoveEventListener(gc.BagEventId.Close, self._OnBagClose, self)
    end
    -- 拖拽关 Tips 注销（全局事件不依赖 gc；幂等）§11
    XEventManager.RemoveEventListener(XEventId.EVENT_PUNISHAAR_DRAG_BEGIN, self._OnDragBegin, self)
end

function XUiPunishaarFightMain:OnDestroy()
    -- 兜底注销：ExitRun 用 XLuaUiManager.Remove 移除 FightMain，Remove 不走弹栈/OnDisable 流程，
    -- 监听不会被 OnDisable 注销 → 须在此收口，防残留监听指向已销毁实例。
    self:_UnregisterStateListener()
    if self._Control and self._Control.GameControl then
        local gc = self._Control.GameControl
        gc:RemoveEventListener(gc.ShopEventId.RefreshShopSuccess, self._OnShopRefreshSuccess, self)
        gc:RemoveEventListener(gc.ShopEventId.RefreshShopFail, self._OnShopRefreshFail, self)
        gc:RemoveEventListener(gc.ShopEventId.ShopPanelAnimEnable, self._OnShopPanelAnimEnable, self)
        gc:RemoveEventListener(gc.ShopEventId.ShopPanelAnimDisable, self._OnShopPanelAnimDisable, self)
        -- 背包↔HUD 互斥注销（对称，幂等；同 ShopEventId 注销同级，依赖 gc）#背包HUD互斥
        gc:RemoveEventListener(gc.BagEventId.Open, self._OnBagOpen, self)
        gc:RemoveEventListener(gc.BagEventId.Close, self._OnBagClose, self)
    end
    -- 拖拽关 Tips 注销兜底（全局事件不依赖 gc；幂等）§11
    XEventManager.RemoveEventListener(XEventId.EVENT_PUNISHAAR_DRAG_BEGIN, self._OnDragBegin, self)
end

--- 注销状态切换事件监听（OnDisable 与 OnDestroy 兜底共用，幂等：AddEventListener 有防重复，
--- 未注册时 RemoveEventListener 无副作用）。
function XUiPunishaarFightMain:_UnregisterStateListener()
    if self._Control and self._Control.GameControl then
        local runControl = self._Control.GameControl.RunControl
        runControl:RemoveEventListener(
            runControl.RunEventId.FightStateChanged,
            self.SwitchToState, self)
    end
end

--- 显示对话气泡（转发 RoleModelUiShow → EnemyDetail → TalkTips）#对话接入
---@param text string 对话文本
function XUiPunishaarFightMain:_ShowTalkTips(text)
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:ShowTalkTips(text)
    end
end

--- 隐藏对话气泡（切走 Shopping 清，敌人态/无对话也调）
function XUiPunishaarFightMain:_HideTalkTips()
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:HideTalkTips()
    end
end

function XUiPunishaarFightMain:_OpenBasePanel()
    if self.CurPanel then
        self.CurPanel:Close()
    end
    self:_HideTalkTips()

    -- 顶部 HUD 按 Base 归属配置（无论 PanelBase 是否就位都先配，降级时也正确）
    self.PanelTop:SetShowOnBase()

    -- Base 无战斗上下文：释放商人/敌人模型（从 Shopping 切来时商人需释放）#商人接入
    if self.ModelShow then
        self.ModelShow:ReleaseEnemyModel()
    end
    -- 敌方副卡槽对称关闭（Base 无敌人模型）#副卡槽联动
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:HideEnemyDetail()
    end

    if not self.PanelBase then
        XLog.Error("[PunishaarFightMain] _OpenBasePanel: PanelBase 节点缺失，请检查 FightMain prefab 是否已加 PanelBase")
        return
    end

    if not self.BasePanel then
        ---@type XUiPunishaarFightMainPanelBase
        self.BasePanel = XUiPunishaarFightMainPanelBase.New(self.PanelBase, self)
    end

    self.BasePanel:Open()

    -- Base 态无战斗上下文：不预览敌人模型（与 PreFight/Fighting 的 RefreshEnemyModel 对称省略）#66
    self.CurPanel = self.BasePanel
end

function XUiPunishaarFightMain:_OpenPreFightPanel()
    if self.CurPanel then
        self.CurPanel:Close()
    end
    self:_HideTalkTips()

    if not self.PreFightPanel then
        ---@type XUiPunishaarFightMainPanelFightBefore
        self.PreFightPanel = XUiPunishaarFightMainPanelFightBefore.New(self.PanelFightBefore, self)
    end

    self.PreFightPanel:Open()
    self.PanelTop:SetShowOnPreFight()

    -- 战前预览敌人/Boss 模型（契约 fightId→Fight.EnemyId→Enemy.EnemyModel）#63
    if self.ModelShow then
        self.ModelShow:RefreshEnemyModel()
    end
    -- 敌方副卡槽对称显（PreFight 有敌人模型）#副卡槽联动
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:ShowEnemyDetail()
    end

    self.CurPanel = self.PreFightPanel
end

function XUiPunishaarFightMain:_OpenShopPanel()
    if self.CurPanel then
        self.CurPanel:Close()
    end
    self:_HideTalkTips()

    -- 补强商店显默认 group HUD（补强是战斗节点 Remedy 状态非独立节点，无法配 StageContent.HudGroupId，
    -- 共用 PunishaarConfig.RemedyShopHudGroupId；SelectHudByGroup 在切态末 _RefreshGuideTips 前调，确保读到新 _HudCfg）#补强HUD
    if self._Control:IsInRemedyShop() then
        local remedyShopHudGroupId = self._Control:GetRemedyShopHudGroupId()
        local gc = self._Control.GameControl
        if gc then
            gc:SelectHudByGroup(remedyShopHudGroupId)
        end
    end

    if not self.ShopPanel then
        ---@type XUiPunishaarFightMainPanelShop
        self.ShopPanel = XUiPunishaarFightMainPanelShop.New(self.PanelShop, self)
    end

    self.ShopPanel:Open()
    self.PanelTop:SetShowOnShop()

    -- Shop 无战斗上下文：释放敌人模型（主卡保留——战斗区卡在 Shop 仍显）+ 加载商人模型 #商人接入
    if self.ModelShow then
        self.ModelShow:ReleaseEnemyModel()
        local shopId = self._Control:GetCurrentShopId()
        if shopId and shopId > 0 then
            local shopCfg = self._Control.GameControl:GetTablePunishaarShop(shopId, true)
            if shopCfg then
                -- 商人模型+待机动画：TraderModelId 空则不加载（ShowShopNpcModel 内判空）；动画须模型加载完成后播（callback 内）
                self.ModelShow:ShowShopNpcModel(shopCfg.TraderModelId, shopCfg.NormalIdleAnima)
                -- 商人对话文本：ShopDialog 非空显 TalkTips 设 TxtTalk，空则隐（FightMain Shopping 态接入 #对话接入）
                if not string.IsNilOrEmpty(shopCfg.ShopDialog) then
                    self:_ShowTalkTips(shopCfg.ShopDialog)
                else
                    self:_HideTalkTips()
                end
            end
        end
    end
    -- 敌方副卡槽对称关闭（Shop 无敌人模型，替商人 NPC）#副卡槽联动
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:HideEnemyDetail()
    end

    self.CurPanel = self.ShopPanel
end

function XUiPunishaarFightMain:_OpenFightingPanel()
    if self.CurPanel then
        self.CurPanel:Close()
    end
    self:_HideTalkTips()

    if not self.FightingPanel then
        ---@type XUiPunishaarFightMainPanelFighting
        self.FightingPanel = XUiPunishaarFightMainPanelFighting.New(self.PanelFighting, self)
    end
    
    self.FightingPanel:Open()
    self.PanelTop:SetShowOnFighting()

    -- Fighting 态确保敌人模型加载（与 PreFight 对称；经 PreFight 进则 persist 无害，直接进则补加载）。#63
    if self.ModelShow then
        self.ModelShow:RefreshEnemyModel()
    end
    -- 敌方副卡槽对称显（Fighting 有敌人模型）#副卡槽联动
    if self.PanelTop and self.PanelTop.RoleModelUiShow then
        self.PanelTop.RoleModelUiShow:ShowEnemyDetail()
    end

    self.CurPanel = self.FightingPanel
end

--region   ------------------Tips 转发（封装行为接口，对齐 #75）-------------------

--- 展示主卡详情 Tips（浮窗悬浮于 posUi 旁；data 形态见 XUiPanelPunishaarTipsRoot.ShowMainCard）
---@param data table Server.XPunishaarGoods | Server.XPunishaarMasterCard
---@param posUi UnityEngine.RectTransform|nil 触发元素（卡牌 grid）的 RectTransform，供浮窗定位
function XUiPunishaarFightMain:ShowMainCardTips(data, posUi)
    self.TipsRoot:ShowMainCard(data, posUi)
    -- 模型显示不绑详情：归 ModelShow 订阅 BuySuccess + OnEnable 刷新战斗区卡模型（紧凑序）。#63
end

--- 展示副卡详情 Tips（占位：SubCardTips 骨架未建）
---@param data table
---@param posUi UnityEngine.RectTransform|nil
function XUiPunishaarFightMain:ShowSubCardTips(data, posUi)
    self.TipsRoot:ShowSubCard(data, posUi)
end

--- 展示敌人详情 Tips（占位：EnemyTips 骨架未建）
---@param fightId number
---@param posUi UnityEngine.RectTransform|nil
function XUiPunishaarFightMain:ShowEnemyTips(fightId, posUi)
    self.TipsRoot:ShowEnemy(fightId, posUi)
end

--- 隐藏当前 Tips
function XUiPunishaarFightMain:HideTips()
    self.TipsRoot:Hide()
    -- 模型不绑 Tips：战斗区卡模型归 ModelShow 订阅 BuySuccess + OnEnable 刷新，关 Tips 不释放。#63
end

--- 拖拽开始：自动关 Tips 防视觉遮挡（订阅 EVENT_PUNISHAAR_DRAG_BEGIN；Hide 幂等，无 Tips 时无副作用）。§11
function XUiPunishaarFightMain:_OnDragBegin()
    self:HideTips()
end

--endregion

--region ------------------3D 模型转发（#63）-------------------

--- 展示主卡 3D 模型（slot 默认 1）。查 PunishaarCardModel 取 ModelId + NormalIdleAnima；无行→no-op（2D fallback）。
---@param cardId number 卡牌模板 Id
---@param slotIndex number|nil 卡牌挂点索引 1..N
function XUiPunishaarFightMain:ShowCardModel(cardId, slotIndex)
    if self.ModelShow then
        self.ModelShow:ShowCardModel(cardId, slotIndex)
    end
end

--- 展示敌人 3D 模型（直喂 modelName = enemyCfg.EnemyModel）。
---@param modelName string
---@param idleAnima string|nil
function XUiPunishaarFightMain:ShowEnemyModel(modelName, idleAnima)
    if self.ModelShow then
        self.ModelShow:ShowEnemyModel(modelName, idleAnima)
    end
end

--- 隐藏/释放当前模型（关 Tips/切对象时调，回缓存池）。
function XUiPunishaarFightMain:HideModel()
    if self.ModelShow then
        self.ModelShow:ReleaseModel()
    end
end

--endregion

return XUiPunishaarFightMain
