--[[  auto generated by XUiLuaCodeGenerator (skeleton) -> implementation filled by 填线师 2026-08-03
  主卡升级·副卡保留选择弹窗（表现层）。
  逻辑层↔表现层接缝 = Open(subCardIds, nextLevelCardId, displayLevel, onConfirm, onCancel)；
  调起入口(RunControl:OpenMainCardLevelupTip)+链式检测(GetGoodsUpgradeChain)+BuyGoods 改造属逻辑层（#61 链式）。
  ≥2 张副卡才触发本 UI（BuyGoods 收集 goods+全链被消耗卡副卡，≥2 调起）；≤1 张逻辑层默认继承不开 UI。
]]

local XUiPunishaarMainCardTips = require("XUi/XUiPunishaar/XUiPunishaarCommonCardDetail/UiPunishaarMainCardTips/XUiPunishaarMainCardTips")
local XUiPunishaarSubCardTips = require("XUi/XUiPunishaar/XUiPunishaarCommonCardDetail/UiPunishaarSubCardTips/XUiPunishaarSubCardTips")  -- 副卡列表条目 grid 代理（纯显示）

---@class XUiPunishaarMainCardLevelupTip : XLuaUi
---@field _Control XPunishaarControl
---@field UiPunishaarShopCardTips_Main UiObject 主卡详情区（复用主卡详情面板 XUiPunishaarMainCardTips，readOnly 无操作按钮）
---@field SubCardList XDynamicTableNormal 副卡候选列表（字段名带空格 verbatim）
---@field UiPunishaarShopSubCardTips UiObject 选中副卡详情区（复用副卡详情面板 XUiPunishaarSubCardTips，KeepPlace 模式只显"保留并放入"按钮）
---@field TxtTips UnityEngine.UI.Text 提示文本
local XUiPunishaarMainCardLevelupTip = XLuaUiManager.Register(XLuaUi, "UiPunishaarMainCardLevelupTip")

local KeepPlaceOp = 6

function XUiPunishaarMainCardLevelupTip:OnAwake()
    self:InitComponents()
end

function XUiPunishaarMainCardLevelupTip:InitComponents()
    -- 主卡详情区：复用主卡详情面板 XUiPunishaarMainCardTips（readOnly 无操作按钮，互斥由其 SetOperationMode 驱动）
    if self.UiPunishaarShopCardTips_Main then
        self.MainCardShow = XUiPunishaarMainCardTips.New(self.UiPunishaarShopCardTips_Main, self)
        self.MainCardShow:Open()
    end

    if self.UiPunishaarShopSubCardTips then
        self.UiPunishaarShopSubCardTips.gameObject:SetActiveEx(false)
    end
    
    -- 副卡候选列表：条目 grid 代理复用副卡显示子面板（纯显示，列表条目同结构）
    if self.SubCardList then
        self.DynamicTable = XUiHelper.DynamicTableNormal(self, self.SubCardList, XUiPunishaarSubCardTips)
    end
end

--- 表现层接缝入口（由逻辑层 RunControl:OpenMainCardLevelupTip 转发调起，待逻辑层落地）。
---@param subCardIds number[] 涉及的全部副卡 Id 列表（≥2，UI 列出让玩家选保留 1 张）
---@param nextLevelCardId number 升级后新卡 TemplateId（同卡升级，= goods.CardId）
---@param displayLevel number 升级后最终等级（链式=最终级如 3，单合=商品级+1）
---@param onConfirm fun(chosenSubCardId:number) 玩家选择保留的副卡
---@param onCancel fun() 玩家取消（关闭=不发起本次购买）
function XUiPunishaarMainCardLevelupTip:OnStart(subCardIds, nextLevelCardId, displayLevel, onConfirm, onCancel)
    self._SubCardIdList    = subCardIds or {}
    self._NextLevelCardId = nextLevelCardId
    self._DisplayLevel    = displayLevel
    self._OnConfirm       = onConfirm
    self._OnCancel        = onCancel
    self._Confirmed       = false

    self._SelectedIndex = 1
    self:Refresh()
end

function XUiPunishaarMainCardLevelupTip:Refresh()
    -- 主卡详情区：升级后新卡，readOnly 无操作按钮（_ResolveOperationMode 返 None → SetOperationMode(None) 隐 PanelBuy/PanelSell）
    if self.MainCardShow and self._NextLevelCardId then
        self.MainCardShow:Refresh({
            cardId = self._NextLevelCardId,
            level = self._DisplayLevel or 1,
            readOnly = true,  -- masterCard 留空：升级后新卡实体由逻辑层 Notify 回流后生成，本 UI 显 base（无投影 delta）
        })
        -- readOnly 不隐藏 BtnLock（_RefreshLockBtn 只设文本），主卡无任何按钮需求 → 隐藏 BtnLock
        if self.MainCardShow.BtnLock then
            self.MainCardShow.BtnLock.gameObject:SetActiveEx(false)
        end
    end

    -- 副卡候选列表
    if self.DynamicTable then
        self.DynamicTable:SetDataSource(self._SubCardIdList)
        self.DynamicTable:ReloadDataASync(1)
    end
    
end

---@param event number DYNAMIC_DELEGATE_EVENT
---@param index number 1-based
---@param grid XUiPanelPunishaarSubCard
function XUiPunishaarMainCardLevelupTip:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_INIT then
        grid:SetKeepPlaceConfirm(handler(self, self.OnSubCardKeepPlaceConfirm))
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local subCardId = self._SubCardIdList and self._SubCardIdList[index]
        if subCardId and grid then
            local viewData = {
                cardId        = subCardId,
                operationMode = KeepPlaceOp,
            }
            grid:Refresh(viewData)
        end
    end
end

--- "保留并放入"确认钩子（经 SetKeepPlaceConfirm 自上而下注入 SubCardTips，cardId=副卡详情区当前展示副卡）。
--- 确认保留该副卡 + 关闭 → onConfirm 回逻辑层 build cardDetail 发请求。
function XUiPunishaarMainCardLevelupTip:OnSubCardKeepPlaceConfirm(cardId)
    if not cardId or cardId == 0 then return end
    self._Confirmed = true
    if self._OnConfirm then self._OnConfirm(cardId) end
    self:Close()
end

--- 关闭兜底：未确认即关闭（玩家点外部/返回）= 取消本次购买。
function XUiPunishaarMainCardLevelupTip:OnDisable()
    if not self._Confirmed then
        if self._OnCancel then self._OnCancel() end
    end
    self._Confirmed = nil
end

function XUiPunishaarMainCardLevelupTip:OnDestroy()
    -- 清引用防闭包持卡泄漏
    self._SubCardIdList    = nil
    self._NextLevelCardId = nil
    self._DisplayLevel    = nil
    self._OnConfirm       = nil
    self._OnCancel        = nil
    self._SelectedIndex   = nil
end

return XUiPunishaarMainCardLevelupTip
