--[[
-- XUiPunishaarFightMainPanelAsset.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-23 16:11:24
--]]

---@class XUiPunishaarFightMainPanelAsset : XUiNode
---@field _Control XPunishaarControl
---@field TxtHp UnityEngine.UI.Text
---@field TxtGold UnityEngine.UI.Text
local XUiPunishaarFightMainPanelAsset = XClass(XUiNode, "XUiPunishaarFightMainPanelAsset")
function XUiPunishaarFightMainPanelAsset:InitComponents()
end

function XUiPunishaarFightMainPanelAsset:OnStart(...)
    self:InitComponents()
end

function XUiPunishaarFightMainPanelAsset:OnEnable()
    self:_RefreshGold()
    self:_RefreshHp()
    XEventManager.AddEventListener(XEventId.EVENT_PUNISHAAR_GOLD_CHANGE, self._RefreshGold, self)
end

function XUiPunishaarFightMainPanelAsset:OnDisable()
    XEventManager.RemoveEventListener(XEventId.EVENT_PUNISHAAR_GOLD_CHANGE, self._RefreshGold, self)
end

function XUiPunishaarFightMainPanelAsset:OnDestroy()
end

function XUiPunishaarFightMainPanelAsset:Refresh()
    self:_RefreshGold()
    self:_RefreshHp()
end

function XUiPunishaarFightMainPanelAsset:_RefreshGold()
    if self.TxtGold then
        self.TxtGold.text = tostring(self._Control:GetCurrentGold() or 0)
    end
end

function XUiPunishaarFightMainPanelAsset:_RefreshHp()
    if self.TxtHp then
        self.TxtHp.text = tostring(self._Control:GetCurrentDurability() or 0)
    end
end

return XUiPunishaarFightMainPanelAsset
