--[[
-- XUiPunishaarFightMainCommonFightMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-23 16:11:24
--]]

local XUiPunishaarFightMainPanelAsset = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiCommonTop/XUiPunishaarFightMainPanelAsset")
local XUiPunishaarFightMainGridStage = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiCommonTop/XUiPunishaarFightMainGridStage")
local XUiPBRStageListScrollView = require("XUi/XUiPBRGame/XUiPBRChapter/XUiPBRStageListScrollView")
local XUiPanelPunishaarRoleModelUi = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiCommonTop/UiRoleModelUiShow/XUiPanelPunishaarRoleModelUi")
local XUiPunishaarDamageNumberPlayer = require("XUi/XUiPunishaar/XUiPunishaarFightMain/CommonUiTemplate/Model/XUiPunishaarDamageNumberPlayer")

---@class XUiPunishaarFightMainCommonFightMain : XUiNode
---@field _Control XPunishaarControl
---@field PanelTop UnityEngine.RectTransform
---@field PanelAsset UnityEngine.RectTransform
---@field TxtHp UnityEngine.UI.Text
---@field TxtGold UnityEngine.UI.Text
---@field TxtRoundNum UnityEngine.UI.Text
---@field ListStage UnityEngine.UI.ScrollRect
---@field GridStage UnityEngine.RectTransform
---@field BtnSpeed UnityEngine.UI.Button 战斗倍速切换按钮（仅 Fighting 态显，toggle 1↔2）#68
---@field BtnAuto UnityEngine.UI.Button 自动战斗切换按钮（仅 Fighting 态显，toggle ByHand 牌自动/手动；VSNotify 期间 disable 同 BtnSpeed）#Auto
---@field RoleModelUiShow XUiPanelPunishaarRoleModelUi 战前战中敌我模型处 UI 显示（技能图标+副卡图标，坐标换算）#70
---@field FlashTextRoot UnityEngine.RectTransform 飘字挂载根（本节点 UiObject 引用，XUiNode 自动绑定；其下 DamageNumberPlayer 建池）
---@field private _DamageNumberPlayer XUiPunishaarDamageNumberPlayer 受伤飘字播放器（New 在 FlashTextRoot 上）
local XUiPunishaarFightMainCommonFightMain = XClass(XUiNode, "XUiPunishaarFightMainCommonFightMain")

function XUiPunishaarFightMainCommonFightMain:InitComponents()
    -- XUiNode
    ---@type XUiPunishaarFightMainPanelAsset
    self.PanelAsset = XUiPunishaarFightMainPanelAsset.New(self.PanelAsset, self)

    -- 节点进度列表：GridStage 作模板隐藏，按总节点数克隆到 ListStage.content
    self.GridStage.gameObject:SetActiveEx(false)
    ---@type XPool
    self._StageGridPool = XPool.New(function()
        local go = XUiHelper.Instantiate(self.GridStage, self.ListStage.content)
        return XUiPunishaarFightMainGridStage.New(go, self)
    end, function(grid)
        grid:Close()
    end, false)
    self._StageGridList = {}

    -- 通用滑动列表聚焦组件（复用 PBR XUiPBRStageListScrollView，纯表现层无数据依赖）
    ---@type XUiPBRStageListScrollView
    self._ScrollViewMove = XUiPBRStageListScrollView.New(self.GameObject, self.Parent, self.ListStage)
    self._ScrollViewMove:Init()

    self.BtnBack.gameObject:SetActiveEx(true)

    self.BtnBack:AddEventListener(handler(self, self.OnBtnBackClick))

    -- 倍速按钮：默认隐藏，仅 SetShowOnFighting 显 #68
    if self.BtnSpeed then
        self.BtnSpeed.gameObject:SetActiveEx(false)
        self.BtnSpeed:AddEventListener(handler(self, self.OnBtnSpeedClick))
    end

    -- 自动战斗按钮：默认隐藏，仅 SetShowOnFighting 显 #Auto
    if self.BtnAuto then
        self.BtnAuto.gameObject:SetActiveEx(false)
        self.BtnAuto:AddEventListener(handler(self, self.OnBtnAutoClick))
    end

    -- 角色模型 UI 图标显示（坐标换算+节点复用，PreFight 进入 Refresh 一次）#70
    if self.RoleModelUiShow then
        ---@type XUiPanelPunishaarRoleModelUi
        self.RoleModelUiShow = XUiPanelPunishaarRoleModelUi.New(self.RoleModelUiShow, self)
        self.RoleModelUiShow:Open()
    end

    -- 受伤飘字播放器（New 在 FlashTextRoot 上，经本节点 UiObject 自动绑定；显隐归 SetShowOn* Open/Close，Open 触发 OnStart→建池）#飘字
    if self.FlashTextRoot then
        self.FlashTextRoot.gameObject:SetActiveEx(false)
        ---@type XUiPunishaarDamageNumberPlayer
        self._DamageNumberPlayer = XUiPunishaarDamageNumberPlayer.New(self.FlashTextRoot, self)
    end
end

function XUiPunishaarFightMainCommonFightMain:OnStart(...)
    self:InitComponents()
end

function XUiPunishaarFightMainCommonFightMain:OnEnable()

end

function XUiPunishaarFightMainCommonFightMain:OnDisable()

end

function XUiPunishaarFightMainCommonFightMain:OnDestroy()
    if self._StageGridPool then
        self:RecycleAllStageGrids()
    end
end

function XUiPunishaarFightMainCommonFightMain:OnBtnBackClick()
    XLuaUiManager.Open("UiPunishaarStagePause")
end

--- 倍速切换（toggle 1↔2）：FightControl.SpeedController 管档位+持久化，SetUpdaterSpeed 驱动 updater #68
function XUiPunishaarFightMainCommonFightMain:OnBtnSpeedClick()
    if self._IsVsNotifyActive then
        return  -- VSNotify 期间过滤（Disable 已拦，双保险，#50/#68）
    end
    local gameControl = self._Control and self._Control.GameControl
    local fightControl = gameControl and gameControl.FightControl
    local speedController = fightControl and fightControl.SpeedController
    if not speedController then
        return
    end
    speedController:ToggleSpeed()
    fightControl:SetUpdaterSpeed(speedController:GetSpeed() == 2)
    self:_RefreshSpeedBtnState()
end

--- 设置战斗按钮可交互性（VSNotify 期间 Disable + 标志过滤；VSNotify 结束 Enable）。
--- 同时管辖 BtnSpeed 与 BtnAuto：两者同为战斗态按钮，VSNotify 生命周期一致 #68 #Auto
---@param interactable boolean
function XUiPunishaarFightMainCommonFightMain:SetSpeedBtnInteractable(interactable)
    self._IsVsNotifyActive = not interactable
    if self.BtnSpeed then
        if interactable then
            self.BtnSpeed:SetButtonState(CS.UiButtonState.Normal)
        else
            self.BtnSpeed:SetButtonState(CS.UiButtonState.Disable)
        end
    end
    -- BtnAuto 同 VSNotify 生命周期：disable 直 Disable；enable 恢复 Normal 态 + AutoPlay 动画（开/关仅由动画区分）#AutoPlay
    if self.BtnAuto then
        if interactable then
            self.BtnAuto:SetButtonState(CS.UiButtonState.Normal)
            self:_RefreshAutoBtnState()
        else
            self.BtnAuto:SetButtonState(CS.UiButtonState.Disable)
        end
    end
end

--- 刷新倍速按钮数字（读 FightControl.SpeedController:GetSpeed）。
--- BtnSpeed 约定 SetNameByGroup 索引 0 = 倍速数字（纯数字，1/2）；按钮无选中态 #68
function XUiPunishaarFightMainCommonFightMain:_RefreshSpeedBtnState()
    if not self.BtnSpeed then
        return
    end
    local gameControl = self._Control and self._Control.GameControl
    local fightControl = gameControl and gameControl.FightControl
    local speedController = fightControl and fightControl.SpeedController
    if not speedController then
        return
    end
    local speed = speedController:GetSpeed()
    self.BtnSpeed:SetNameByGroup(0, tostring(speed))
end

--- 自动战斗切换（toggle ByHand 牌自动/手动）：STEControl:SetAutoMode 即时打/摘 Global Auto tag + 写持久化 #Auto
--- 吃球校验不跳过（Pipeline ExecuteOneCardEffects 仍 CheckBallEnough，球不足 skip）。
function XUiPunishaarFightMainCommonFightMain:OnBtnAutoClick()
    if self._IsVsNotifyActive then
        return  -- VSNotify 期间过滤（Disable 已拦，双保险，同 BtnSpeed）
    end
    local steControl = self:_GetSTEControl()
    if not steControl then
        return
    end
    steControl:SetAutoMode(not steControl:GetAutoMode())
    self:_RefreshAutoBtnState()
end

--- 刷新自动战斗 AutoPlay 动画（读 STEControl:GetAutoMode 缓存态）。
--- 开启/关闭仅由 AutoPlay 动画区分（播=开启/停=关闭），按钮无 Select 态 #AutoPlay
function XUiPunishaarFightMainCommonFightMain:_RefreshAutoBtnState()
    if not self.BtnAuto then
        return
    end
    local steControl = self:_GetSTEControl()
    local autoOn = steControl and steControl:GetAutoMode() or false
    -- AutoPlay 动画：开启自动 + 按钮显示时播（循环 Loop），否则停
    local btnShow = self.BtnAuto.gameObject.activeInHierarchy
    if autoOn and btnShow then
        self:PlayAnimation("AutoPlay", nil, nil, CS.UnityEngine.Playables.DirectorWrapMode.Loop)
    else
        self:StopAnimation("AutoPlay")
    end
end

--- 取当前局 STEControl（经 _Control.GameControl.FightControl 链路，对齐 BtnSpeed 取 SpeedController 范式）#Auto
---@return XPunishaarSTEControl|nil
function XUiPunishaarFightMainCommonFightMain:_GetSTEControl()
    local gameControl = self._Control and self._Control.GameControl
    local fightControl = gameControl and gameControl.FightControl
    return fightControl and fightControl.STEControl
end

--- 回收全部节点 grid（逆序，复用 PBR RoundPanel 范式）。
function XUiPunishaarFightMainCommonFightMain:RecycleAllStageGrids()
    if XTool.IsTableEmpty(self._StageGridList) then return end
    for i = #self._StageGridList, 1, -1 do
        local grid = self._StageGridList[i]
        self._StageGridList[i] = nil
        if grid then
            self._StageGridPool:ReturnItemToPool(grid)
        end
    end
end

--- 刷新节点进度：文本"当前/总数" + 按总节点数刷出 grid 列表（三态见 GridStage.Refresh）。
function XUiPunishaarFightMainCommonFightMain:RefreshStageProgress()
    local stageId = self._Control:GetCurrentStageId()
    if not stageId then return end

    local total = self._Control:GetStageTotalNodeCount(stageId) or 0
    local curIndex = self._Control:GetCurrentNodeIndex() or 0

    if self.TxtRoundNum then
        self.TxtRoundNum.text = string.format("%d/%d", curIndex, total)
    end

    self:RecycleAllStageGrids()

    for i = 1, total do
        local grid = self._StageGridPool:GetItemFromPool()
        grid:Open()
        grid:Refresh(stageId, i, curIndex, total)
        table.insert(self._StageGridList, grid)
    end

    -- 列表布局重建（对齐 PBR RefreshWavesShow）
    if self.ListStage and self.ListStage.content then
        CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.ListStage.content)
    end
    -- 聚焦当前节点（居中），对齐 PBR RoundPanel.FocusCurWaveUI
    self:FocusCurNodeUI(curIndex, false)
end

--region 节点列表滑动聚焦

--- 聚焦指定节点到视口中心（复用通用组件 XUiPBRStageListScrollView.PlayScrollViewMove）。
---@param index number 节点序号（1-based）
---@param onlyViewFull boolean true=只要完全显示即可；false=居中
---@param cb function|nil 移动完成回调
function XUiPunishaarFightMainCommonFightMain:FocusCurNodeUI(index, onlyViewFull, cb)
    local grid = self._StageGridList[index]
    if not grid or not self._ScrollViewMove then return end

    local halfView = self._ScrollViewMove.HalfViewPortWidth
    local content = self.ListStage.content
    local gridLocalX = grid.Transform.localPosition.x
    local tarPosX

    if onlyViewFull then
        -- 让目标 grid 完全显示在视口内（左右边界 Clamp）
        local halfGrid = grid.Transform.sizeDelta.x / 2
        -- TODO: 边界留白 offset 若需可后续接 ClientConfig，暂用 0
        local leftPos = -halfView - gridLocalX + halfGrid
        local rightPos = halfView - gridLocalX - halfGrid
        tarPosX = XMath.Clamp(content.localPosition.x, leftPos, rightPos)
    else
        -- 聚焦到视口中心（content 锚点在左侧，0=起始）
        tarPosX = -gridLocalX
    end

    -- 越界夹取：不可大于 0（起始），不可小于 -(content 宽 - 半视口)
    local maxLeft = -content.sizeDelta.x + halfView
    tarPosX = XMath.Clamp(tarPosX, maxLeft, -halfView)

    self._ScrollViewMove:PlayScrollViewMove(tarPosX, nil, true, cb)
end

--endregion

function XUiPunishaarFightMainCommonFightMain:SetShowOnFighting()
    self.PanelAsset:Close()
    -- PanelTop 是关卡进度容器（TxtRoundNum+ListStage+装饰 UI 的父节点），整容器隐以一并遮蔽全部进度内容。
    -- 隐前先 Close 内部实例化 XUiNode（pool grids）：避免 Open 态 XUiNode 挂 activeSelf=false 容器下，
    -- 否则 root 恢复时 EnableChildNodes 级联重 Enable 会触发 _CheckUIActive 报错（RecycleAllStageGrids 经池 onRelease 调 grid:Close）。
    self:RecycleAllStageGrids()
    if self.PanelTop then
        self.PanelTop.gameObject:SetActiveEx(false)
    end
    -- 倍速按钮仅战斗中显 + 同步数字 #50/#68
    if self.BtnSpeed then
        self.BtnSpeed.gameObject:SetActiveEx(true)
        self:_RefreshSpeedBtnState()
    end
    -- 自动战斗按钮仅当前关卡启用自动战斗（PunishaarStageGroup.EnableCardAutoMode）时显 + 同步选中态/AutoPlay 动画 #Auto
    if self.BtnAuto then
        local steControl = self:_GetSTEControl()
        local autoByStage = steControl and steControl:IsAutoModeEnabledByStage()
        self.BtnAuto.gameObject:SetActiveEx(autoByStage == true)
        self:_RefreshAutoBtnState()
    end
    -- VSNotify 期间两按钮先 Disable：须在两按钮 refresh 之后调用，Disable 后生效不被 refresh 覆盖
    -- （持久化偏好+驱动归 FightControl:InitNewGame）#50/#68/#Auto
    self:SetSpeedBtnInteractable(false)
    -- 飘字播放器：战斗 Open（触发 OnStart→建池）/ 非战斗 Close #飘字
    if self._DamageNumberPlayer then
        self._DamageNumberPlayer:Open()
    end
    -- 我方副卡槽刷新（Fighting 卡在板上，跟模型走应显；若 RoleModelUiShow 挂 PanelTop 下则随 PanelTop 隐，需 prefab 移出）#副卡槽联动
    if self.RoleModelUiShow then
        self.RoleModelUiShow:Refresh()
    end
end

function XUiPunishaarFightMainCommonFightMain:SetShowOnShop()
    self.PanelAsset:Open()
    if self.PanelTop then
        self.PanelTop.gameObject:SetActiveEx(true)
    end
    -- 显后 Open 内部实例化 XUiNode（grids）+ 刷文本（RefreshStageProgress 经池取回 grid:Open + 设 TxtRoundNum/ListStage）
    self:RefreshStageProgress()
    if self.BtnSpeed then
        self.BtnSpeed.gameObject:SetActiveEx(false)
    end
    if self.BtnAuto then
        self.BtnAuto.gameObject:SetActiveEx(false)
        self:_RefreshAutoBtnState()  -- 停 AutoPlay 动画（按钮隐）#AutoPlay
    end
    -- 我方副卡槽初始刷新（暂离重进/直进 Shop 无 BuySuccess 时补刷；后续卡集合变更由订阅刷）#副卡槽联动
    if self.RoleModelUiShow then
        self.RoleModelUiShow:Refresh()
    end
    if self._DamageNumberPlayer then
        self._DamageNumberPlayer:Close()  -- 飘字播放器非战斗 Close #飘字
    end
end

function XUiPunishaarFightMainCommonFightMain:SetShowOnPreFight()
    self.PanelAsset:Open()
    if self.PanelTop then
        self.PanelTop.gameObject:SetActiveEx(true)
    end
    self:RefreshStageProgress()
    if self.BtnSpeed then
        self.BtnSpeed.gameObject:SetActiveEx(false)
    end
    if self.BtnAuto then
        self.BtnAuto.gameObject:SetActiveEx(false)
        self:_RefreshAutoBtnState()  -- 停 AutoPlay 动画（按钮隐）#AutoPlay
    end
    -- 我方副卡槽初始刷新（坐标换算，PreFight 进入一次；后续卡集合变更由 BuySuccess 订阅刷）#70 #副卡槽联动
    if self.RoleModelUiShow then
        self.RoleModelUiShow:Refresh()
    end
    if self._DamageNumberPlayer then
        self._DamageNumberPlayer:Close()  -- 飘字播放器非战斗 Close #飘字
    end
end

--- Base 态（基底态：背包编排）顶部部件显隐。
--- 各子部件有明确状态归属，Base 默认显 PanelAsset + PanelTop（与 Shop/PreFight 一致：金币/HP + 节点进度作常驻 HUD）；
--- 若某部件后续判定不属于 Base，在此调整其显隐即可。#66
function XUiPunishaarFightMainCommonFightMain:SetShowOnBase()
    self.PanelAsset:Open()
    if self.PanelTop then
        self.PanelTop.gameObject:SetActiveEx(true)
    end
    self:RefreshStageProgress()
    if self.BtnSpeed then
        self.BtnSpeed.gameObject:SetActiveEx(false)
    end
    if self.BtnAuto then
        self.BtnAuto.gameObject:SetActiveEx(false)
        self:_RefreshAutoBtnState()  -- 停 AutoPlay 动画（按钮隐）#AutoPlay
    end
    -- 我方副卡槽初始刷新（同 Shop，覆盖暂离重进/直进 Base 无 BuySuccess 场景）#副卡槽联动
    if self.RoleModelUiShow then
        self.RoleModelUiShow:Refresh()
    end
    if self._DamageNumberPlayer then
        self._DamageNumberPlayer:Close()  -- 飘字播放器非战斗 Close #飘字
    end
end

--region 受伤飘字 FightControl 订阅转发（PanelFighting:OnEnable/OnDisable 平行 ModelShow 调）#飘字

--- PanelFighting:OnEnable 调，转发 DamageNumberPlayer 订阅 SpawnDamageNumber。
function XUiPunishaarFightMainCommonFightMain:BindFightControl()
    if not self._DamageNumberPlayer then
        return  -- FlashTextRoot 未绑定（prefab UiObject 未引用），飘字不可用，静默跳过
    end
    local fightControl = self._Control and self._Control.GameControl and self._Control.GameControl.FightControl
    if not fightControl then
        return
    end
    self._DamageNumberPlayer:BindFightControl(fightControl)
end

--- PanelFighting:OnDisable 调（ExitFight 前），转发注销 + 强制回收在播飘字。
function XUiPunishaarFightMainCommonFightMain:UnbindFightControl()
    if self._DamageNumberPlayer then
        self._DamageNumberPlayer:UnbindFightControl()
    end
end

--endregion

return XUiPunishaarFightMainCommonFightMain
