--[[
-- XUiPBRShopNewPanelItem.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

local XUiPBRShopNewGridItem = require("XUi/XUiPBRGame/XUiPBRShopNew/GoodsPanel/XUiPBRShopNewGridItem")

---@class XUiPBRShopNewPanelItem : XUiNode
local XUiPBRShopNewPanelItem = XClass(XUiNode, "XUiPBRShopNewPanelItem")

--- 固定商品格子数：prefab 已预置 PanelItem1..PanelItemN，没有商品表现为空
local ConstSlotCount = 3

function XUiPBRShopNewPanelItem:OnStart(...)
    self:InitComponents()
end

function XUiPBRShopNewPanelItem:OnEnable()
end

function XUiPBRShopNewPanelItem:OnDisable()
end

function XUiPBRShopNewPanelItem:OnDestroy()
end

function XUiPBRShopNewPanelItem:InitComponents()
    ---@type XUiPBRShopNewGridItem[]
    self.GoodsPanelList = {}

    for i = 1, ConstSlotCount do
        local go = self["PanelItem" .. i]   -- prefab 预置节点：PanelItem1、PanelItem2…

        if go then
            self.GoodsPanelList[i] = XUiPBRShopNewGridItem.New(go, self, self.Parent)
        end
    end
end

---@param itemIds number[]
function XUiPBRShopNewPanelItem:RefreshGoodsShow(itemIds)
    for i = 1, #self.GoodsPanelList do
        local panel = self.GoodsPanelList[i]

        if panel then
            panel:Refresh(itemIds[i], true)
        end
    end
end


return XUiPBRShopNewPanelItem
