--[[
-- XUiPartnerOneKeyCultureDetailItemCellView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-25 17:15:00
--]]

---@class XUiPartnerOneKeyCultureDetailItemCellView : XUiNode
---@field _Control XPartnerControl
---@field Parent XUiEquipOneClickCulturePartnerMainEnhanceDetail
---@field TxtTitle UnityEngine.UI.Text
---@field BtnEnter XUiComponent.XUiButton
---@field GoCostGrid UnityEngine.RectTransform
---@field GoFullStyle UnityEngine.RectTransform
--- 以下是自定义部分
---@field _CultureType XPartnerEnum.CultureType
local XUiPartnerOneKeyCultureDetailItemCellView = XClass(XUiNode, "XUiPartnerOneKeyCultureDetailItemCellView")





function XUiPartnerOneKeyCultureDetailItemCellView:InitComponents()
    self.BtnEnter.CallBack = function()
        self:OnBtnEnterClick()
    end
    self._CostGridList = {}
    self._CostList = {}
    -- 第一个格子直接用 GoCostGrid 本身
    local firstGrid = self:_NewCostGrid(self.GoCostGrid)
    table.insert(self._CostGridList, firstGrid)
    self.GoCostGrid.gameObject:SetActiveEx(false)
end

function XUiPartnerOneKeyCultureDetailItemCellView:OnStart(...)
    self:InitComponents()
end

function XUiPartnerOneKeyCultureDetailItemCellView:OnEnable()
end

function XUiPartnerOneKeyCultureDetailItemCellView:OnDisable()
end

function XUiPartnerOneKeyCultureDetailItemCellView:OnDestroy()
end

---region ui event

function XUiPartnerOneKeyCultureDetailItemCellView:OnBtnEnterClick()
    local XPartnerEnum = XMVCA.XPartner.Enum
    local cultureType = self._CultureType

    local partner = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partner then
        return
    end

    local tabIndex
    if cultureType == XPartnerEnum.CultureType.LevelUp then
        tabIndex = XPartnerConfigs.PriorityTabType.Level
    elseif cultureType == XPartnerEnum.CultureType.StarUp then
        tabIndex = XPartnerConfigs.PriorityTabType.Quality
    elseif cultureType == XPartnerEnum.CultureType.SkillLevelUp then
        tabIndex = XPartnerConfigs.PriorityTabType.Skill
    end

    XDataCenter.PartnerManager.OpenUiPartnerMain(false, XPartnerConfigs.MainUiState.Property, partner, true, true, tabIndex)
end

---endregion

---region event

-- TODO: 事件监听

---endregion

function XUiPartnerOneKeyCultureDetailItemCellView:Refresh(cultureType)
    self._CultureType = cultureType

    local XPartnerEnum = XMVCA.XPartner.Enum

    if cultureType == XPartnerEnum.CultureType.LevelUp then
        self:_RefreshLevelUp()
    elseif cultureType == XPartnerEnum.CultureType.StarUp then
        self:_RefreshStarUp()
    elseif cultureType == XPartnerEnum.CultureType.SkillLevelUp then
        self:_RefreshSkillLevelUp()
    end

    self:_RefreshFullStyle()
end

function XUiPartnerOneKeyCultureDetailItemCellView:_RefreshFullStyle()
    local isDone = self:IsCultureDone(self._CultureType)
    self.GoFullStyle.gameObject:SetActiveEx(isDone)
    self.BtnEnter.gameObject:SetActiveEx(not isDone)
end

--- 该养成项是否已达成（技能项额外要求穿戴选满，未选满不算达成）
---@param cultureType XPartnerEnum.CultureType
---@return boolean
function XUiPartnerOneKeyCultureDetailItemCellView:IsCultureDone(cultureType)
    local isDone = not self._Control:GetOneKeyCultureMainControl():IsNeedCulture(cultureType)
    if isDone and cultureType == XMVCA.XPartner.Enum.CultureType.SkillLevelUp then
        isDone = self:_IsSkillWearFull()
    end
    return isDone
end

--- 技能穿戴是否选满（主动技 1 个 + 被动技槽位）
---@return boolean
function XUiPartnerOneKeyCultureDetailItemCellView:_IsSkillWearFull()
    local partner = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partner then
        return true
    end
    return #partner:GetCarryPassiveSkillGroupList() >= partner:GetQualitySkillColumnCount()
end

function XUiPartnerOneKeyCultureDetailItemCellView:_RefreshLevelUp()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local costControl = mainControl:GetBaseCostControl()
    local partner = mainControl:GetCurPartnerEntity()
    local maxLevel = partner:GetBreakthroughLevelLimit(partner:GetBreakthroughLimit())
    self.TxtTitle.text = XUiHelper.GetText("PartnerOneKeyDetailLevelTitle", maxLevel)
    local costList = costControl:GetLevelUpTotalCostData()
    self:_RefreshCostList(costList)
end

function XUiPartnerOneKeyCultureDetailItemCellView:_RefreshStarUp()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local costControl = mainControl:GetBaseCostControl()
    local havePartnerCount = costControl:GetStarUpPartnerHaveCount()
    local recommendQuality = mainControl:GetRecommendQuality()
    local recommendQualityText = XPartnerConfigs.GetQualityString(recommendQuality)
    self.TxtTitle.text = XUiHelper.GetText("PartnerOneKeyDetailStarTitle", recommendQualityText)

    local costList = self._CostList
    table.clear(costList)

    local XPartnerEnum = XMVCA.XPartner.Enum
    local partner = mainControl:GetCurPartnerEntity()

    if partner and mainControl:IsNeedCulture(XPartnerEnum.CultureType.StarUp) then
        table.insert(costList, {
            IsPartner = true,
            Icon = partner:GetIcon(),
            Quality = XMVCA.XPartner.Util.GetGoodsQualityByPartnerQuality(partner:GetInitQuality()),
            NeedCount = costControl:GetStarUpPartnerNeedCount(),
            HaveCount = havePartnerCount,
        })
    end

    self:_RefreshCostList(costList)
end


function XUiPartnerOneKeyCultureDetailItemCellView:_RefreshSkillLevelUp()
    local costControl = self._Control:GetOneKeyCultureMainControl():GetBaseCostControl()
    self.TxtTitle.text = XUiHelper.GetText("PartnerOneKeyDetailSkillTitle")
    local costList = costControl:GetSkillCostData()
    self:_RefreshCostList(costList)
end

function XUiPartnerOneKeyCultureDetailItemCellView:_RefreshCostList(costList)
    -- MainView 只显示关键材料，过滤掉螺母
    local CoinId = XDataCenter.ItemManager.ItemId.Coin
    local displayList = {}
    for _, item in ipairs(costList) do
        if item.IsPartner or item.Id ~= CoinId then
            table.insert(displayList, item)
        end
    end

    self:_EnsureCostGridCount(#displayList)

    for index, item in ipairs(displayList) do
        local grid = self._CostGridList[index]
        if item.IsPartner then
            grid:RefreshCustom(item.Icon, item.Quality, item.NeedCount, item.HaveCount)
            grid:SetCustomClick(self._OnPartnerCostClick, self)
        else
            grid:Refresh(item.Id, item.Count)
        end
        grid.GameObject:SetActiveEx(true)
    end

    for i = #displayList + 1, #self._CostGridList do
        self._CostGridList[i].GameObject:SetActiveEx(false)
    end
end

function XUiPartnerOneKeyCultureDetailItemCellView:_EnsureCostGridCount(needCount)
    while #self._CostGridList < needCount do
        local ui = CS.UnityEngine.Object.Instantiate(self.GoCostGrid, self.GoCostGrid.transform.parent)
        ui.gameObject:SetActiveEx(false)
        local grid = self:_NewCostGrid(ui)
        table.insert(self._CostGridList, grid)
    end
end

function XUiPartnerOneKeyCultureDetailItemCellView:_NewCostGrid(ui)
    local XUiGridCostItem = require("XUi/XUiEquipBreakThrough/XUiGridCostItem")
    return XUiGridCostItem.New(self, ui)
end


function XUiPartnerOneKeyCultureDetailItemCellView:_OnPartnerCostClick()
    local partner = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partner then
        return
    end

    local itemId = partner:GetChipItemId()
    XLuaUiManager.Open("UiTip", XDataCenter.ItemManager.GetItem(itemId))
end


return XUiPartnerOneKeyCultureDetailItemCellView
