--[[
-- XUiPunishaarChooseStage.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-01 15:11:12
--]]

---@class XUiPunishaarChooseStage : XLuaUi
---@field BtnHelp XUiComponent.XUiButton
---@field TopControl UnityEngine.RectTransform
---@field GridStage01 UnityEngine.RectTransform
---@field GridStage02 UnityEngine.RectTransform
---@field GridStage03 UnityEngine.RectTransform
---@field GridStage04 UnityEngine.RectTransform
---@field GridStage05 UnityEngine.RectTransform
---@field GridStage06 UnityEngine.RectTransform
---@field GridStage07 UnityEngine.RectTransform
---@field GridStage08 UnityEngine.RectTransform
---@field GridStage09 UnityEngine.RectTransform
---@field UiPunishaarGridStage UnityEngine.RectTransform
local XUiPunishaarChooseStage = XLuaUiManager.Register(XLuaUi, "UiPunishaarChooseStage")
function XUiPunishaarChooseStage:OnAwake()
    self:InitComponents()

end

function XUiPunishaarChooseStage:InitComponents()
    self.UiPunishaarGridStage.gameObject:SetActiveEx(false)
    XUiHelper.NewPanelTopControl(self, self.TopControl)
    self:BindHelpBtn(self.BtnHelp, "XPunishaarHelp")
end

function XUiPunishaarChooseStage:OnStart(...)
    self:InitStageGrids()
end

function XUiPunishaarChooseStage:OnEnable()
    -- 返回页面时完整刷新进度、存档和红点
    self:Refresh()

    -- 每秒只检查关卡状态是否变化
    self._Control:AddTimeEventListener(
        self.UpdateStageStatus,
        self
    )
end

function XUiPunishaarChooseStage:OnDisable()
    self._Control:RemoveTimeEventListener(
        self.UpdateStageStatus,
        self
    )
end

function XUiPunishaarChooseStage:OnDestroy()
end


function XUiPunishaarChooseStage:Refresh()
    if not self._GridList then
        return
    end

    for _, grid in ipairs(self._GridList) do
        grid:Refresh()
    end
end

function XUiPunishaarChooseStage:InitStageGrids()
    local groupId = XMVCA.XPunishaar:GetCurrentStageGroupId()
    if not groupId then
        return
    end

    self._GridList = {}

    for i = 1, 9 do
        local stageId = XMVCA.XPunishaar:GetStageIdByGroupAndIndex(groupId, i)
        local stageCfg = XMVCA.XPunishaar:GetTablePunishaarStageGroupById(stageId)

        if not stageCfg then
            break
        end
        local gridRoot = self["GridStage0" .. i]
        local gridObject = XUiHelper.Instantiate(self.UiPunishaarGridStage, gridRoot)

        local grid = require("XUi/XUiPunishaar/Grid/XUiGridPunishaarStage").New(gridObject, self, i)
        grid:Open()
        grid:InitStage(stageId)
        self._GridList[i] = grid
    end
end

function XUiPunishaarChooseStage:UpdateStageStatus()
    if not self._GridList then
        return
    end

    for _, grid in ipairs(self._GridList) do
        grid:RefreshIfStatusChanged()
    end
end
return XUiPunishaarChooseStage
