--[[
-- XUiEquipOneClickCulturePartnerMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-24 15:59:14
--]]


---@class XUiEquipOneClickCulturePartnerMain : XLuaUi
---@field _Control XPartnerControl
---@field PanelAsset UnityEngine.RectTransform
---@field BtnBack XUiComponent.XUiButton
---@field BtnMainUi XUiComponent.XUiButton
---@field BtnHelp XUiComponent.XUiButton
---@field BtnOneKeyCultureSure XUiComponent.XUiButton
---@field BtnAutoExchange XUiComponent.XUiButton
---@field AnimFold PlayableDirector
---@field AnimUnFold PlayableDirector
---@field GoSkillRoot UnityEngine.RectTransform
---@field Partner3DView UiObject
---@field PartnerBaseView UiObject 
---@field PartnerEnhanceDetailView UiObject
---@field GoOneKeyCultureFinish UnityEngine.RectTransform
---@field GoEffect UnityEngine.RectTransform
---@field _PartnerModelView XUiEquipOneClickCulturePartnerMainPartnerModel
---@field _PartnerBaseView XUiEquipOneClickCulturePartnerMainPanelPartnerPlan
---@field _EnhanceDetailView XUiEquipOneClickCulturePartnerMainEnhanceDetail
local XUiEquipOneClickCulturePartnerMain = XLuaUiManager.Register(XLuaUi, "UiEquipOneClickCulturePartnerMain")
function XUiEquipOneClickCulturePartnerMain:OnAwake()
    self._Control:GetOneKeyCultureMainControl():OnEnterCultureMainUI()
    self:InitComponents()
end

function XUiEquipOneClickCulturePartnerMain:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()
    self:BindHelpBtn(self.BtnHelp, "UiEquipOneClickCulturePartnerMainHelpKey")

    -- Button
    self.BtnOneKeyCultureSure.CallBack = function()
        self:OnBtnOneKeyCultureSureClick()
    end
    self.BtnAutoExchange.CallBack = function()
        self:OnBtnAutoExchangeClick()
    end

    local assetItemIds = self._Control:GetOneKeyCultureMainControl():GetAssetPanelItemIds()
    self._PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, table.unpack(assetItemIds))

    -- XUiNode
    local XUiEquipOneClickCulturePartnerMainPanelPartnerPlan = require("XUi/XUiPartnerOneKeyCulture/OneKeyCultureMain/XUiEquipOneClickCulturePartnerMain/XUiEquipOneClickCulturePartnerMainPanelPartnerPlan")
    local XUiEquipOneClickCulturePartnerMainPartnerModel = require("XUi/XUiPartnerOneKeyCulture/OneKeyCultureMain/XUiEquipOneClickCulturePartnerMain/XUiEquipOneClickCulturePartnerMainPartnerModel")
    local XUiEquipOneClickCulturePartnerMainEnhanceDetail = require("XUi/XUiPartnerOneKeyCulture/OneKeyCultureMain/XUiEquipOneClickCulturePartnerMain/XUiEquipOneClickCulturePartnerMainEnhanceDetail")

    ---@type XUiEquipOneClickCulturePartnerMainPartnerModel
    self._PartnerModelView = XUiEquipOneClickCulturePartnerMainPartnerModel.New(self.Partner3DView, self)

    ---@type XUiEquipOneClickCulturePartnerMainPanelPartnerPlan
    self._PartnerBaseView = XUiEquipOneClickCulturePartnerMainPanelPartnerPlan.New(self.PartnerBaseView, self)


    ---@type XUiEquipOneClickCulturePartnerMainEnhanceDetail
    self._EnhanceDetailView = XUiEquipOneClickCulturePartnerMainEnhanceDetail.New(self.PartnerEnhanceDetailView, self)

end

function XUiEquipOneClickCulturePartnerMain:OnEnable()
    self:_SetEvent(true)
    self._Control:GetOneKeyCultureMainControl():GetBaseCostControl():CalcAllCostData()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMain:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipOneClickCulturePartnerMain:OnDestroy()
    self._Control:GetOneKeyCultureMainControl():OnExitCultureMainUI()
end

---region ui event

function XUiEquipOneClickCulturePartnerMain:OnBtnOneKeyCultureSureClick()
    self._Control:GetOneKeyCultureMainControl():SyncAutoSettingsFromEquip()
    XLuaUiManager.Open("UiEquipPartnerOneClickPopup")
end

function XUiEquipOneClickCulturePartnerMain:OnBtnAutoExchangeClick()
    local isAuto = self._Control:GetOneKeyCultureMainControl():IsAutoExchange()
    self._Control:GetOneKeyCultureMainControl():SetAutoExchangeWithNotify(not isAuto)
end

---endregion

---region event

function XUiEquipOneClickCulturePartnerMain:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_VIEW_ONE_KEY_CULTURE_EFFECT, self._OnOneKeyCultureEffect, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_VIEW_ONE_KEY_CULTURE_EFFECT, self._OnOneKeyCultureEffect, self)
    end
end

function XUiEquipOneClickCulturePartnerMain:_OnPartnerSelectChange(partnerId)
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMain:_OnPartnerDataUpdate()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMain:_OnOneKeyCultureFinish()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMain:_OnOneKeyCultureEffect()
    self.GoEffect.gameObject:SetActiveEx(false)
    self.GoEffect.gameObject:SetActiveEx(true)
end

function XUiEquipOneClickCulturePartnerMain:_OnAutoExchangeChange()
    self:_RefreshAutoExchange()
end

---endregion

function XUiEquipOneClickCulturePartnerMain:_Refresh()
    self._PartnerModelView:Open()
    self._PartnerBaseView:Open()
    self._EnhanceDetailView:Open()

    self.BtnBack:SetButtonState(CS.UiButtonState.Normal)
    self.BtnMainUi:SetButtonState(CS.UiButtonState.Normal)
    self.BtnHelp:SetButtonState(CS.UiButtonState.Normal)

    self:_RefreshOneKeyCultureBtn()
    self:_RefreshAutoExchange()
end

function XUiEquipOneClickCulturePartnerMain:_RefreshAutoExchange()
    local isAuto = self._Control:GetOneKeyCultureMainControl():IsAutoExchange()
    self.BtnAutoExchange:SetButtonState(isAuto and CS.UiButtonState.Select or CS.UiButtonState.Normal)
end

function XUiEquipOneClickCulturePartnerMain:_RefreshOneKeyCultureBtn()
    local isAllDone = self._Control:GetOneKeyCultureMainControl():IsAllCultureDone()
    self.GoOneKeyCultureFinish.gameObject:SetActiveEx(isAllDone)
    self.BtnOneKeyCultureSure:SetButtonState(isAllDone and CS.UiButtonState.Disable or CS.UiButtonState.Normal)
end

return XUiEquipOneClickCulturePartnerMain
