--[[
-- XUiRoleCostPreviewPopupGridExchange.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-10 21:29:19
--]]

local XUiGridCommon = require("XUi/XUiObtain/XUiGridCommon")

---@class XUiRoleCostPreviewPopupGridExchange : XUiNode
---@field _Control XEquipControl
---@field RawImgToken UnityEngine.UI.RawImage
---@field TxtUseCount UnityEngine.UI.Text
---@field TxtTips UnityEngine.UI.Text
---@field Grid256 UnityEngine.RectTransform
local XUiRoleCostPreviewPopupGridExchange = XClass(XUiNode, "XUiRoleCostPreviewPopupGridExchange")

-- 初始化兑换产出道具格子。
function XUiRoleCostPreviewPopupGridExchange:InitComponents()
    self.RewardGrids = {}
    self._RewardData = {}
    self.Grid256.gameObject:SetActiveEx(false)
    self.BtnCost:AddEventListener(handler(self, self.OnBtnCostClick))
end

function XUiRoleCostPreviewPopupGridExchange:OnBtnCostClick()
    XLuaUiManager.Open("UiTip", XDataCenter.ItemManager.GetItem(self.Data.ConsumeId))
end

-- 接收兑换信息并刷新格子。
function XUiRoleCostPreviewPopupGridExchange:OnStart()
    self:InitComponents()
end

-- 刷新一次自动兑换（同代币的多项已合并）
---@param data table { ConsumeId, ConsumeCount, Rewards = {{ItemId, RewardCount}, ...} }
function XUiRoleCostPreviewPopupGridExchange:Refresh(data)
    self.Data = data

    local consumeId = data.ConsumeId
    local shopName = XItemConfigs.GetAutoExchangeTokenShopName(consumeId)
    self.TxtTips.text = XUiHelper.GetText("RoleExchangeShopTips", shopName)
    self.RawImgToken.gameObject:SetActiveEx(XTool.IsNumberValid(consumeId))
    if XTool.IsNumberValid(consumeId) then
        self.RawImgToken:SetRawImage(XDataCenter.ItemManager.GetItemIcon(consumeId))
        self.TxtUseCount.text = CS.XTextManager.GetText("ShopGridCommonCount", data.ConsumeCount or 0)
    end

    self:_RefreshRewardGrids(data.Rewards or table.empty)
end

function XUiRoleCostPreviewPopupGridExchange:_RefreshRewardGrids(rewards)
    XUiHelper.RefreshCustomizedList(self.Grid256.transform.parent, self.Grid256, #rewards, function(index, go)
        local grid = self.RewardGrids[index]
        if not grid then
            grid = XUiGridCommon.New(go)
            self.RewardGrids[index] = grid
        end
        local reward = rewards[index]
        local rewardData = self._RewardData[index]
        if not rewardData then
            rewardData = {}
            self._RewardData[index] = rewardData
        end
        rewardData.TemplateId = reward.ItemId
        rewardData.Count = reward.RewardCount
        grid:Refresh(rewardData)
    end)
end

function XUiRoleCostPreviewPopupGridExchange:Update(data, index)
    self:Refresh(data)
end

return XUiRoleCostPreviewPopupGridExchange
