--[[
-- XUiEquipPartnerEnhanceProgressPopup.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-08 12:06:34
--]]

---@class XUiEquipPartnerEnhanceProgressPopup : XLuaUi
---@field _Control XPartnerControl
---@field BtnClose XUiComponent.XUiButton
---@field TxtTitle UnityEngine.UI.Text
---@field BtnFinish XUiComponent.XUiButton
---@field BtnStop XUiComponent.XUiButton
---@field ProgressItem UiObject
---@field GoOK UnityEngine.RectTransform
---@field GoLoading UnityEngine.RectTransform
---@field private _LevelUpCell XUiEquipPartnerEnhanceProgressCell
---@field private _StarUpCell XUiEquipPartnerEnhanceProgressCell
---@field private _SkillLevelUpCell XUiEquipPartnerEnhanceProgressCell
---@field private _CommitFlowRoot XFlowTreeRoot
---@field private _HasCultureSuccess boolean
local XUiEquipPartnerEnhanceProgressPopup = XLuaUiManager.Register(XLuaUi, "UiEquipPartnerEnhanceProgressPopup")

local XUiEquipPartnerEnhanceProgressCell = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/XUiEquipPartnerEnhanceProgressCell")

function XUiEquipPartnerEnhanceProgressPopup:OnAwake()
    self:InitComponents()
end

function XUiEquipPartnerEnhanceProgressPopup:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnFinish:AddEventListener(function() self:OnBtnFinishClick() end)
    self.BtnStop:AddEventListener(function() self:OnBtnStopClick() end)

    -- 实例化3个进度项：原始=升级，克隆=升星/技能
    local originGO = self.ProgressItem.gameObject
    local originRoot = self.ProgressItem.transform.parent
    self._LevelUpCell = XUiEquipPartnerEnhanceProgressCell.New(self.ProgressItem, self)
    local starUpGo = XUiHelper.Instantiate(originGO, originRoot)
    self._StarUpCell = XUiEquipPartnerEnhanceProgressCell.New(starUpGo, self)
    local skillLevelUpGo = XUiHelper.Instantiate(originGO, originRoot)
    self._SkillLevelUpCell = XUiEquipPartnerEnhanceProgressCell.New(skillLevelUpGo, self)
end

function XUiEquipPartnerEnhanceProgressPopup:OnStart(...)
    self:SetHasCultureSuccess(false)
    self:_Refresh()
    self:_StartCommitFlow()
end

function XUiEquipPartnerEnhanceProgressPopup:OnEnable()
    self:_SetEvent(true)
end

function XUiEquipPartnerEnhanceProgressPopup:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipPartnerEnhanceProgressPopup:OnDestroy()
    self:_DestroyCommitFlow()
    if self:GetHasCultureSuccess() then
        self._Control:DispatchEvent(XMVCA.XPartner.EventIds.EVENT_VIEW_ONE_KEY_CULTURE_EFFECT)
    end
end

function XUiEquipPartnerEnhanceProgressPopup:SetHasCultureSuccess(value)
    self._HasCultureSuccess = value
end

function XUiEquipPartnerEnhanceProgressPopup:GetHasCultureSuccess()
    return self._HasCultureSuccess
end

---region ui event

function XUiEquipPartnerEnhanceProgressPopup:OnBtnCloseClick(eventData)
    self:Close()
end

function XUiEquipPartnerEnhanceProgressPopup:OnBtnFinishClick(eventData)
    self:Close()
end

function XUiEquipPartnerEnhanceProgressPopup:OnBtnStopClick(eventData)
    self:_DestroyCommitFlow()
    self:_NotifyOneKeyCultureFinish()
    self:Close()
end

---endregion

---region event

function XUiEquipPartnerEnhanceProgressPopup:_SetEvent(flag)
end


---endregion

function XUiEquipPartnerEnhanceProgressPopup:_Refresh()
    self:_SetInitView()

    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local commitControl = mainControl:GetCommitControl()
    local XPartnerEnum = XMVCA.XPartner.Enum
    local EnhanceProgressType = XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType

    local isLevelUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.LevelUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.LevelUp)
    local isStarUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.StarUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.StarUp)
    local isSkillLevelUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.SkillLevelUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.SkillLevelUp)

    self._LevelUpCell.GameObject:SetActiveEx(isLevelUp)
    self._StarUpCell.GameObject:SetActiveEx(isStarUp)
    self._SkillLevelUpCell.GameObject:SetActiveEx(isSkillLevelUp)

    if isLevelUp then
        self._LevelUpCell:RefreshByCultureType(XPartnerEnum.CultureType.LevelUp)
        self._LevelUpCell:RefreshByProgressStatus(EnhanceProgressType.Waiting)
    end
    if isStarUp then
        self._StarUpCell:RefreshByCultureType(XPartnerEnum.CultureType.StarUp)
        self._StarUpCell:RefreshByProgressStatus(EnhanceProgressType.Waiting)
    end
    if isSkillLevelUp then
        self._SkillLevelUpCell:RefreshByCultureType(XPartnerEnum.CultureType.SkillLevelUp)
        self._SkillLevelUpCell:RefreshByProgressStatus(EnhanceProgressType.Waiting)
    end
end

function XUiEquipPartnerEnhanceProgressPopup:_SetInitView()
    self.TxtTitle.text = XUiHelper.GetText("PartnerOneKeyProgressTitleProcessing")
    self.BtnStop.gameObject:SetActiveEx(true)
    self.BtnFinish.gameObject:SetActiveEx(false)
    self.GoLoading.gameObject:SetActiveEx(true)
    self.GoOK.gameObject:SetActiveEx(false)
end

---@param isSuccess boolean 行为树是否全部执行成功
function XUiEquipPartnerEnhanceProgressPopup:_SetFinishView(isSuccess)
    self.TxtTitle.text = isSuccess and XUiHelper.GetText("PartnerOneKeyProgressTitleFinish") or XUiHelper.GetText("PartnerOneKeyProgressTitleInterrupt")
    self.BtnStop.gameObject:SetActiveEx(false)
    self.BtnFinish.gameObject:SetActiveEx(true)
    self.GoLoading.gameObject:SetActiveEx(false)
    self.GoOK.gameObject:SetActiveEx(isSuccess)
end

function XUiEquipPartnerEnhanceProgressPopup:_StartCommitFlow()
    local XFlowTreeRequire = require("XFlowTree/XFlowTreeRequire")

    self._CommitFlowRoot = XFlowTreeRequire.XFlowTreeRoot.New()
    local seq = XFlowTreeRequire.XFlowTreeSequence.New()

    -- 前置：自动兑换（缺料时先走商店购买补足）
    local prepareNode = self:_BuildPrepareNode()
    if prepareNode then
        seq:AddChild(prepareNode)
    end

    -- 升级+突破
    local levelUpNode = self:_BuildLevelUpNode()
    if levelUpNode then 
        seq:AddChild(levelUpNode) 
    end

    -- 升星
    local starUpNode = self:_BuildStarUpNode()
    if starUpNode then 
        seq:AddChild(starUpNode) 
    end

    -- 技能升级
    local skillNode = self:_BuildSkillLevelUpNode()
    if skillNode then 
        seq:AddChild(skillNode) 
    end

    self._CommitFlowRoot:AddChild(seq)
    self._CommitFlowRoot:SetDoneCallback(self._Finish, self)
    self._CommitFlowRoot:StartFlowTree(self)
end



--- 前置节点：自动兑换（勾选自动兑换且有兑换计划时，先逐条购买补足材料）
---@return XFlowTreeAction?
function XUiEquipPartnerEnhanceProgressPopup:_BuildPrepareNode()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    if not mainControl:IsAutoExchange() then
        return nil
    end
    if XTool.IsTableEmpty(mainControl:GetCommitControl():GetExchangePlanList()) then
        return nil
    end

    local XFlowTreeActionPartnerOneKeyAutoExchange = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyAutoExchange")
    return XFlowTreeActionPartnerOneKeyAutoExchange.New()
end

--- 构建升级+突破节点
---@return XFlowTreeSequence?
function XUiEquipPartnerEnhanceProgressPopup:_BuildLevelUpNode()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local XPartnerEnum = XMVCA.XPartner.Enum

    if not (mainControl:GetCommitControl():IsCultureSelected(XPartnerEnum.CultureType.LevelUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.LevelUp)) then
        return nil
    end

    local XFlowTreeRequire = require("XFlowTree/XFlowTreeRequire")
    local XFlowTreeActionPartnerOneKeyLvExpUp = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyLvExpUp")
    local XFlowTreeActionPartnerOneKeyLvBreakUp = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyLvBreakUp")
    local XFlowTreeActionSetCellStatus = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionSetCellStatus")
    local XFlowTreeActionDelay = XFlowTreeRequire.XFlowTreeActionDelay

    local commitControl = mainControl:GetCommitControl()
    local baseCostControl = mainControl:GetBaseCostControl()
    local EnhanceProgressType = XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType

    local seq = XFlowTreeRequire.XFlowTreeSequence.New()
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._LevelUpCell, EnhanceProgressType.Processing))

    local levelUpMOList = baseCostControl:GetLevelUpMOList()
    local levelUpConsumeIndex = commitControl:GetLevelUpConsumeIndex()
    for i = 1, levelUpConsumeIndex do
        local mo = levelUpMOList[i]
        if mo:GetCultureType() == XPartnerEnum.CultureType.LevelUp then
            seq:AddChild(XFlowTreeActionPartnerOneKeyLvExpUp.New(mo))
        elseif mo:GetCultureType() == XPartnerEnum.CultureType.BreakUp then
            seq:AddChild(XFlowTreeActionPartnerOneKeyLvBreakUp.New(mo))
        end
    end

    seq:AddChild(XFlowTreeActionDelay.New(1))
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._LevelUpCell, EnhanceProgressType.Done))
    return seq
end

--- 构建升星节点
---@return XFlowTreeSequence?
function XUiEquipPartnerEnhanceProgressPopup:_BuildStarUpNode()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local XPartnerEnum = XMVCA.XPartner.Enum

    if not (mainControl:GetCommitControl():IsCultureSelected(XPartnerEnum.CultureType.StarUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.StarUp)) then
        return nil
    end

    local XFlowTreeRequire = require("XFlowTree/XFlowTreeRequire")
    local XFlowTreeActionPartnerOneKeyStarFeed = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyStarFeed")
    local XFlowTreeActionPartnerOneKeyStarEvolution = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyStarEvolution")
    local XFlowTreeActionPartnerOneKeyStarClipExchange = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyStarClipExchange")
    local XFlowTreeActionPartnerOneKeyStarOreExchange = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeyStarOreExchange")
    local XFlowTreeActionSetCellStatus = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionSetCellStatus")
    local XFlowTreeActionDelay = XFlowTreeRequire.XFlowTreeActionDelay
    local XFlowTreeActionFunCall = XFlowTreeRequire.XFlowTreeActionFunCall

    local commitControl = mainControl:GetCommitControl()
    local baseCostControl = mainControl:GetBaseCostControl()
    local EnhanceProgressType = XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType

    local seq = XFlowTreeRequire.XFlowTreeSequence.New()
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._StarUpCell, EnhanceProgressType.Processing))

    -- 矿石兑换碎片（如有选中矿石兑换格子，先用矿石在商店购买碎片）
    if commitControl:GetSelectOreExchangeClipCount() > 0 then
        seq:AddChild(XFlowTreeActionPartnerOneKeyStarOreExchange.New())
    end

    -- 碎片兑换（如有选中碎片，先兑换再喂养）
    if commitControl:GetSelectClipCount() + commitControl:GetSelectOreExchangeClipCount() > 0 then
        seq:AddChild(XFlowTreeActionPartnerOneKeyStarClipExchange.New())
    end

    -- 每个原子：先喂狗粮，再进化
    local starUpMOList = baseCostControl:GetStarUpMOList()
    local starUpConsumeIndex = commitControl:GetStarUpConsumeIndex()
    for i = 1, starUpConsumeIndex do
        seq:AddChild(XFlowTreeActionPartnerOneKeyStarFeed.New(starUpMOList[i]))
        seq:AddChild(XFlowTreeActionPartnerOneKeyStarEvolution.New(starUpMOList[i]))
    end
    if commitControl:HasStarUpTailFeed() then
        seq:AddChild(XFlowTreeActionPartnerOneKeyStarFeed.New(starUpMOList[starUpConsumeIndex + 1], true))
    end

    seq:AddChild(XFlowTreeActionDelay.New(1))
    seq:AddChild(XFlowTreeActionFunCall.New(self._StarUpCell.RefreshQualityIcon, self._StarUpCell))
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._StarUpCell, EnhanceProgressType.Done))
    return seq
end

--- 构建技能升级节点
---@return XFlowTreeSequence?
function XUiEquipPartnerEnhanceProgressPopup:_BuildSkillLevelUpNode()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local XPartnerEnum = XMVCA.XPartner.Enum

    if not (mainControl:GetCommitControl():IsCultureSelected(XPartnerEnum.CultureType.SkillLevelUp) and mainControl:IsNeedCulture(XPartnerEnum.CultureType.SkillLevelUp)) then
        return nil
    end

    local XFlowTreeRequire = require("XFlowTree/XFlowTreeRequire")
    local XFlowTreeActionPartnerOneKeySkillUp = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionPartnerOneKeySkillUp")
    local XFlowTreeActionSetCellStatus = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerEnhanceProgressPopup/ProgressFlow/XFlowTreeActionSetCellStatus")
    local XFlowTreeActionDelay = XFlowTreeRequire.XFlowTreeActionDelay

    local commitControl = mainControl:GetCommitControl()
    local baseCostControl = mainControl:GetBaseCostControl()
    local EnhanceProgressType = XUiEquipPartnerEnhanceProgressCell.EnhanceProgressType

    local seq = XFlowTreeRequire.XFlowTreeSequence.New()
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._SkillLevelUpCell, EnhanceProgressType.Processing))

    local skillMOList = baseCostControl:GetSkillMOList()
    local skillConsumeIndex = commitControl:GetSkillConsumeIndex()
    for i = 1, skillConsumeIndex do
        seq:AddChild(XFlowTreeActionPartnerOneKeySkillUp.New(skillMOList[i]))
    end

    seq:AddChild(XFlowTreeActionDelay.New(1))
    seq:AddChild(XFlowTreeActionSetCellStatus.New(self._SkillLevelUpCell, EnhanceProgressType.Done))
    return seq
end

function XUiEquipPartnerEnhanceProgressPopup:_DestroyCommitFlow()
    if self._CommitFlowRoot then
        self._CommitFlowRoot:DestroyFlowTree()
        self._CommitFlowRoot = nil
    end
end


---@param result XFlowTreeEnum.Result 行为树执行结果
function XUiEquipPartnerEnhanceProgressPopup:_Finish(result)
    local XFlowTreeEnum = require("XFlowTree/XFlowTreeEnum")
    self:_SetFinishView(result == XFlowTreeEnum.Result.Succeed)
    self:_NotifyOneKeyCultureFinish()
end

function XUiEquipPartnerEnhanceProgressPopup:_NotifyOneKeyCultureFinish()
    self._Control:GetOneKeyCultureMainControl():GetBaseCostControl():CalcAllCostData()
    self._Control:DispatchEvent(XMVCA.XPartner.EventIds.EVENT_ONE_KEY_CULTURE_FINISH)
end

return XUiEquipPartnerEnhanceProgressPopup
