--[[
-- XUiPunishaarChallengeSettlementPanelStats.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-21 17:21:58
--]]

---@class XUiPunishaarChallengeSettlementPanelStats : XUiNode
---@field _Control XPunishaarControl
---@field TxtLives UnityEngine.UI.Text
---@field TxtCoin UnityEngine.UI.Text
---@field TxtMaxHp UnityEngine.UI.Text
local XUiPunishaarChallengeSettlementPanelStats = XClass(XUiNode, "XUiPunishaarChallengeSettlementPanelStats")

function XUiPunishaarChallengeSettlementPanelStats:OnStart()
    self:Refresh()
end

---@param settleInfo table|nil XPunishaarSettleInfo（结算数据，nil 时兜底空表）
function XUiPunishaarChallengeSettlementPanelStats:Refresh(settleInfo)
    settleInfo = settleInfo or {}
    -- 存续值：优先取最新 stage.Durability；耐久耗尽失败（DurabilityEnd）时服务端 stage.Durability 可能未及时归零/缺失读旧值，
    -- 按失败条件应 0 特殊处理显 0（避免显示战前残留 1）。Quit（主动退出）耐久未耗尽仍取实时值。#存续值失败显0
    if settleInfo.SettleType == XMVCA.XPunishaar.EnumConst.SettleType.DurabilityEnd then
        self.TxtLives.text = "0"
    else
        self.TxtLives.text = tostring(self._Control:GetCurrentDurability() or 0)
    end
    -- 结算用总获得金币（settleInfo.AllGold）比 GetCurrentGold 更贴结算语义
    self.TxtCoin.text  = tostring(settleInfo.AllGold or 0)
    -- TxtMaxHp：本局战斗 HP 上限 = HPValue + 已胜战斗次数 × HPGrowthValue（口径同 RunControl 开战）
    if self.TxtMaxHp then
        self.TxtMaxHp.text = tostring(self._Control:GetPlayerBattleHp(settleInfo.FightWinCount or 0))
    end
end

return XUiPunishaarChallengeSettlementPanelStats
