--[[
-- XUiPunishaarChallengeSettlement.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-21 17:21:58
--]]

local XUiPunishaarChallengeSettlementPanelRecord    = require("XUi/XUiPunishaar/XUiPunishaarChallengeSettlement/XUiPunishaarChallengeSettlementPanelRecord")
local XUiPunishaarChallengeSettlementPanelStats     = require("XUi/XUiPunishaar/XUiPunishaarChallengeSettlement/XUiPunishaarChallengeSettlementPanelStats")
local XUiPunishaarChallengeSettlementPanelFormation = require("XUi/XUiPunishaar/XUiPunishaarChallengeSettlement/XUiPunishaarChallengeSettlementPanelFormation")
local XUiPanelPunishaarTipsRoot = require("XUi/XUiPunishaar/XUiPunishaarCommonCardDetail/XUiPanelPunishaarTipsRoot")

---@class XUiPunishaarChallengeSettlement : XLuaUi
---@field _Control XPunishaarControl
---@field BtnRestart XUiComponent.XUiButton
---@field BtnExit XUiComponent.XUiButton
---@field TxtStageProgress UnityEngine.UI.Text
---@field GroupControl XUiComponent.XUiGroupControl 结算胜负状态控制器（Finished=Win，其余=Lose）+ 文本组0=关卡名称 #69
---@field PanelRecord XUiPunishaarChallengeSettlementPanelRecord
---@field PanelStats XUiPunishaarChallengeSettlementPanelStats
---@field PanelFormation XUiPunishaarChallengeSettlementPanelFormation
---@field CardTipsPanelRoot UnityEngine.RectTransform 卡牌详情浮窗挂载根
---@field TipsRoot XUiPanelPunishaarTipsRoot
local XUiPunishaarChallengeSettlement = XLuaUiManager.Register(XLuaUi, "UiPunishaarChallengeSettlement")

-- 结算胜负态：Finished=胜利，其余（DurabilityEnd/Quit/None）=失败
local UiState = {
    Win  = "Win",
    Lose = "Lose",
}

function XUiPunishaarChallengeSettlement:OnAwake()
    self:_InitComponents()
end

function XUiPunishaarChallengeSettlement:_InitComponents()
    self.BtnRestart:AddEventListener(handler(self, self._OnBtnRestart))
    self.BtnExit:AddEventListener(handler(self, self._OnBtnExit))

    self.PanelRecord    = XUiPunishaarChallengeSettlementPanelRecord.New(self.PanelRecord, self)
    self.PanelStats     = XUiPunishaarChallengeSettlementPanelStats.New(self.PanelStats, self)
    self.PanelFormation = XUiPunishaarChallengeSettlementPanelFormation.New(self.PanelFormation, self)

    -- TipsRoot：常驻 Open，挂在 CardTipsPanelRoot 下，按对象路由 3 个子 Tips（对齐 FightMain）
    self.CardTipsPanelRoot.gameObject:SetActiveEx(false)
    ---@type XUiPanelPunishaarTipsRoot
    self.TipsRoot = XUiPanelPunishaarTipsRoot.New(self.CardTipsPanelRoot, self)
    self.TipsRoot:Open()
end

--region 卡牌详情浮窗转发（供 PanelFormation 内 grid 的 _GetTipsHost 沿父链找到本界面）

function XUiPunishaarChallengeSettlement:ShowMainCardTips(data, posUi)
    -- 结算只读（局已结束，不出买卖/丢弃按钮）
    self.TipsRoot:ShowMainCard(data, posUi, true)
end

function XUiPunishaarChallengeSettlement:ShowSubCardTips(data, posUi)
    self.TipsRoot:ShowSubCard(data, posUi)
end

function XUiPunishaarChallengeSettlement:ShowEnemyTips(fightId, posUi)
    self.TipsRoot:ShowEnemy(fightId, posUi)
end

function XUiPunishaarChallengeSettlement:HideTips()
    self.TipsRoot:Hide()
end

--endregion

---@param settleInfo table 服务端整局结算数据（字段结构待协议确认）
function XUiPunishaarChallengeSettlement:OnStart(settleInfo)
    self._SettleInfo = settleInfo
    self:Refresh()
end

function XUiPunishaarChallengeSettlement:OnEnable()
end

function XUiPunishaarChallengeSettlement:OnDisable()
end

function XUiPunishaarChallengeSettlement:OnDestroy()
end

function XUiPunishaarChallengeSettlement:Refresh()
    local settleInfo = self._SettleInfo or {}
    -- 胜负态 + 关卡名：GroupControl 两状态(Win/Lose) + 文本组0=关卡名称 #69
    -- 接口：ChangeGroup(key) 互斥显隐 / SetText(index, content) 设当前组文本子组
    if self.GroupControl then
        local isWin = settleInfo.SettleType == XMVCA.XPunishaar.EnumConst.SettleType.Finished
        self.GroupControl:ChangeGroup(isWin and UiState.Win or UiState.Lose)
        local stageName = XMVCA.XPunishaar:GetCfgStageNameByStageId(settleInfo.StageId) or ""
        self.GroupControl:SetText(0, stageName)
    end
    -- TxtStageProgress：关卡名 · 第N轮（CurrentRound 结算到达轮次，无尽关有意义）
    if self.TxtStageProgress then
        local stageName = XMVCA.XPunishaar:GetCfgStageNameByStageId(settleInfo.StageId) or ""
        self.TxtStageProgress.text = XUiHelper.FormatTextEx(
            XMVCA.XPunishaar:GetClientStringByKey("SettleStageProgressShow"),
            stageName)
    end
    self.PanelStats:Refresh(settleInfo)
    self.PanelFormation:Refresh()
    -- PanelRecord（挑战记录+破纪录）仅无尽关显示
    if self._Control:IsEndlessStage(settleInfo.StageId) then
        self.PanelRecord:Open()
        self.PanelRecord:Refresh(settleInfo)
    else
        self.PanelRecord:Close()
    end
end

function XUiPunishaarChallengeSettlement:_OnBtnRestart()
    local stageId = self._Control:GetCurrentStageId()
    if not stageId then
        XLog.Error("[Punishaar] ChallengeSettlement: 无法获取当前关卡ID，重新挑战失败")
        return
    end
    self._Control.GameControl:ClearCurrentRun()
    -- 关旧 FightMain（#66 基底在结算期保持打开，此处重启须先关）
    -- 防 EnterGame→ReleaseGameControl+InitGameControl+EnterRun→TransitionTo(fromPanel=nil) 重复打开 FightMain
    self._Control.GameControl:ExitRun()
    self._Control:StartStage(stageId, function(data)
        self._Control:EnterGame(data)
        self:Close()
    end)
end

function XUiPunishaarChallengeSettlement:_OnBtnExit()
    -- ExitRun 关 FightMain（RunControl 仍存活，须在 ReleaseGameControl 释放 GameControl 前）
    -- FightMain 在新方案下贯穿结算期作 #66 持久基底（Open 前 不 ExitRun），此处退出时才关
    self._Control.GameControl:ExitRun()
    self._Control.GameControl:ClearCurrentRun()
    -- 退出结算界面 = 真正退出关卡（修正1）：释放关卡级 GameControl（级联 Run/Fight）
    self._Control:ReleaseGameControl()
    self:Close()
    -- 兜底：ChooseStage 进局时未 Remove（fromPanel=nil），Close 结算后通常已恢复栈顶；
    -- 若因其他路径未加载则 Open，避免重复打开栈顶警告
    if not XLuaUiManager.IsUiLoad("UiPunishaarChooseStage") then
        XLuaUiManager.Open("UiPunishaarChooseStage")
    end
end

return XUiPunishaarChallengeSettlement
