--[[
-- XUiPunishaarChallengeSettlementPanelRecord.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-21 17:21:58
--]]

---@class XUiPunishaarChallengeSettlementPanelRecord : XUiNode
---@field _Control XPunishaarControl
---@field TagNew UnityEngine.UI.Text
---@field TxtRoundRecord UnityEngine.UI.Text
local XUiPunishaarChallengeSettlementPanelRecord = XClass(XUiNode, "XUiPunishaarChallengeSettlementPanelRecord")

function XUiPunishaarChallengeSettlementPanelRecord:OnStart()
    -- TagNew 默认隐（防 prefab 默认 active 残留显，显隐由 Refresh 按 IsNewRecord 决定）
    if self.TagNew then
        self.TagNew.gameObject:SetActiveEx(false)
    end
end

---@param settleInfo table|nil XPunishaarSettleInfo（结算数据，nil 时兜底空表）
function XUiPunishaarChallengeSettlementPanelRecord:Refresh(settleInfo)
    settleInfo = settleInfo or {}
    local stageId = settleInfo.StageId
    local round = settleInfo.CurrentRound or 0
    -- 当前节点序号（stage.HistoryNodeList+1）+ 总节点数（StageContentIds 长度）
    local nodeIndex = self._Control:GetCurrentNodeIndex()
    local totalNode = stageId and self._Control:GetStageTotalNodeCount(stageId) or 0
    -- 轮末结算 HistoryNodeList 可能=totalNode 致 nodeIndex=totalNode+1，封顶对齐 GetStageProgress
    if totalNode > 0 and nodeIndex > totalNode then
        nodeIndex = totalNode
    end
    -- TxtRoundRecord：ClientConfig 插值"第{0}轮 第{1}/{2}节点"（轮次/当前节点/总节点，无尽关有意义）
    if self.TxtRoundRecord then
        local fmt = XMVCA.XPunishaar:GetClientStringByKey("PunishaarRoundNodeRecordFormat")
        if not string.IsNilOrEmpty(fmt) then
            self.TxtRoundRecord.text = XUiHelper.FormatTextEx(fmt, tostring(round), tostring(nodeIndex), tostring(totalNode))
        else
            self.TxtRoundRecord.text = tostring(round)
            if not self._FmtWarned then
                self._FmtWarned = true
                XLog.Error("[Punishaar] ClientConfig key 'PunishaarRoundNodeRecordFormat' 未配置，请补插值文本（第{0}轮 第{1}/{2}节点）#无尽关进度")
            end
        end
    end
    -- TagNew（破纪录）：服务端 IsNewRecord 字段（本局是否创造新挑战最佳纪录，无尽关有意义，平纪录不算）
    if self.TagNew then
        self.TagNew.gameObject:SetActiveEx(settleInfo.IsNewRecord == true)
    end
end

return XUiPunishaarChallengeSettlementPanelRecord
