--[[
-- XUiPunishaarExploreDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-01 15:16:21
--]]

---@class XUiPunishaarExploreDetail : XLuaUi
---@field _Control XPunishaarControl
---@field BtnMask XUiComponent.XUiButton
---@field PanelStory UnityEngine.RectTransform
---@field TxtStoryName UnityEngine.UI.Text
---@field TxtStoryDec UnityEngine.UI.Text
---@field BtnEnterStory XUiComponent.XUiButton
---@field PanelAsset UnityEngine.RectTransform
---@field BtnRetryFight XUiComponent.XUiButton
---@field BtnResumeFight XUiComponent.XUiButton
---@field BtnStartFight XUiComponent.XUiButton
---@field TxtProgress UnityEngine.UI.Text
local XUiPunishaarExploreDetail = XLuaUiManager.Register(XLuaUi, "UiPunishaarExploreDetail")
function XUiPunishaarExploreDetail:OnAwake()
    self:InitComponents()
end

function XUiPunishaarExploreDetail:InitComponents()
    -- Button
    self.BtnMask:AddEventListener(function() self:OnBtnMaskClick() end)
    self.BtnEnterStory:AddEventListener(function() self:OnBtnEnterStoryClick() end)
    self.BtnRetryFight:AddEventListener(function() self:OnBtnRetryFightClick() end)
    self.BtnResumeFight:AddEventListener(function() self:OnBtnResumeFightClick() end)
    self.BtnStartFight:AddEventListener(function() self:OnBtnStartFightClick() end)

    -- PanelAsset
    self.PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, XDataCenter.ItemManager.ItemId.FreeGem)

end

function XUiPunishaarExploreDetail:OnStart(stageId)
    self:Refresh(stageId)
end

function XUiPunishaarExploreDetail:OnEnable()
end

function XUiPunishaarExploreDetail:OnDisable()
end

function XUiPunishaarExploreDetail:OnDestroy()
end

function XUiPunishaarExploreDetail:Refresh(stageId)
    self._StageId = stageId

    local stageCfg = XMVCA.XPunishaar:GetTablePunishaarStageGroupById(stageId)
    local stageStatus = XMVCA.XPunishaar:GetStageStatus(stageId)
    local isPassed = stageStatus == XMVCA.XPunishaar.EnumConst.StageStatus.Passed
    local isHasSave = stageStatus == XMVCA.XPunishaar.EnumConst.StageStatus.HasSave
    local storyId = XMVCA.XPunishaar:GetExploreDetailStoryId(stageId)

    local stageIndex = string.format("%02d", stageId % 100)
    local stageName = stageCfg and stageCfg.Name or ""

    self.TxtStoryName.text = XUiHelper.FormatTextEx(
        self._Control:GetStageDetailNameText(),
        stageIndex,
        stageName
    )
    self.TxtStoryDec.text = stageCfg and stageCfg.Desc or ""
    self.BtnStartFight.gameObject:SetActiveEx(not isHasSave and not isPassed)
    self.BtnResumeFight.gameObject:SetActiveEx(isHasSave and not isPassed)
    self.BtnRetryFight.gameObject:SetActiveEx(isPassed)

    self.BtnEnterStory.gameObject:SetActiveEx((isHasSave or isPassed) and not string.IsNilOrEmpty(storyId))

    local isShowProgress = isHasSave and not isPassed
    self.TxtProgress.gameObject:SetActiveEx(isShowProgress)
    self.Txt.gameObject:SetActiveEx(isShowProgress)

    if isShowProgress then
        local cur, total = XMVCA.XPunishaar:GetStageProgress(stageId)
        self.TxtProgress.text = XUiHelper.FormatTextEx(
            self._Control:GetStageProgressText(),
            cur,
            total
        )
    end
end

function XUiPunishaarExploreDetail:OnBtnMaskClick()
    self:Close()
end

function XUiPunishaarExploreDetail:OnBtnEnterStoryClick()
    self._Control:EnterStory(self._StageId)
end

function XUiPunishaarExploreDetail:OnBtnRetryFightClick()
    self:StartStageWithStory()
end

function XUiPunishaarExploreDetail:OnBtnResumeFightClick()
    local control = self._Control
    control:ContinueStage(self._StageId, function(data)
        if not data then
            return
        end
        self:Close()
        control:EnterGame(data)
    end)
end

function XUiPunishaarExploreDetail:OnBtnStartFightClick()
    self:StartStageWithStory()
end

function XUiPunishaarExploreDetail:StartStageWithStory()
    local control = self._Control
    local stageId = self._StageId

    control:StartStage(stageId, function(data)
        if not data then
            return
        end

        self:Close()
        CsXUiManager.Instance:SetReleaseAllLock(true)
        control:EnterStory(stageId, function()
            CsXUiManager.Instance:SetReleaseAllLock(false)
            control:EnterGame(data)
        end)
    end)
end
return XUiPunishaarExploreDetail
