--[[
-- XUiPunishaarCollection.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-02 15:23:32
--]]

---@class XUiPunishaarCollection: XLuaUi
---@field PanelTabGroup                XUiButtonGroup
---@field Content                      UnityEngine.RectTransform
---@field TxtProgressNum               UnityEngine.UI.Text
---@field TopControlWhite              UnityEngine.RectTransform
---@field BtnHelp                      XUiComponent.XUiButton
---@field UiPunishaarShopCardTips_Main UnityEngine.RectTransform
---@field PanelCardList XDynamicTableIrregular
------@field PanelSubCardList             UnityEngine.RectTransform
local XUiPunishaarCollection = XLuaUiManager.Register(XLuaUi, "UiPunishaarCollection")
local XDynamicTableIrregular = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableIrregular")
local XDynamicTableNormal = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableNormal")
local XUiPanelPunishaarCollection = require("XUi/XUiPunishaar/Panel/XUiPanelPunishaarCollection")
local XUiPanelPunishaarCollectionMainCardTips = require("XUi/XUiPunishaar/Panel/XUiPanelPunishaarCollectionMainCardTips")
local PROXY_TYPE_GROUP = "PunishaarCollectionGroup"
local XUiGridPunishaarCollectionSubCard = require("XUi/XUiPunishaar/Grid/XUiGridPunishaarCollectionSubCard")
function XUiPunishaarCollection:OnAwake()
    self:InitComponents()
end

function XUiPunishaarCollection:InitComponents()
    -- Back Mainui Help
    self:BindHelpBtn(self.BtnHelp, "XPunishaarHelp")
    XUiHelper.NewPanelTopControl(self, self.TopControlWhite)

    self.DynamicTable = XDynamicTableIrregular.New(self.PanelCardList)
    self.DynamicTable:SetProxy(
        PROXY_TYPE_GROUP,
        XUiPanelPunishaarCollection,
        self.GridSlotList.gameObject,
        self
    )
    self.DynamicTable:SetDelegate(self)
    
    self.GridSlotList.gameObject:SetActiveEx(false)
    self.PanelCardList.gameObject:SetActiveEx(false)
    self.PanelSubCardList.gameObject:SetActiveEx(false)
    self.MainCardDetail = XUiPanelPunishaarCollectionMainCardTips.New(self.UiPunishaarShopCardTips_Main, self)
    self.SubCardDynamicTable = XDynamicTableNormal.New(self.PanelSubCardList)
    self.SubCardDynamicTable:SetProxy(XUiGridPunishaarCollectionSubCard, self)
    self.SubCardDynamicTable:SetDelegate(self)
    self.SubCardDynamicTable:SetDynamicEventDelegate(handler(self, self.OnSubCardDynamicTableEvent))
    self.UiPunishaarSubCard.gameObject:SetActiveEx(false)
end

function XUiPunishaarCollection:OnStart(...)
    self._CurSelectedTabIndex = 1
    self._CurrCollectionDatas = {}
    self._CurrSizeGroup = {}

    self:InitProgressColors()
    self:InitTabs()

    self.PanelTabGroup:SelectIndex(
        self._CurSelectedTabIndex
    )
    self:RefreshReddot()
end

function XUiPunishaarCollection:InitProgressColors()
    self._ProgressNormalColor = self.TxtProgressNum.color
    self._ProgressFullColor = self.TxtProgressNum.color

    local normalColorStr = self._Control:GetCollectionProgressColor(false)

    local fullColorStr = self._Control:GetCollectionProgressColor(true)

    if not string.IsNilOrEmpty(normalColorStr) then
        normalColorStr = string.gsub(normalColorStr, "^#", "")
        self._ProgressNormalColor = XUiHelper.Hexcolor2Color(normalColorStr)
    end

    if not string.IsNilOrEmpty(fullColorStr) then
        fullColorStr = string.gsub(fullColorStr, "^#", "")
        self._ProgressFullColor = XUiHelper.Hexcolor2Color(fullColorStr)
    end
end

function XUiPunishaarCollection:GetProxyType(index)
    return PROXY_TYPE_GROUP
end

function XUiPunishaarCollection:OnEnable()
end

function XUiPunishaarCollection:OnDisable()
end

function XUiPunishaarCollection:OnDestroy()
end

function XUiPunishaarCollection:InitTabs()
    local tabGroup = {}

    for i = 1, self.PanelTabGroup.transform.childCount do
        local childBtn = self.PanelTabGroup.transform:GetChild(i - 1)

        local btn = childBtn:GetComponent("XUiButton")

        local tabName = XMVCA.XPunishaar:GetClientStringByKey(
            "CardTypeNames",
            i
        )

        if not string.IsNilOrEmpty(tabName) then
            btn:SetNameByGroup(0, tabName)
        end
        
        
        tabGroup[#tabGroup + 1] = childBtn:GetComponent("XUiButton")
    end

    self.PanelTabGroup:Init(
        tabGroup,
        handler(self, self.OnTabGroupClick)
    )
    self:InitReddot(tabGroup)
end

function XUiPunishaarCollection:InitReddot(tabGroup)
    local CatalogType = XMVCA.XPunishaar.EnumConst.CatalogType
    local catalogTypes = {
        CatalogType.Character,
        CatalogType.Partner,
        CatalogType.Equip,
        CatalogType.Resonance,
    }

    self._CollectionReddotIds = {}

    for index, catalogType in ipairs(catalogTypes) do
        local btn = tabGroup[index]

        self._CollectionReddotIds[index] = self:AddRedPointEvent(
            btn,
            function(_, count)
                btn:ShowReddot(count >= 0)
            end,
            self,
            { XRedPointConditions.Types.CONDITION_PUNISHAAR_COLLECTION },
            catalogType,
            false
        )
    end
end

function XUiPunishaarCollection:RefreshReddot()
    for _, redPointId in ipairs(self._CollectionReddotIds or {}) do
        XRedPointManager.Check(redPointId)
    end
end

---@param percent number
function XUiPunishaarCollection:RefreshProgress(percent)
    percent = math.max(0, math.min(percent or 0, 100))

    self.TxtProgressNum.text = string.format("%d%%", percent)

    if percent >= 100 then
        self.TxtProgressNum.color = self._ProgressFullColor
    else
        self.TxtProgressNum.color = self._ProgressNormalColor
    end
end

function XUiPunishaarCollection:Refresh()
    self:OnTabGroupClick(self._CurSelectedTabIndex)
end

function XUiPunishaarCollection:OnTabGroupClick(index)
    self:ClearMainCardSelection()
    self._CurSelectedTabIndex = index

    local CardType = XMVCA.XPunishaar.EnumConst.CardType
    local CatalogType = XMVCA.XPunishaar.EnumConst.CatalogType

    local catalogType

    if index == 1 then
        catalogType = CatalogType.Character
        self:RefreshMainCollection(CardType.Character)

    elseif index == 2 then
        catalogType = CatalogType.Partner
        self:RefreshMainCollection(CardType.Weapon)

    elseif index == 3 then
        catalogType = CatalogType.Equip
        self:RefreshSubCollection(CardType.Awareness)

    elseif index == 4 then
        catalogType = CatalogType.Resonance
        self:RefreshSubCollection(CardType.Resonance)
    end

    if catalogType then
        self._Control:MarkCollectionRead(catalogType)
    end
end

function XUiPunishaarCollection:RefreshMainCollection(cardType)
    self.PanelCardList.gameObject:SetActiveEx(true)
    self.PanelSubCardList.gameObject:SetActiveEx(false)

    local groups, _, _, percent = self._Control:GetMainCollectionGroups(cardType)

    self._CurrCollectionDatas = {}
    self._CurrSizeGroup = {}

    for _, group in ipairs(groups) do
        if #group.Cards > 0 then
            self._CurrCollectionDatas[group.Size] = group.Cards

            self._CurrSizeGroup[#self._CurrSizeGroup + 1] = group.Size
        end
    end

    self:RefreshProgress(percent)

    self.DynamicTable:SetDataSource(
        self._CurrSizeGroup
    )
    self.DynamicTable:ReloadDataASync(1)
end

function XUiPunishaarCollection:RefreshSubCollection(cardType)
    self.PanelCardList.gameObject:SetActiveEx(false)
    self.PanelSubCardList.gameObject:SetActiveEx(true)

    self._CurrCollectionDatas = {}
    self._CurrSizeGroup = {}

    self.DynamicTable:SetDataSource({})
    self.DynamicTable:RecycleAllTableGrid()

    local datas, _, _, percent =
    self._Control:GetSubCollectionDatas(cardType)

    self:RefreshProgress(percent)

    self._SubCardDatas = datas
    self._DefaultSubCardIndex = nil

    -- 优先选择第一张已解锁副卡
    for index, data in ipairs(datas) do
        if data.IsUnlocked then
            self._DefaultSubCardIndex = index
            break
        end
    end

    -- 没有已解锁副卡时，选择第一张未解锁副卡
    if not self._DefaultSubCardIndex and #datas > 0 then
        self._DefaultSubCardIndex = 1
    end

    self.SubCardDynamicTable:SetDataSource(datas)
    self.SubCardDynamicTable:ReloadDataSync(self._DefaultSubCardIndex or 1)
end


function XUiPunishaarCollection:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local size = self._CurrSizeGroup[index]

        if size and grid then
            grid:Refresh(size)
        end

    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_RELOAD_COMPLETED then
        local selected = false

        -- 优先选择所有分组中的第一张已解锁卡
        for i = 1, #self._CurrSizeGroup do
            local groupGrid = self.DynamicTable:GetGridByIndex(i)

            if groupGrid and groupGrid:SelectFirstCard(false) then
                selected = true
                break
            end
        end

        -- 没有默认选中卡时，从当前存在的第一个分组开始选择第一张已解锁卡
        if not selected then
            for i = 1, #self._CurrSizeGroup do
                local groupGrid = self.DynamicTable:GetGridByIndex(i)

                if groupGrid and groupGrid:SelectFirstCard(true) then
                    break
                end
            end
        end
    end
end

function XUiPunishaarCollection:OnSubCardDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local data = self.SubCardDynamicTable:GetData(index)
        if data and grid then
            grid:Refresh(data)
            grid:SetSelected(
                self:IsCardSelected(data.Id)
            )
        end

    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_RELOAD_COMPLETED then
        local defaultIndex = self._DefaultSubCardIndex
        if not defaultIndex then
            return
        end

        local data = self.SubCardDynamicTable:GetData(defaultIndex)

        local defaultGrid = self.SubCardDynamicTable:GetGridByIndex(defaultIndex)

        if data and defaultGrid then
            self:OnSubCardClick(data, defaultGrid)
        end
    end
end

function XUiPunishaarCollection:OnMainCardClick(data, grid)
    if not data then
        return
    end

    if self._SelectedCardGrid and self._SelectedCardGrid ~= grid then
        self._SelectedCardGrid:SetSelected(false)
    end

    self._SelectedCardGrid = grid
    self._SelectedCardId = data.Id
    grid:SetSelected(true)

    self.MainCardDetail:Open()
    self.MainCardDetail:RefreshCollection({
        cardId = data.Id,
        level = 1,
        collectionLocked = not data.IsUnlocked,
    })
end

function XUiPunishaarCollection:OnSubCardClick(data, grid)
    if not data then
        return
    end

    if self._SelectedCardGrid
        and self._SelectedCardGrid ~= grid
    then
        self._SelectedCardGrid:SetSelected(false)
    end

    self._SelectedCardGrid = grid
    self._SelectedCardId = data.Id

    grid:SetSelected(true)

    self.MainCardDetail:Open()
    self.MainCardDetail:RefreshCollection({
        cardId = data.Id,
        collectionSubCard = true,
        collectionLocked = not data.IsUnlocked,
    })
end


function XUiPunishaarCollection:IsCardSelected(cardId)
    return self._SelectedCardId == cardId
end

function XUiPunishaarCollection:ClearMainCardSelection()
    if self._SelectedCardGrid then
        self._SelectedCardGrid:SetSelected(false)
    end

    self._SelectedCardGrid = nil
    self._SelectedCardId = nil

    self.MainCardDetail:Close()
end

function XUiPunishaarCollection:GetCurrentCollectionDatas()
    return self._CurrCollectionDatas
end
return XUiPunishaarCollection
