--[[
-- XUiPunishaarMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-01 15:02:44
--]]

---@class XUiPunishaarMain : XLuaUi
---@field _Control XPunishaarControl
---@field TxtPunishaarName UnityEngine.UI.Text
---@field PanelTime UnityEngine.RectTransform
---@field TxtTime UnityEngine.UI.Text
---@field TopControl UnityEngine.RectTransform
---@field BtnHelp XUiComponent.XUiButton
---@field BtnCollection XUiComponent.XUiButton
---@field BtnTask XUiComponent.XUiButton
---@field CommonTaskRewardLeft UnityEngine.RectTransform
---@field Grid256New UnityEngine.RectTransform
---@field BtnGoFight XUiComponent.XUiButton
local XUiPunishaarMain = XLuaUiManager.Register(XLuaUi, "UiPunishaarMain")
local XUiGridCommon = require("XUi/XUiObtain/XUiGridCommon")
local XUiPunishaarMainModelShow = require("XUi/XUiPunishaar/XUiPunishaarMainModelShow")

function XUiPunishaarMain:OnAwake()
    self:InitComponents()
end

function XUiPunishaarMain:InitComponents()
    -- Back Mainui Help
    self:BindHelpBtn(self.BtnHelp, "XPunishaarHelp")
    -- Button
    XUiHelper.NewPanelTopControl(self, self.TopControl)
    self.BtnCollection:AddEventListener(function()
        self:OnBtnCollectionClick()
    end)
    self.BtnTask:AddEventListener(function()
        self:OnBtnTaskClick()
    end)
    self.BtnGoFight:AddEventListener(function()
        self:OnBtnGoFightClick()
    end)
    if self.Grid256New then
        self.Grid256New.gameObject:SetActiveEx(false)
    end

    ---@type XUiPunishaarMainModelShow
    self.ModelShow = XUiPunishaarMainModelShow.New(self.UiModelGo, self)
    self.ModelShow:Open()
end

function XUiPunishaarMain:OnStart(...)
    local activityCfg = self._Control:GetActivityCfg()
    if not activityCfg then
        return
    end

    --标题
    self.TxtPunishaarName.text = activityCfg.Name
    
    self:InitReddot()
    self:RefreshRewardPreview()
    self.ModelShow:PlayStartAnimation()
end

function XUiPunishaarMain:OnEnable()
    self._Control:AddTimeEventListener(self.UpdateLeftTime, self)
    self:RefreshReddot()
end

function XUiPunishaarMain:OnDisable()
    self._Control:RemoveTimeEventListener(self.UpdateLeftTime, self)
end

function XUiPunishaarMain:OnDestroy()
end

function XUiPunishaarMain:Refresh()
    self:RefreshRewardPreview()
    self:RefreshReddot()
end

function XUiPunishaarMain:OnBtnCollectionClick()
    self._Control:GetStageData(function(success)
        if success then
            XLuaUiManager.Open("UiPunishaarCollection")
        end
    end)
end

function XUiPunishaarMain:OnBtnTaskClick()
    XLuaUiManager.Open("UiPunishaarTask")
end

function XUiPunishaarMain:OnBtnGoFightClick()
    self._Control:GetStageData(function(success)
        if success then
            XLuaUiManager.Open("UiPunishaarChooseStage")
        end
    end)
end

function XUiPunishaarMain:UpdateLeftTime(timeId)
    local endTime = XFunctionManager.GetEndTimeByTimeId(timeId)
    local leftTime = math.max(endTime - XTime.GetServerNowTimestamp(), 0)

    self.TxtTime.text = XUiHelper.GetTime(leftTime, XUiHelper.TimeFormatType.ACTIVITY)
end

function XUiPunishaarMain:RefreshRewardPreview()
    if not self.Grid256New then
        return
    end

    local rewardId = self._Control:GetDisplayRewardId()
    local rewards = {}

    if XTool.IsNumberValid(rewardId) then
        rewards = XRewardManager.GetRewardListNotCount(rewardId) or {}
    end

    XUiHelper.RefreshCustomizedList(
        self.Grid256New.transform.parent,
        self.Grid256New,
        #rewards,
        function(index, obj)
            local grid = XUiGridCommon.New(self, obj)
            grid:Refresh(rewards[index])
        end
    )
end

function XUiPunishaarMain:InitReddot()
    self._TaskReddotId = self:AddRedPointEvent(
        self.BtnTask,
        function(_, count)
            self.BtnTask:ShowReddot(count >= 0)
        end,
        self,
        { XRedPointConditions.Types.CONDITION_PUNISHAAR_TASK },
        nil,
        false
    )
    self._CollectionReddotId = self:AddRedPointEvent(
        self.BtnCollection,
        function(_, count)
            self.BtnCollection:ShowReddot(count >= 0)
        end,
        self,
        { XRedPointConditions.Types.CONDITION_PUNISHAAR_COLLECTION },
        nil,
        false
    )
end

function XUiPunishaarMain:RefreshReddot()
    XRedPointManager.Check(self._TaskReddotId)
    XRedPointManager.Check(self._CollectionReddotId)

    XRedPointManager.CheckOnceByButton(
        self.BtnGoFight,
        {
            XRedPointConditions.Types.CONDITION_PUNISHAAR_STAGE
        }
    )
end
return XUiPunishaarMain
