--[[
-- XUiEquipOneClickAutoCommonSetting.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-06 11:55:23
--]]

---@class XUiEquipOneClickAutoCommonSetting : XLuaUi
---@field _Control XEquipControl
---@field BtnTanchuangClose XUiComponent.XUiButton
---@field BtnClosePopup XUiComponent.XUiButton
---@field PanelAsset UnityEngine.RectTransform
---@field BtnWeaponLevel XUiComponent.XUiButton
---@field BtnWeaponResonance XUiComponent.XUiButton
---@field BtnWeaponOverrun XUiComponent.XUiButton
---@field BtnAwarenessLevel XUiComponent.XUiButton
---@field BtnAwarenessResnance XUiComponent.XUiButton
---@field BtnAwarenessOverclocking XUiComponent.XUiButton
---@field BtnPartnerLevel XUiComponent.XUiButton
---@field BtnPartnerQuality XUiComponent.XUiButton
---@field BtnPartnerSkill XUiComponent.XUiButton
---@field BtnSaveSet XUiComponent.XUiButton
---@field ToggleComfirmSetting UnityEngine.UI.Toggle
local XUiEquipOneClickAutoCommonSetting = XLuaUiManager.Register(XLuaUi, "UiEquipOneClickAutoCommonSetting")

function XUiEquipOneClickAutoCommonSetting:OnAwake()
    self:InitComponents()
end

function XUiEquipOneClickAutoCommonSetting:InitComponents()
    -- Button
    self.BtnTanchuangClose:AddEventListener(function() self:OnBtnTanchuangCloseClick() end)
    self.BtnClosePopup:AddEventListener(function() self:OnBtnClosePopupClick() end)
    self.BtnWeaponLevel:AddEventListener(function() self:OnBtnWeaponLevelClick() end)
    self.BtnWeaponResonance:AddEventListener(function() self:OnBtnWeaponResonanceClick() end)
    self.BtnWeaponOverrun:AddEventListener(function() self:OnBtnWeaponOverrunClick() end)
    self.BtnAwarenessLevel:AddEventListener(function() self:OnBtnAwarenessLevelClick() end)
    self.BtnAwarenessResnance:AddEventListener(function() self:OnBtnAwarenessResnanceClick() end)
    self.BtnAwarenessOverclocking:AddEventListener(function() self:OnBtnAwarenessOverclockingClick() end)
    self.BtnPartnerLevel:AddEventListener(function() self:OnBtnPartnerLevelClick() end)
    self.BtnPartnerQuality:AddEventListener(function() self:OnBtnPartnerQualityClick() end)
    self.BtnPartnerSkill:AddEventListener(function() self:OnBtnPartnerSkillClick() end)
    self.BtnSaveSet:AddEventListener(function() self:OnBtnSaveSetClick() end)

    -- Toggle
    self.ToggleComfirmSetting.onValueChanged:AddListener(function(value) self:OnToggleComfirmSettingValueChanged(value) end)

end

function XUiEquipOneClickAutoCommonSetting:OnStart(...)
    self:_InitSettingDic()
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnEnable()
end

function XUiEquipOneClickAutoCommonSetting:OnDisable()
end

function XUiEquipOneClickAutoCommonSetting:OnDestroy()
end

---region ui event

function XUiEquipOneClickAutoCommonSetting:OnBtnTanchuangCloseClick()
    self:Close()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnClosePopupClick()
    self:Close()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnSaveSetClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    local settingControl = self._Control.OneClickAutoSettingControl
    for _, settingType in ipairs(XEquipEnum.OneClickAutoSettingGlobalTypeList) do
        if self._SettingDic[settingType] ~= settingControl:GetSetting(settingType) then
            self:_SubmitSettings()
            XUiManager.TipText("EquipOneClickAutoSettingSaved")
            self:Close()
            return
        end
    end

    XUiManager.TipText("EquipOneClickAutoSettingNoChange")
 end

function XUiEquipOneClickAutoCommonSetting:OnBtnWeaponLevelClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponLevel] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponLevel]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnWeaponResonanceClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponResonance] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponResonance]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnWeaponOverrunClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponOverrun] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.WeaponOverrun]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnAwarenessLevelClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessLevel] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessLevel]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnAwarenessResnanceClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessResonance] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessResonance]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnAwarenessOverclockingClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessOverclocking] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.AwarenessOverclocking]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnPartnerLevelClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerLevel] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerLevel]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnPartnerQualityClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerQuality] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerQuality]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnBtnPartnerSkillClick()
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerSkill] = not self._SettingDic[XEquipEnum.OneClickAutoSettingType.PartnerSkill]
    self:_Refresh()
end

function XUiEquipOneClickAutoCommonSetting:OnToggleComfirmSettingValueChanged(value)
    local XEquipEnum = XMVCA.XEquip.Enum
    self._SettingDic[XEquipEnum.OneClickAutoSettingType.ConfirmSetting] = value
    self:_Refresh()
end

---endregion

---region event

---endregion

function XUiEquipOneClickAutoCommonSetting:_InitSettingDic()
    local XEquipEnum = XMVCA.XEquip.Enum
    local settingControl = self._Control.OneClickAutoSettingControl
    self._SettingDic = {}
    for _, settingType in ipairs(XEquipEnum.OneClickAutoSettingGlobalTypeList) do
        self._SettingDic[settingType] = settingControl:GetSetting(settingType)
    end
end

function XUiEquipOneClickAutoCommonSetting:_SubmitSettings()
    local XEquipEnum = XMVCA.XEquip.Enum
    local settingControl = self._Control.OneClickAutoSettingControl
    for _, settingType in ipairs(XEquipEnum.OneClickAutoSettingGlobalTypeList) do
        settingControl:SetSetting(settingType, self._SettingDic[settingType])
    end
end

function XUiEquipOneClickAutoCommonSetting:_Refresh()
    local XEquipEnum = XMVCA.XEquip.Enum
    local dic = self._SettingDic

    local function GetState(settingType)
        return dic[settingType] and CS.UiButtonState.Select or CS.UiButtonState.Normal
    end

    self.BtnWeaponLevel:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.WeaponLevel))
    self.BtnWeaponResonance:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.WeaponResonance))
    self.BtnWeaponOverrun:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.WeaponOverrun))
    self.BtnAwarenessLevel:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.AwarenessLevel))
    self.BtnAwarenessResnance:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.AwarenessResonance))
    self.BtnAwarenessOverclocking:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.AwarenessOverclocking))
    self.BtnPartnerLevel:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.PartnerLevel))
    self.BtnPartnerQuality:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.PartnerQuality))
    self.BtnPartnerSkill:SetButtonState(GetState(XEquipEnum.OneClickAutoSettingType.PartnerSkill))
    self.ToggleComfirmSetting.isOn = dic[XEquipEnum.OneClickAutoSettingType.ConfirmSetting] or false
end

return XUiEquipOneClickAutoCommonSetting
