---@class XMusicPlayerEventId 
local XMusicPlayerEventId = {
    EVENT_VIEW_CALL_SWITCH_STATE = "EVENT_VIEW_CALL_SWITCH_STATE",
    EVENT_VIEW_WILL_UPDATE_STATE = "EVENT_VIEW_WILL_UPDATE_STATE",
    EVENT_VIEW_UPDATE_STATE = "EVENT_VIEW_UPDATE_STATE",
    
    EVENT_VIEW_MUSIC_LIST_MANAGER_STATE_CHANGE = "EVENT_VIEW_MUSIC_LIST_MANAGER_STATE_CHANGE",

    EVENT_VIEW_CONSOLE_BTN_CLICK = "EVENT_VIEW_CONSOLE_BTN_CLICK",
    EVENT_VIEW_CALL_JUMP_PLAYLIST = "EVENT_VIEW_CALL_JUMP_PLAYLIST",

    EVENT_VIEW_ZHEN_ENABLE_COMPLETE = "EVENT_VIEW_ZHEN_ENABLE_COMPLETE",
    EVENT_VIEW_ZHEN_DISABLE_COMPLETE = "EVENT_VIEW_ZHEN_DISABLE_COMPLETE",

    EVENT_VIEW_PLAY_SFX = "EVENT_VIEW_PLAY_SFX",

    
    EVENT_MUSICLIST_UPDATE = "EVENT_MUSICLIST_UPDATE",
    EVENT_NORMAL_MUSICLIST_SORT_CHANGE = "EVENT_NORMAL_MUSICLIST_SORT_CHANGE",
    EVENT_PLAYER_MUSIC_CHANGE = "EVENT_PLAYER_MUSIC_CHANGE",
    EVENT_PLAYER_PLAY_STATE_CHANGE = "EVENT_PLAYER_PLAY_STATE_CHANGE",
    EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE = "EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE",
    EVENT_CHANGE_UI_COLOR_STYLE = "EVENT_CHANGE_UI_COLOR_STYLE",
    EVENT_COLOR_MATERIAL_LOADED = "EVENT_COLOR_MATERIAL_LOADED",

    EVENT_REPLY_MUISC_REMOVE_FROM_LIST = "EVENT_REPLY_MUISC_REMOVE_FROM_LIST",
    EVENT_REPLY_BGM_ADD_TO_LIST      = "EVENT_REPLY_BGM_ADD_TO_LIST",
    EVENT_REPLY_BGMMUSIC_INDEX_CHANGE   = "EVENT_REPLY_BGMMUSIC_INDEX_CHANGE",
    EVENT_REPLY_BGMLIST_RESET           = "EVENT_REPLY_BGMLIST_RESET",
    EVENT_REPLY_LIKE_ALL_SET_BGM        = "EVENT_REPLY_LIKE_ALL_SET_BGM",
}

return XMusicPlayerEventId