--[[
-- XUiPBRShopNew.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:36
--]]

local XUiPBRShopNewPanelRound = require("XUi/XUiPBRGame/XUiPBRShopNew/RoundPanel/XUiPBRShopNewPanelRound")
local XUiPBRShopNewPanelItem = require("XUi/XUiPBRGame/XUiPBRShopNew/GoodsPanel/XUiPBRShopNewPanelItem")
local XUiPBRShopNewBtnCharacter = require("XUi/XUiPBRGame/XUiPBRShopNew/CharacterInfo/XUiPBRShopNewBtnCharacter")
local XUiPBRShopNewPanelSkill = require("XUi/XUiPBRGame/XUiPBRShopNew/CharacterInfo/XUiPBRShopNewPanelSkill")
local XUiPBRShopNewPanelProp = require("XUi/XUiPBRGame/XUiPBRShopNew/CharacterInfo/XUiPBRShopNewPanelProp")
local XUiPBRShopNewUiPBRPanelDetail = require("XUi/XUiPBRGame/XUiPBRShopNew/ItemDetailPopupPanel/XUiPBRShopNewUiPBRPanelDetail")
local XUiPBRShopNewUiPBRPanelAttribute = require("XUi/XUiPBRGame/XUiPBRShopNew/CharacterInfo/XUiPBRShopNewUiPBRPanelAttribute")

---@class XUiPBRShopNew : XLuaUi
---@field _Control XPBRGameControl
--- 以下面板节点为 prefab 原始节点，在 InitComponents / OnStart 中被包装为对应子 UI 类
---@field PanelItem XUiPBRShopNewPanelItem 商品列表面板（展示在售商品）
---@field PanelSkill XUiPBRShopNewPanelSkill 已拥有技能列表
---@field PanelProp XUiPBRShopNewPanelProp 已拥有道具列表
---@field PanelRound XUiPBRShopNewPanelRound 波次进度面板
---@field UiPBRPanelDetail XUiPBRShopNewUiPBRPanelDetail 商品详情弹窗
---@field UiPBRPanelAttribute XUiPBRShopNewUiPBRPanelAttribute 角色属性详情面板
---@field BtnCharacter XUiPBRShopNewBtnCharacter 角色信息按钮（prefab 按钮节点，包装为子 UI 类）
--- 以下为 prefab 自动注入的按钮与文本节点
---@field BtnExit XUiComponent.XUiButton 退出商店
---@field BtnRefresh XUiComponent.XUiButton 刷新商品（按钮名展示剩余刷新次数）
---@field BtnGiveup XUiComponent.XUiButton 放弃本次选择 / 进入下一波
---@field BtnMusic XUiComponent.XUiButton 选择 BGM（仅无尽模式显示）
---@field TxtSelectNum UnityEngine.UI.Text 剩余强化（选择）次数文本
local XUiPBRShopNew = XLuaUiManager.Register(XLuaUi, "UiPBRShopNew")

local XInputSignalMediator = require('XModule/XPBRGame/Entity/XInputSignalMediator')
local XUiGridMusicOptionEntrance = require("XUi/XUiPBRGame/CommonUiTemplate/XUiGridMusicOptionEntrance")

function XUiPBRShopNew:OnAwake()
    self:InitComponents()
end

function XUiPBRShopNew:InitComponents()
    self.UiPBRPanelDetail.gameObject:SetActiveEx(false)
    
    ---@type XInputSignalMediator
    self.InputSignalMediator = XInputSignalMediator.New(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop)
    self.InputSignalMediator:RegisterSignalHandler(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.Exit, handler(self, self.OnBtnExitSignal))
    self.InputSignalMediator:RegisterSignalHandler(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.GoNextWave, handler(self, self.OnBtnGoSignal))
    self.InputSignalMediator:RegisterSignalHandler(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.RefreshGoods, handler(self, self.OnBtnRefreshSignal))
    self.InputSignalMediator:RegisterSignalHandler(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.SelectGoods, handler(self, self.OnSelectItemSignal))
    self.InputSignalMediator:RegisterSignalHandler(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.BGMSelect, handler(self, self.OnBtnMusicClickSignal))
    
    
    -- Button
    self.BtnExit:AddEventListener(function() 
        self.InputSignalMediator:ReceiveInputSignal(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.Exit) 
    end)

    self.BtnRefresh:AddEventListener(function()
        self.InputSignalMediator:ReceiveInputSignal(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.RefreshGoods)
    end)
    
    self.BtnGiveup:AddEventListener(function()
        self.InputSignalMediator:ReceiveInputSignal(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.GoNextWave)
    end)
    
    self.BtnCharacter:AddEventListener(function() self:OnBtnCharacterClick() end)

    if self.BtnMusic then
        ---@type XUiGridMusicOptionEntrance
        self.UiGridMusic = XUiGridMusicOptionEntrance.New(self.BtnMusic, self)
        self.UiGridMusic:AddEventListener(function()
            self.InputSignalMediator:ReceiveInputSignal(XMVCA.XPBRGame.EnumConst.UIInputTypes.UIShop.BGMSelect)
        end)
    end

    -- XUiNode
    
    ---@type XUiPBRShopNewPanelItem
    self.PanelItem = XUiPBRShopNewPanelItem.New(self.PanelItem, self)
    ---@type XUiPBRShopNewBtnCharacter
    self.BtnCharacter = XUiPBRShopNewBtnCharacter.New(self.BtnCharacter, self)
    ---@type XUiPBRShopNewPanelSkill
    self.PanelSkill = XUiPBRShopNewPanelSkill.New(self.PanelSkill, self)
    ---@type XUiPBRShopNewPanelProp
    self.PanelProp = XUiPBRShopNewPanelProp.New(self.PanelProp, self)
    ---@type XUiPBRShopNewUiPBRPanelDetail
    self.UiPBRPanelDetail = XUiPBRShopNewUiPBRPanelDetail.New(self.UiPBRPanelDetail, self)
end


---@param stageId number
function XUiPBRShopNew:OnStart(stageId)
    self.StageId = stageId
    ---@type PbrSegmentSettleData
    self.SettleData = self._Control.InGameControl:GetSegmentSettleData()
    ---@type PbrAdventureShopData
    self.ShopData = self.SettleData and self.SettleData.ShopData or nil

    self.UiPBRPanelAttribute.gameObject:SetActiveEx(false)
    ---@type XUiPBRShopNewUiPBRPanelAttribute
    self.UiPBRPanelAttribute = XUiPBRShopNewUiPBRPanelAttribute.New(self.UiPBRPanelAttribute, self, self.SettleData.CharacterId)
    
    self:InitWavesShow()
    
    self:RefreshAll()

    if self.UiGridMusic then
        self.UiGridMusic:SetVisible(self._Control.InGameControl:CheckIsInEndlessMode())
    end

    self:_PlaySelectedBgm()
end

function XUiPBRShopNew:OnEnable()
    self.InputSignalMediator:StartInputSignalUpdateTimer()

    self._Control:AddEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_ITEM_DETAIL, self.OnItemDetailOpenEvent, self)
    self._Control:AddEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_MUSIC_POPUP_CLOSED, self._OnMusicPopupClosed, self)

    if self.UiGridMusic then
        self.UiGridMusic:RefreshBgmName(self.StageId)
    end
end

function XUiPBRShopNew:OnDisable()
    self.InputSignalMediator:StopInputSignalUpdateTimer()

    self._Control:RemoveEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_ITEM_DETAIL, self.OnItemDetailOpenEvent, self)
    self._Control:RemoveEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_MUSIC_POPUP_CLOSED, self._OnMusicPopupClosed, self)
end

function XUiPBRShopNew:OnDestroy()
    self:_StopSelectedBgm()
end

function XUiPBRShopNew:InitWavesShow()
    -- 初始化波次进度显示，因为在商店中波次进度不会变化，所以只需要初始化一次    
    ---@type XUiPBRShopNewPanelRound
    self.PanelRound = XUiPBRShopNewPanelRound.New(self.PanelRound, self, self.StageId, self._Control.InGameControl:GetWaveInSegmentSettleData())
    self.PanelRound:RefreshWavesShow()
end

function XUiPBRShopNew:RefreshAll()
    self:RefreshCharacterInfo()
    self:RefreshShopShow()
end

function XUiPBRShopNew:RefreshShopShow()
    -- 强化次数、刷新次数显示
    local selectTimes, maxSelectTimes = self._Control.InGameControl:GetShopSelectCount()
    
    local refreshTimes, maxRefreshTimes = self._Control.InGameControl:GetShopRefreshCount()
    
    self.BtnRefresh:SetNameByGroup(0, XUiHelper.FormatTextEx(self._Control:GetClientPBRText('ShopRefreshTimesDesc'), refreshTimes, maxRefreshTimes))
    
    self.TxtSelectNum.text = XUiHelper.FormatTextEx(self._Control:GetClientPBRText('ShopSelectGoodsTimesDesc'), selectTimes, maxSelectTimes)
    -- 刷新商品道具显示
    
    local itemIds = self._Control.InGameControl:GetShopSellItemIds()

    self.PanelItem:RefreshGoodsShow(itemIds)
    
    -- 刷新了商品后需要手动检查引导
    XDataCenter.GuideManager.CheckGuideOpen()
end

function XUiPBRShopNew:RefreshCharacterInfo()
    -- 刷新道具显示
    local itemDict = self._Control.InGameControl:GetOwnedItemIdsByType()

    -- 分别展示道具和技能列表
    self.PanelSkill:RefreshItemShow(itemDict[XMVCA.XPBRGame.EnumConst.ItemType.Skill])
    self.PanelProp:RefreshItemShow(itemDict[XMVCA.XPBRGame.EnumConst.ItemType.Other])
    
    -- 刷新角色信息
    self.BtnCharacter:RefreshShow(self.SettleData.CharacterId, self.SettleData.CharacterLevel)
end

function XUiPBRShopNew:OnBtnCharacterClick(eventData)
    -- 打开角色详情界面
    self.UiPBRPanelAttribute:Open()
end

function XUiPBRShopNew:OnItemDetailOpenEvent(posUi, itemId)
    self.UiPBRPanelDetail:Open()
    self.UiPBRPanelDetail:RefreshItemShow(posUi, itemId)
end

function XUiPBRShopNew:_GetHintInfo()
    if self._HintInfo == nil then
        ---@type XUiPBRPopupComTipsExtraData
        self._HintInfo = {
            IsShowHint = true,
            HintContent = self._Control:GetClientPBRText('ShopDialogHintDesc'),
            HintStatus = self._Control.InGameControl:GetIsShopSelectGiveupIgnorePopup(),
            HintStatusChangedCb = function(status)
                if self._Control and self._Control.InGameControl then
                    self._Control.InGameControl:SetShopSelectGiveupIgnorePopup(status) 
                end
            end
        }
    else
        -- 只更新状态 
        self._HintInfo.HintStatus = self._Control.InGameControl:GetIsShopSelectGiveupIgnorePopup()
    end
    
    return self._HintInfo
end

--region 输入信号处理

--- 信号处理：退出界面
function XUiPBRShopNew:OnBtnExitSignal()
    self:_OnShopExit()
end

--- 信号处理：放弃当次选择
function XUiPBRShopNew:OnBtnGoSignal()
    -- 判断强化次数是否用完
    if self._Control.InGameControl:GetIsShopHasChooseTimes() then
        local leftTimes = self._Control.InGameControl:GetShopLeftSelectCount()

        local hintInfo = self:_GetHintInfo()
        
        if leftTimes > 1 then
            if not hintInfo.HintStatus then
                XMVCA.XPBRGame:OpenCommonTips(self._Control:GetClientPBRText('ShopGiveUpWithMultyChooseTime'), nil, nil, function()
                    self:_DoShopFresh(true)
                end, hintInfo)
            else
                self:_DoShopFresh(true)
            end
        else
            if not hintInfo.HintStatus then
                XMVCA.XPBRGame:OpenCommonTips(self._Control:GetClientPBRText('ShopGiveUpWithLastChooseTime'), nil, nil, function()
                    self:_DoNextWave()
                end, hintInfo)
            else
                self:_DoNextWave()
            end
        end
    else
        self:_DoNextWave()
    end
    
end

function XUiPBRShopNew:_DoShopFresh(isGiveUpChoose)
    XMVCA.XPBRGame.NetworkAgency:DoPbrShopFreshRequest(function(success)
        if success then
            -- 刷新商店显示
            self.ShopData = self._Control.InGameControl:GetShopData()
            self:RefreshShopShow()
            -- 主要是检查技能升级显示
            self:RefreshCharacterInfo()

            XUiManager.TipMsg(self._Control:GetClientPBRText('ShopFreshSuccessTips'))
        end
    end, isGiveUpChoose)
end

function XUiPBRShopNew:_DoNextWave()
    -- 清空商店数据
    self._Control.InGameControl:ClearShopData()
    self._Control:SetCurSelectCharId(self.SettleData.CharacterId)
    XMVCA.XFuben:EnterFightByStageId(self.StageId, nil, false, 1, nil)
    self:Close()
end

--- 信号处理：刷新商品
function XUiPBRShopNew:OnBtnRefreshSignal()
    self:_DoShopFresh(false)
end

--- 信号处理：选择商品
function XUiPBRShopNew:OnSelectItemSignal(itemId)
    self._Control.InGameControl:TrySelectItem(itemId, function(success)
        if success then
            -- 刷新商店显示
            self.ShopData = self._Control.InGameControl:GetShopData()
            
            -- 检查剩余次数
            local leftTimes = self._Control.InGameControl:GetShopLeftSelectCount()

            if leftTimes > 0 then
                self:RefreshAll()

                XUiManager.TipMsg(self._Control:GetClientPBRText('ShopSelectItemSuccessTips'))
            else
                XUiManager.TipMsg(self._Control:GetClientPBRText('ShopSelectItemSuccessTips'))
                -- 直接进入下一波
                self:_DoNextWave()
            end
            
        end
    end)
end

function XUiPBRShopNew:OnBtnMusicClickSignal()
    XLuaUiManager.Open("UiPBRPopupMusicChoose", self.StageId)
end
--endregion

--region 退出界面流程相关子逻辑

function XUiPBRShopNew:_OnShopExit()
    -- 打开二级弹窗
    local content, btnLeftText, btnRightText = self._Control:GetClientBattleShopBackTips()
    
    XMVCA.XPBRGame:OpenCommonTips(content, nil, handler(self, self._OnShopExitTipsSettle), handler(self, self._OnShopExitTipsOnlyExit), {
        BtnLeftText = btnLeftText,
        BtnRightText = btnRightText
    })
end

--- 走提前结算流程
function XUiPBRShopNew:_OnShopExitTipsSettle()
    local confirmCb = function()
        XMVCA.XPBRGame.NetworkAgency:DoPbrForceSettleRequest(function(success)
            if success then
                XLuaUiManager.SafeClose("UiPBRShopNew")
                XMVCA.XPBRGame:DoSafeFightExit()
            end
        end)
    end
    
    if self._Control.InGameControl:CheckIsInEndlessMode() then
        -- 无尽模式无需二次确认
        confirmCb()
    else
        XMVCA.XPBRGame:OpenCommonTips(self._Control:GetClientPBRText('BattleSettleByHandTips'), nil, nil, confirmCb)
    end
end

--- 纯退出逻辑
function XUiPBRShopNew:_OnShopExitTipsOnlyExit()
    if XMVCA.XPBRGame:DoSafeFightExit() then
        -- 隔一帧
        -- 加遮罩防止退出期间点击
        XLuaUiManager.SetMask(true)
        self:_AddTimerId(XScheduleManager.ScheduleNextFrame(function()
            XLuaUiManager.CloseAllUpperUi('UiPBRMain')
            XLuaUiManager.SetMask(false)
        end))
    else
        XLuaUiManager.CloseAllUpperUi('UiPBRMain')
    end
end

--endregion

--region BGM

function XUiPBRShopNew:_PlaySelectedBgm()
    local bgmId = self._Control.MusicControl:GetSelectedBgmIdByStageId(self.StageId)
    if bgmId then
        self._Control.MusicControl:PlayBgmIfNotCurrent(bgmId)
    end
end

function XUiPBRShopNew:_StopSelectedBgm()
    self._Control.MusicControl:StopPreview()
end

function XUiPBRShopNew:_OnMusicPopupClosed()
    self:_PlaySelectedBgm()

    if self.UiGridMusic then
        self.UiGridMusic:RefreshBgmName(self.StageId)
    end
end

--endregion

return XUiPBRShopNew
