--[[
-- XUiMusicPlayerCDView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-01 20:02:28
--]]

---@class XUiMusicPlayerMainPanelCDView : XUiNode
---@field _Control XMusicPlayerControl
---@field BtnBgmList XUiComponent.XUiButton
---@field BtnLikeList XUiComponent.XUiButton
---@field BtnImmerseMode XUiComponent.XUiButton
---@field GoPanelLeft UnityEngine.RectTransform
---@field GoCDListRoot UnityEngine.RectTransform
---@field GoSongTitle UnityEngine.RectTransform
---@field TxtMusicName UnityEngine.UI.Text
---@field TxtComposer UnityEngine.UI.Text
---@field BtnMusicFullInfo XUiComponent.XUiButton
---@field BtnEgg XUiComponent.XUiButton
---@field TxtEggTip UnityEngine.UI.Text
---@field ImgColorInBgmList  UnityEngine.UI.Image
---@field GoGridCdCell UnityEngine.RectTransform
---@field GoCdDynamicCdList UnityEngine.RectTransform
---@field GoEggTip UnityEngine.RectTransform
local XUiMusicPlayerCDView = XClass(XUiNode, "XUiMusicPlayerCDView")
function XUiMusicPlayerCDView:InitComponents()
    -- Button
    self.BtnBgmList:AddEventListener(function() self:OnBtnBgmListClick() end)
    self.BtnLikeList:AddEventListener(function() self:OnBtnLikeListClick() end)
    self.BtnImmerseMode:AddEventListener(function() self:OnBtnImmerseModeClick() end)
    self.BtnMusicFullInfo:AddEventListener(function() self:OnBtnMusicFullInfoClick() end)
    self.BtnEgg:AddEventListener(function() self:OnBtnEggClick() end)

    -- CD滚动列表
    local XDynamicTableCurve = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableCurve")
    local XUiMusicPlayerCDPlayCellView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUiMusicPlayerCDPlayCellView")
    self._CDListTable = XDynamicTableCurve.New(self.GoCdDynamicCdList.gameObject)
    self._CDListTable:SetProxy(XUiMusicPlayerCDPlayCellView, self)
    self._CDListTable:SetDelegate(self)
    self.GoGridCdCell.gameObject:SetActive(false)

    local XUiTextScrolling = require("XUi/XUiTaikoMaster/XUiTaikoMasterFlowText")
    self._MusicNameScrolling = XUiTextScrolling.New(self.TxtMusicName, self.TxtMusicName.transform.parent)
    self._MusicNameScrolling:Stop()
end

function XUiMusicPlayerCDView:OnStart(...)
    self:InitComponents()
end

function XUiMusicPlayerCDView:OnEnable()
    self:_SetEvent(true)
    self:_OnUIColorStyleChange()
    self._CurCDShowMusicID = self._Control:GetCDPlayerControl():GetCurPlayingMusicID()
    self:_RefreshAll()
end

function XUiMusicPlayerCDView:OnDisable()
    self:_SetEvent(false)
end

function XUiMusicPlayerCDView:OnDestroy()
end

---region ui event
function XUiMusicPlayerCDView:OnBtnBgmListClick(eventData)
    local curMusiyID = self._Control:GetCDPlayerControl():GetCurPlayingMusicCO().Id

    local musicListControl = self._Control:GetMusicmusicListControl()
    if musicListControl:CheckMusicIsInListByListType(XMVCA.XMusicPlayer.Enum.MusicListType.BGM,curMusiyID) then
        self._Control:GetMusicPlayerNetWorkControl():SendRemoveBgmMusicRequest(curMusiyID)
    else
        self._Control:GetMusicPlayerNetWorkControl():SendAddBGMMusicRequest(curMusiyID)
    end
end

function XUiMusicPlayerCDView:OnBtnLikeListClick(eventData)
    local curMusicID = self._Control:GetCDPlayerControl():GetCurPlayingMusicCO().Id 

    local musicListControl = self._Control:GetMusicmusicListControl()
    if musicListControl:CheckMusicIsInListByListType(XMVCA.XMusicPlayer.Enum.MusicListType.Favorite,curMusicID) then
        self._Control:GetMusicPlayerNetWorkControl():SendRemoveLikeMusicRequest(curMusicID)
    else
        self._Control:GetMusicPlayerNetWorkControl():SendAddLikeMusicRequest(curMusicID)
    end
end

function XUiMusicPlayerCDView:OnBtnImmerseModeClick(eventData)
    local curStatus = self.Parent:GetMusicPlayerUIStatus()
    local MusicMainUIStatus = XMVCA.XMusicPlayer.Enum.MusicMainUIStatus
    if curStatus == MusicMainUIStatus.immerse then
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE,MusicMainUIStatus.mainCD)
    else
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE,MusicMainUIStatus.immerse)
    end
end

function XUiMusicPlayerCDView:OnBtnMusicFullInfoClick(eventData)
    XLuaUiManager.Open("UiCdPlayerMusicDetailPopup", self._CurCDShowMusicID)
end

function XUiMusicPlayerCDView:OnBtnEggClick(eventData)
    self.GoEggTip.gameObject:SetActive(not self.GoEggTip.gameObject.activeSelf)
end
---endregion

---region event
function XUiMusicPlayerCDView:_SetEvent(flag)
    if flag then
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_MUSICLIST_UPDATE,self._OnMusicListUpdate,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._OnMusicListTypeChange,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_UPDATE_STATE,self._OnMainViewStatusChange,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_PLAYER_MUSIC_CHANGE,self._OnCurPlayMusicChange,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CHANGE_UI_COLOR_STYLE,self._OnUIColorStyleChange,self)
    else
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_MUSICLIST_UPDATE,self._OnMusicListUpdate,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._OnMusicListTypeChange,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_UPDATE_STATE,self._OnMainViewStatusChange,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_PLAYER_MUSIC_CHANGE,self._OnCurPlayMusicChange,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CHANGE_UI_COLOR_STYLE,self._OnUIColorStyleChange,self)
    end
end

function XUiMusicPlayerCDView:_OnMusicListUpdate()
    self:_RefreshAll() 
end

function XUiMusicPlayerCDView:_OnMusicListTypeChange()
    self:_RefreshAll()
end

function XUiMusicPlayerCDView:_OnCurPlayMusicChange(direction)
    self._CurCDShowMusicID = self._Control:GetCDPlayerControl():GetCurPlayingMusicID()
    self:_RefreshCDByMusicID(self._CurCDShowMusicID)

    local cdControl = self._Control:GetCDPlayerControl()
    local rawList = cdControl:GetCurRawMusicIdList()
    local totalCount = #rawList
    local target = (table.indexof(rawList, self._CurCDShowMusicID) or 1) - 1
    local rawCur = self._CDListTable.Imp.StartIndex
    local diff = 0
    if totalCount > 0 then
        local cur = rawCur % totalCount
        local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
        if direction == XMusicPlayerEnum.MusicSwitchDirection.Next then
            -- 正向: diff 始终为正,往前进
            diff = (target - cur) % totalCount
            if diff == 0 then diff = totalCount end
        elseif direction == XMusicPlayerEnum.MusicSwitchDirection.Prev then
            -- 反向: 算后退距离,用 rawCur - backwardDist 往回退
            local backwardDist = (cur - target) % totalCount
            if backwardDist == 0 then backwardDist = totalCount end
            diff = -backwardDist
        else
            -- Jump: 最短路径
            diff = (target - cur) % totalCount
            if diff > totalCount / 2 then
                diff = diff - totalCount
            end
        end
    end
    if self._CDListTable.Imp.MoveType == CS.XDynamicTableCurve.MovementType.Clamped then
        -- Clamped 模式不支持虚拟索引，直接定位到实际下标
        self._CDListTable:TweenToIndex(target)
    else
        self._CDListTable:TweenToIndex(rawCur + diff)
    end
end

---拖拽滑动切换CD: 按视图位置移动一格,能播则跳转播放,不能播则只滚动展示
---@param isNext boolean true=右滑下一首, false=左滑上一首
function XUiMusicPlayerCDView:OnCDSwipe(isNext)
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_PLAY_SFX, XMVCA.XMusicPlayer.Enum.AudioName.cdSFXSwitch)
    local cdControl = self._Control:GetCDPlayerControl()
    local rawList = cdControl:GetCurRawMusicIdList()
    local totalCount = #rawList
    if totalCount <= 0 then return end

    -- 用表格当前视觉位置算下一格,不用 CurCDShowMusicID
    local rawCur = self._CDListTable.Imp.StartIndex
    local cur = rawCur % totalCount
    local nextViewIdx
    if isNext then
        nextViewIdx = (cur + 1) % totalCount
    else
        nextViewIdx = (cur - 1 + totalCount) % totalCount
    end
    local nextIdx = nextViewIdx + 1  -- 0-based → 1-based

    local musicID = rawList[nextIdx]
    self._CurCDShowMusicID = musicID
    self:_RefreshCDByMusicID(musicID)

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local useStatus = cdControl:GetMusicUseStatusAndConditionDesc(musicID)
    -- Clamped 模式使用实际索引；Loop 模式使用虚拟索引以保持移动方向
    local targetIdx
    if self._CDListTable.Imp.MoveType == CS.XDynamicTableCurve.MovementType.Clamped then
        targetIdx = nextViewIdx
    else
        targetIdx = isNext and (rawCur + 1) or (rawCur - 1)
    end
    if useStatus ~= XMusicPlayerEnum.MusicUseStatus.unlock then
        if musicID == cdControl:GetCurPlayingMusicID() then
            -- 拖回当前正在播放的歌曲，不重复播，直接滚回去
            self._CDListTable:TweenToIndex(targetIdx)
        else
            -- 不同歌曲: 跳转播放(tween 由 _OnCurPlayMusicChange 驱动)
            cdControl:JumpPlayByMusicIDWithNotify(cdControl:GetCurMusicListType(), musicID)
        end
    else
        -- 不可播放: 只滚动到该CD展示
        self._CDListTable:TweenToIndex(targetIdx)
    end
end

function XUiMusicPlayerCDView:_OnMainViewStatusChange(lastStatus,curStatus)
    local MusicMainUIStatus = XMVCA.XMusicPlayer.Enum.MusicMainUIStatus

    if curStatus == MusicMainUIStatus.immerse or curStatus == MusicMainUIStatus.immersePro   then
        XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnImmerseMode,CS.UiButtonState.Select)
        self.GoPanelLeft.gameObject:SetActive(false)
    else
        XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnImmerseMode,CS.UiButtonState.Normal)
        self.GoPanelLeft.gameObject:SetActive(true)
    end

    self.BtnImmerseMode.gameObject:SetActive(curStatus ~= MusicMainUIStatus.immersePro)

    self:_RefreshFullInfoBtn()
end

function XUiMusicPlayerCDView:_OnUIColorStyleChange()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local spritePath = self._Control:GetCurColorUiSprite(XMusicPlayerEnum.UiSpriteKey.BgmListBtn)
    if spritePath then
        self.ImgColorInBgmList:SetSprite(spritePath)
    end
end
---endregion

function XUiMusicPlayerCDView:_RefreshAll()
    self:_RefreshCDByMusicID(self._CurCDShowMusicID)
    self:_RefreshCDList(self._CurCDShowMusicID)
end

function XUiMusicPlayerCDView:_RefreshCDByMusicID(musicID)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local cdControl = self._Control:GetCDPlayerControl()
    local musicListControl = self._Control:GetMusicmusicListControl()
    local co = self._Control:GetMusicPlayerconfigControl():GetMusicPlayerAlbumCOByid(musicID)

    local isInBGMList = musicListControl:CheckMusicIsInListByListType(XMusicPlayerEnum.MusicListType.BGM, musicID)
    local isInLickList = musicListControl:CheckMusicIsInListByListType(XMusicPlayerEnum.MusicListType.Favorite, musicID)
    XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnBgmList, isInBGMList and CS.UiButtonState.Select or CS.UiButtonState.Normal)
    XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnLikeList, isInLickList and CS.UiButtonState.Select or CS.UiButtonState.Normal)
    self.BtnImmerseMode:SetButtonState(CS.UiButtonState.Normal)

    self.TxtMusicName.text = co.Name
    self._MusicNameScrolling:Play()

    local composerBrief = co.ComposeBrief 
    if string.IsNilOrEmpty(composerBrief) then
        self.TxtComposer.text = XUiHelper.ConvertLineBreakSymbol(co.Composer) 
    else
        self.TxtComposer.text = XUiHelper.ConvertLineBreakSymbol(composerBrief)
    end
    self:_RefreshFullInfoBtn()

    self.GoEggTip.gameObject:SetActive(false)
    self.TxtEggTip.text = co.EggText
    if cdControl:NeedShowEggTag(musicID) then
        self.BtnEgg.gameObject:SetActive(true)
    else
        self.BtnEgg.gameObject:SetActive(false)
    end
end

---全量刷新CD列表(列表变更/初始化时调用)
function XUiMusicPlayerCDView:_RefreshCDList(musicID)
    local cdControl = self._Control:GetCDPlayerControl()
    local rawList = cdControl:GetCurRawMusicIdList()
    local count = #rawList
    -- 仅1首时走Clamped(不可循环滚动), 多首走Loop(无限循环)
    self._CDListTable.Imp.MoveType = count <= 2
            and CS.XDynamicTableCurve.MovementType.Clamped
            or CS.XDynamicTableCurve.MovementType.Loop
    self._CDListTable:SetDataSource(rawList)
    local index = table.indexof(rawList, musicID) or 1
    self._CDListTable:ReloadData(count > 0 and (index - 1) or -1)
end



function XUiMusicPlayerCDView:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local visualIndex = index
        index = index % self._CDListTable.Imp.TotalCount + 1
        grid:UpdateCDCellData(index, self, visualIndex)
    end
end


function XUiMusicPlayerCDView:_RefreshFullInfoBtn()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local co = self._Control:GetMusicPlayerconfigControl():GetMusicPlayerAlbumCOByid(self._CurCDShowMusicID)
    local hasBrief = co and not string.IsNilOrEmpty(co.ComposeBrief)

    local curUIStatus = self.Parent:GetMusicPlayerUIStatus()
    local isImmerse = curUIStatus == XMusicPlayerEnum.MusicMainUIStatus.immerse
        or curUIStatus == XMusicPlayerEnum.MusicMainUIStatus.immersePro

    self.BtnMusicFullInfo.gameObject:SetActive(hasBrief and not isImmerse)
end

function XUiMusicPlayerCDView:GetMusicPlayerUIStatus()
    return self.Parent:GetMusicPlayerUIStatus()
end


return XUiMusicPlayerCDView
