--[[
-- XUiMusicPlayerMusicListCellView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-04 15:18:19
--]]

---@class XUiMusicPlayerMusicListCellView : XUiNode
---@field _Control XMusicPlayerControl
---@field _musicPlayerconfigControl XMusicPlayerConfigControl
--
---@field GridAlbum UiObject
---@field GoNotSelectRoot UnityEngine.RectTransform
---@field TxtMusicName UnityEngine.UI.Text
---@field GoLimitInfo UnityEngine.RectTransform
---@field TxtLimitedTime UnityEngine.UI.Text
---@field TxtAuthorName UnityEngine.UI.Text
---@field GOManageBtnLayout UnityEngine.RectTransform
---@field BtnLike XUiComponent.XUiButton
---@field BtnBgm XUiComponent.XUiButton
---@field BtnUp XUiComponent.XUiButton
---@field BtnDown XUiComponent.XUiButton
---@field GoUnLockText UnityEngine.UI.Text
---@field BtnCurCell XUiComponent.XUiButton
---@field GOSelectedBg  UnityEngine.RectTransform
---@field TxtSelectLock UnityEngine.UI.Text
---@field GoAlbumNotSelect  UnityEngine.RectTransform
---@field GoAlbumSelect  UnityEngine.RectTransform
---@field GoAlbumSelectLock  UnityEngine.RectTransform
---@field RImgAlbum1  UnityEngine.RawImage
---@field RImgAlbum2  UnityEngine.RawImage
---@field RImgAlbum3  UnityEngine.RawImage
---@field GoEgg UnityEngine.RectTransform
---@field ImgColorSelectedBg UnityEngine.UI.Image
---@field ImgColorBgmBtn UnityEngine.UI.Image
---@field ImgNoSelectBg UnityEngine.UI.Image
---@field RImgMusicCurve UnityEngine.RawImage
---@field RImgMusicCurve4 UnityEngine.RawImage
local XUiMusicPlayerMusicListCellView = XClass(XUiNode, "XUiMusicPlayerMusicListCellView")

function XUiMusicPlayerMusicListCellView:InitComponents()
    -- Button
    self.BtnLike:AddEventListener(function() self:OnBtnLikeClick() end)
    self.BtnBgm:AddEventListener(function() self:OnBtnBgmClick() end)
    self.BtnUp:AddEventListener(function() self:OnBtnUpClick() end)
    self.BtnDown:AddEventListener(function() self:OnBtnDownClick() end)
    self.BtnCurCell:AddEventListener(function() self:OnBtnCurCellClick() end)
end

function XUiMusicPlayerMusicListCellView:OnStart(...)
    self._MusicPlayerConfig = self._Control:GetMusicPlayerconfigControl()
    self:InitComponents()
end

function XUiMusicPlayerMusicListCellView:OnEnable()
    self._MusicID = nil
    self:_SetEvent(true)
end

function XUiMusicPlayerMusicListCellView:OnDisable()
    self._MusicID = nil
    self:_SetEvent(false)
end

function XUiMusicPlayerMusicListCellView:OnDestroy()
end

---region ui event
function XUiMusicPlayerMusicListCellView:OnBtnLikeClick(eventData)
    local musicID = self._MusicID
    local MusicListType = XMVCA.XMusicPlayer.Enum.MusicListType
    local musicListControl = self._Control:GetMusicmusicListControl()
    local isFavorite = musicListControl:CheckMusicIsInListByListType(MusicListType.Favorite,musicID)
    if isFavorite then
        self._Control:GetMusicPlayerNetWorkControl():SendRemoveLikeMusicRequest(self._MusicID)
    else
        self._Control:GetMusicPlayerNetWorkControl():SendAddLikeMusicRequest(self._MusicID)
    end
end

function XUiMusicPlayerMusicListCellView:OnBtnBgmClick(eventData)
    local musicID = self._MusicID

    local MusicListType = XMVCA.XMusicPlayer.Enum.MusicListType
    local musicListControl = self._Control:GetMusicmusicListControl()
    local isBGM = musicListControl:CheckMusicIsInListByListType(MusicListType.BGM,musicID)
    if isBGM then
        self._Control:GetMusicPlayerNetWorkControl():SendRemoveBgmMusicRequest(musicID)
    else
        self._Control:GetMusicPlayerNetWorkControl():SendAddBGMMusicRequest(musicID)
    end
end

function XUiMusicPlayerMusicListCellView:OnBtnUpClick(eventData)
    self._Control:GetMusicPlayerNetWorkControl():SendBgmMusicIndexChangeRequest(self._Index,true)
end

function XUiMusicPlayerMusicListCellView:OnBtnDownClick(eventData)
    self._Control:GetMusicPlayerNetWorkControl():SendBgmMusicIndexChangeRequest(self._Index,false)
end

function XUiMusicPlayerMusicListCellView:OnBtnCurCellClick(eventData)
    local cdControl = self._Control:GetCDPlayerControl()
    local useStatus, conditionDesc = cdControl:GetMusicUseStatusAndConditionDesc(self._MusicID)
    local XMusicPlayerEnum  = XMVCA.XMusicPlayer.Enum
    if useStatus == XMusicPlayerEnum.MusicUseStatus.unlock then
        XUiManager.TipError(conditionDesc)
        return
    end

    local status, listType = self:_GetMusicListViewStatusAndType()
    if status == XMusicPlayerEnum.MusicListUIStatus.manager then
        return
    end
    cdControl:JumpPlayByMusicIDWithNotify(listType, self._MusicID)
end
---endregion

---region event
function XUiMusicPlayerMusicListCellView:_SetEvent(flag)
    if flag then
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_MUSICLIST_UPDATE,self._Refreash,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_PLAYER_MUSIC_CHANGE,self._Refreash,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._Refreash,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_MUSIC_LIST_MANAGER_STATE_CHANGE,self._Refreash,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CHANGE_UI_COLOR_STYLE,self._OnUIColorStyleChange,self)
        self._Control:AddEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_COLOR_MATERIAL_LOADED,self._OnColorMaterialLoaded,self)
        if not self._LimitTimeTimerId then
            self._LimitTimeTimerId = XScheduleManager.ScheduleForever(function()
                self:_RefreshLimitTime()
            end, 1000, 0)
        end
    else
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_MUSICLIST_UPDATE,self._Refreash,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_PLAYER_MUSIC_CHANGE,self._Refreash,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CURRENT_PLAY_MUSICLISTTYPE_CHANGE,self._Refreash,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_MUSIC_LIST_MANAGER_STATE_CHANGE,self._Refreash,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_CHANGE_UI_COLOR_STYLE,self._OnUIColorStyleChange,self)
        self._Control:RemoveEventListener(XMVCA.XMusicPlayer.EventIds.EVENT_COLOR_MATERIAL_LOADED,self._OnColorMaterialLoaded,self)

        if self._LimitTimeTimerId then
            XScheduleManager.UnSchedule(self._LimitTimeTimerId)
            self._LimitTimeTimerId = nil
        end
    end
end

function XUiMusicPlayerMusicListCellView:_OnUIColorStyleChange()
    self:_refreshColorFX()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local selectedBgPath = self._Control:GetCurColorUiSprite(XMusicPlayerEnum.UiSpriteKey.ListCellSelectedBg)
    if selectedBgPath then
        self.ImgColorSelectedBg:SetSprite(selectedBgPath)
    end
    local bgmBtnPath = self._Control:GetCurColorUiSprite(XMusicPlayerEnum.UiSpriteKey.BgmListBtn)
    if bgmBtnPath then
        self.ImgColorBgmBtn:SetSprite(bgmBtnPath)
    end
end

function XUiMusicPlayerMusicListCellView:_OnColorMaterialLoaded()
    self:_refreshColorFX()
end
---endregion

function XUiMusicPlayerMusicListCellView:UpdateXMusicListCellData(index,musiclistView)
    self._MusicListView = musiclistView
    self._Index = index
    self._MusicID = self._MusicListView:GetMusicIdByIndex(index)

    self:_Refreash()
end

function XUiMusicPlayerMusicListCellView:_Refreash()
    local musicID = self._MusicID

    self:_OnUIColorStyleChange()

    local musicCO = self._MusicPlayerConfig:GetMusicPlayerAlbumCOByid(musicID)
    self.TxtMusicName.text =  musicCO.Name
    local hasBrief = not string.IsNilOrEmpty(musicCO.ComposeBrief)
    self.TxtAuthorName.text = XUiHelper.ConvertLineBreakSymbol(hasBrief and musicCO.ComposeBrief or musicCO.Composer)
    
    local coverPath = musicCO.Cover
    self.RImgAlbum1:SetRawImage(coverPath) 
    self.RImgAlbum2:SetRawImage(coverPath) 
    self.RImgAlbum3:SetRawImage(coverPath) 

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local cdControl = self._Control:GetCDPlayerControl()
    local useStatus = cdControl:GetMusicUseStatusAndConditionDesc(musicID)
    local isUnLock    = useStatus == XMusicPlayerEnum.MusicUseStatus.unlock

    self:_RefreshLimitTime()
    self.TxtSelectLock.gameObject:SetActive(isUnLock)
    if self.GoEgg then 
        self.GoEgg.gameObject:SetActive(cdControl:NeedShowEggTag(musicID))
    end

    local musicListControl = self._Control:GetMusicmusicListControl()
    local isFavorite = musicListControl:CheckMusicIsInListByListType(XMusicPlayerEnum.MusicListType.Favorite,musicID)
    local isBGM = musicListControl:CheckMusicIsInListByListType(XMusicPlayerEnum.MusicListType.BGM,musicID)

    XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnLike, isFavorite and CS.UiButtonState.Select or CS.UiButtonState.Normal)
    XMVCA.XMusicPlayer.Util.SetBtnStatusPro(self.BtnBgm, isBGM and CS.UiButtonState.Select or CS.UiButtonState.Normal)

    local _, listType = self:_GetMusicListViewStatusAndType()
    local isCurPlay = cdControl:GetCurMusicListType() == listType
            and cdControl:GetCurPlayingMusicID() == self._MusicID

    self.GOSelectedBg.gameObject:SetActive(false)
    self.GoAlbumNotSelect.gameObject:SetActive(false)
    self.GoAlbumSelect.gameObject:SetActive(false)
    self.GoAlbumSelectLock.gameObject:SetActive(false)
    self.ImgNoSelectBg.gameObject:SetActive(not isCurPlay)
    if isUnLock then
        self.GoAlbumSelectLock.gameObject:SetActive(true)
    elseif isCurPlay then
        self.GOSelectedBg.gameObject:SetActive(true)
        self.GoAlbumSelect.gameObject:SetActive(true)
    else
        self.GoAlbumNotSelect.gameObject:SetActive(true)
    end
    -- endregion



    local status = self:_GetMusicListViewStatusAndType()
    local isManager = status == XMusicPlayerEnum.MusicListUIStatus.manager 
    self.GOManageBtnLayout.gameObject:SetActive(isManager)

    self.BtnLike.gameObject:SetActive(false)
    self.BtnBgm.gameObject:SetActive(false)
    self.BtnUp.gameObject:SetActive(false)
    self.BtnDown.gameObject:SetActive(false)
    if not isUnLock then
        if status == XMusicPlayerEnum.MusicListUIStatus.manager then
        self.BtnLike.gameObject:SetActive(true)
        self.BtnBgm.gameObject:SetActive(true)
        if listType == XMusicPlayerEnum.MusicListType.BGM then
            self.BtnUp.gameObject:SetActive(true)
            self.BtnDown.gameObject:SetActive(true)
            end
        end
    end
end

-- 刷新限免剩余时间显示(自己读取 musicID 取 CO / useStatus,1秒timer 周期性调用)
function XUiMusicPlayerMusicListCellView:_RefreshLimitTime()
    if not XTool.IsNumberValid(self._MusicID) then
        return
    end
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local musicCO = self._MusicPlayerConfig:GetMusicPlayerAlbumCOByid(self._MusicID)
    local useStatus = self._Control:GetCDPlayerControl():GetMusicUseStatusAndConditionDesc(self._MusicID)

    if useStatus == XMusicPlayerEnum.MusicUseStatus.limitedFree then
        self.GoLimitInfo.gameObject:SetActive(true)
        self.TxtLimitedTime.text = self._Control:GetCDPlayerControl():GetTimeIdLeftStr(musicCO.ExperienceTimeId)
    else
        self.GoLimitInfo.gameObject:SetActive(false)
    end
end

function XUiMusicPlayerMusicListCellView:_GetMusicListViewStatusAndType()
    return self._MusicListView:GetMusicListViewStatusAndType()
end


function XUiMusicPlayerMusicListCellView:_refreshColorFX()
    local UiMaterialKey = XMVCA.XMusicPlayer.Enum.UiMaterialKey

    local mat = self._Control:GetCurColorMat(UiMaterialKey.MusicCurve)
    if mat and self.RImgMusicCurve then
        self.RImgMusicCurve.material = mat
    end

    mat = self._Control:GetCurColorMat(UiMaterialKey.MusicCurve4)
    if mat and self.RImgMusicCurve4 then
        self.RImgMusicCurve4.material = mat
    end
end


return XUiMusicPlayerMusicListCellView
