--[[
-- XUiMusicPlayerMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-01 20:02:28
--]]

---@class XUiMusicPlayerMain : XLuaUi
---@field _Control XMusicPlayerControl
---@field BtnBack XUiComponent.XUiButton
---@field BtnBack XUiComponent.XUiButton
---@field RImgBg UnityEngine.UI.RawImage
---@field ConsoleBtnView UnityEngine.RectTransform
---@field CDView UnityEngine.RectTransform
---@field PanelCDView XUiMusicPlayerCDView
---@field MusicListView UnityEngine.RectTransform
---@field PanelMusicListView XUiMusicPlayerMainPanelMusicListView
---@field BtnShowMusicList XUiComponent.XUiButton
---@field BtnImmerseProMask XUiComponent.XUiButton
---@field AlbumCollectionView UnityEngine.RectTransform
---@field BtnHideMusicListMask XUiComponent.XUiButton
local XUiMusicPlayerMain = XLuaUiManager.Register(XLuaUi, "UiMusicPlayerMain")

-- 状态机转换阶段枚举
local TransitionPhase = {
    ExitState = 1,
    EnterState = 2,
    RecordStatusWithNotify = 3,
}


function XUiMusicPlayerMain:OnAwake()
    self._Control:GetCDPlayerControl():EnterMusicMainUI()

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local Status = XMusicPlayerEnum.MusicMainUIStatus

    self._UIShowByStatus = {
        [Status.mainCD] =  {self.BtnShowMusicList, self.BtnBack },
        [Status.musicList] = {self.BtnBack, self.BtnHideMusicListMask},
        [Status.CDListExpand] = {self.BtnBack},
        [Status.immerse] = {self.BtnImmerseProMask},
        [Status.immersePro] = {self.BtnImmerseProMask},
    }

    self._AnimMapping = {
        [Status.CDListExpand] = {enable = "FengmianEnable", disable = "FengmianDisable"},
        [Status.immerse]       = {enable = "CengjinEnable", disable = "CengjinDisable"},
        [Status.musicList]     = {enable = "PanelMusicListViewEnable", disable = "PanelMusicListViewDisable"},
    }

    self._TransActionQueue = {}
    -- self._ImageMainColorAnalyzer = CS.XImageMainColorAnalyse(8, 24)

    self:InitComponents()
end

function XUiMusicPlayerMain:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()

    self.BtnShowMusicList:AddEventListener(function() self:OnBtnShowMusicListClick() end)
    self.BtnHideMusicListMask:AddEventListener(function() self:OnBtnHideMusicListMaskClick() end)
    self.BtnImmerseProMask:AddEventListener(function() self:OnBtnImmerseProMaskClick() end)

    -- Button

    local XUiMusicPlayerConsoleBtnView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUiMusicPlayerConsoleBtnView")
    local XUiMusicPlayerCDView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUiMusicPlayerCDView")
    local XUiMusicPlayerMusicListView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUiMusicPlayerMusicListView")
    local XUIMusciPlayerAlbumCollectionView = require("XUi/XUiMusicPlayer/XUiMusicPlayerMain/XUIMusciPlayerAlbumCollectionView")
    -- XUiNode
    ---@type XUiMusicPlayerConsoleBtnView
    self._ConsoleBtnView = XUiMusicPlayerConsoleBtnView.New(self.ConsoleBtnView, self)

    ---@type XUiMusicPlayerCDView
    self._CDView = XUiMusicPlayerCDView.New(self.CDView, self)

    ---@type XUiMusicPlayerMusicListView
    self._MusicListView = XUiMusicPlayerMusicListView.New(self.MusicListView, self)

    ---@type XUIMusciPlayerAlbumCollectionView
    self._AlbumCollectionView = XUIMusciPlayerAlbumCollectionView.New(self.AlbumCollectionView, self)

    self._CurStatus = nil

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    self:_SwitchStatus(XMusicPlayerEnum.MusicMainUIStatus.mainCD)

end

function XUiMusicPlayerMain:OnStart(bgmId)
    self._JumpBgmId = bgmId
    self:Refresh()
    self:PlayAnimation("ZhenEnable", function()
        self._Control:SetCDAutoRotateEnabled(true)
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_ZHEN_ENABLE_COMPLETE)
    end)
end

function XUiMusicPlayerMain:OnEnable()
    self:_SetEvent(true)
    local cdControl = self._Control:GetCDPlayerControl()
    cdControl:EnterMusicFirstPlayerMusicNotify()
    -- Skip 跳转携带的 bgmId：初始化完成后跳转播放指定歌曲
    if XTool.IsNumberValid(self._JumpBgmId) then
        local bgmId = self._JumpBgmId
        self._JumpBgmId = nil
        local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
        cdControl:JumpPlayByMusicIDWithNotify(XMusicPlayerEnum.MusicListType.Normal, bgmId)
    end
end

function XUiMusicPlayerMain:OnDisable()
    self:_SetEvent(false)
end

function XUiMusicPlayerMain:OnDestroy()
    -- if self._ImageMainColorAnalyzer then
    --     self._ImageMainColorAnalyzer:Release()
    --     self._ImageMainColorAnalyzer = nil
    -- end
    self._Control:GetCDPlayerControl():ExitMusicMainUI()
end

---region ui event
function XUiMusicPlayerMain:OnBtnShowMusicListClick()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local curMusicID = self._Control:GetCDPlayerControl():GetCurPlayingMusicID()
    self._MusicListView:SetJumpMusicIdAndDo(curMusicID, false)
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE, XMusicPlayerEnum.MusicMainUIStatus.musicList)
end

function XUiMusicPlayerMain:OnBtnHideMusicListMaskClick()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if self._CurStatus ~= XMusicPlayerEnum.MusicMainUIStatus.musicList then
        return
    end
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE, XMusicPlayerEnum.MusicMainUIStatus.mainCD)
end

function XUiMusicPlayerMain:OnBtnImmerseProMaskClick()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if self._CurStatus == XMusicPlayerEnum.MusicMainUIStatus.immerse then
        self:_RefreshImmerseIdleRecordTime()
    elseif self._CurStatus == XMusicPlayerEnum.MusicMainUIStatus.immersePro then

        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE,XMusicPlayerEnum.MusicMainUIStatus.immerse)
    end
end
---endregion

---region event
function XUiMusicPlayerMain:_SetEvent(flag)
    local XMusicPlayerEventId = XMVCA.XMusicPlayer.EventIds
    if flag then
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_VIEW_CALL_SWITCH_STATE, self._EventRequestSwitchStatus, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_VIEW_CONSOLE_BTN_CLICK, self._RefreshImmerseIdleRecordTime, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_VIEW_CALL_JUMP_PLAYLIST, self._OnCallJumpPlaylist, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_VIEW_PLAY_SFX, self._OnPlaySfx, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_PLAYER_MUSIC_CHANGE, self._OnCurPlayMusicChange, self)
        self._Control:AddEventListener(XMusicPlayerEventId.EVENT_PLAYER_PLAY_STATE_CHANGE, self._OnPlayStateChange, self)
        self._TickTimer = XScheduleManager.ScheduleForever(function()
            self:_Tick()
        end, 0)
    else
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_VIEW_CALL_SWITCH_STATE, self._EventRequestSwitchStatus, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_VIEW_CONSOLE_BTN_CLICK, self._RefreshImmerseIdleRecordTime, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_VIEW_CALL_JUMP_PLAYLIST, self._OnCallJumpPlaylist, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_VIEW_PLAY_SFX, self._OnPlaySfx, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_PLAYER_MUSIC_CHANGE, self._OnCurPlayMusicChange, self)
        self._Control:RemoveEventListener(XMusicPlayerEventId.EVENT_PLAYER_PLAY_STATE_CHANGE, self._OnPlayStateChange, self)
        if self._TickTimer then
            XScheduleManager.UnSchedule(self._TickTimer)
            self._TickTimer = nil
        end
    end
end

function XUiMusicPlayerMain:_OnCurPlayMusicChange()
    local co = self._Control:GetCDPlayerControl():GetCurPlayingMusicCO()
    -- self.RImgBg:SetRawImage(co.Bg, function()
    --     self:_AnalyzeCurrentMusicBgMainColor()
    -- end)
    self.RImgBg:SetRawImage(co.Bg)
    self._Control:SetMusicBakedColorStyle(co.Id)
    self:PlayAnimation("ZhenEnable", function()
        self._Control:SetCDAutoRotateEnabled(true)
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_ZHEN_ENABLE_COMPLETE)
    end)
end

function XUiMusicPlayerMain:_OnPlayStateChange(isPlaying)
    if isPlaying then
        self:PlayAnimation("ZhenEnable", function()
            self._Control:SetCDAutoRotateEnabled(true)
            self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_ZHEN_ENABLE_COMPLETE)
        end)
    else
        self._Control:SetCDAutoRotateEnabled(false)
        self:PlayAnimation("ZhenDisable")
    end
end

function XUiMusicPlayerMain:_OnPlaySfx(cueName)
    self.AudioObjectPlayer:PlayByKeyName(cueName)
end

-- function XUiMusicPlayerMain:_AnalyzeCurrentMusicBgMainColor()
--     if not self._ImageMainColorAnalyzer or not self.RImgBg or not self.RImgBg.texture then
--         return
--     end

--     local loaded = self._ImageMainColorAnalyzer:LoadTexture2ReadAbleTex(self.RImgBg.texture)
--     if not loaded then
--         XLog.Error("[ImageMainColor] LoadTexture2ReadAbleTex failed, bg=" .. tostring(self.RImgBg.texture.name))
--         return
--     end
--     local color = self._ImageMainColorAnalyzer:AnalyzeMainColor()
--     if not color then
--         XLog.Error("[ImageMainColor] AnalyzeMainColor returned nil mainColor")
--         return
--     end
--     self._Control:SetMusicBgMainColor(color)
-- end

function XUiMusicPlayerMain:_EventRequestSwitchStatus(targetStatus)
    self:_SwitchStatus(targetStatus)
end

function XUiMusicPlayerMain:_OnCallJumpPlaylist(musicID)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if self._CurStatus == XMusicPlayerEnum.MusicMainUIStatus.musicList then
        self._MusicListView:SetJumpMusicIdAndDo(musicID, true)
    else
        self._MusicListView:SetJumpMusicIdAndDo(musicID, false)
        self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_CALL_SWITCH_STATE, XMusicPlayerEnum.MusicMainUIStatus.musicList)
    end
end

function XUiMusicPlayerMain:_Tick()
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    if  self._CurStatus == XMusicPlayerEnum.MusicMainUIStatus.immerse then
        if math.abs(self._EnterImmerseTime - XTime.GetServerNowTimestamp() ) > 3 then
            self:_SwitchStatus(XMusicPlayerEnum.MusicMainUIStatus.immersePro)
        end
    end
end

function XUiMusicPlayerMain:_RefreshImmerseIdleRecordTime()
    self._EnterImmerseTime = XTime.GetServerNowTimestamp()
end
---endregion

function XUiMusicPlayerMain:Refresh()
    self.BtnBack:SetButtonState(CS.UiButtonState.Normal)
end

function XUiMusicPlayerMain:GetMusicPlayerUIStatus()
    return self._CurStatus
end


-- ==================== 状态机 ====================

--- 状态切换入口：生成转换队列并执行
function XUiMusicPlayerMain:_SwitchStatus(targetStatus)
    if self._CurStatus == targetStatus or #self._TransActionQueue ~= 0 then
        return
    end

    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local Status = XMusicPlayerEnum.MusicMainUIStatus
    local lastStatus = self._CurStatus
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_WILL_UPDATE_STATE, lastStatus, targetStatus)

    table.clear(self._TransActionQueue)
    local queue = self._TransActionQueue

    if lastStatus == Status.musicList and targetStatus == Status.immerse then
        -- 特殊：侧栏 → 主界面 → 沉浸（两段转换）
        local midStatus = Status.mainCD
        self:_AppendTransStep(queue, TransitionPhase.ExitState, lastStatus, midStatus)
        self:_AppendTransStep(queue, TransitionPhase.EnterState, lastStatus, midStatus)
        self:_AppendTransStep(queue, TransitionPhase.RecordStatusWithNotify, midStatus, midStatus)
        self:_AppendTransStep(queue, TransitionPhase.ExitState, midStatus, targetStatus)
        self:_AppendTransStep(queue, TransitionPhase.EnterState, midStatus, targetStatus)
        self:_AppendTransStep(queue, TransitionPhase.RecordStatusWithNotify, targetStatus, targetStatus)
    else
        self:_AppendTransStep(queue, TransitionPhase.ExitState, lastStatus, targetStatus)
        self:_AppendTransStep(queue, TransitionPhase.EnterState, lastStatus, targetStatus)
        self:_AppendTransStep(queue, TransitionPhase.RecordStatusWithNotify, targetStatus, targetStatus)
    end

    self:_RunNextTransStep()
end

function XUiMusicPlayerMain:_AppendTransStep(queue, phase, fromStatus, toStatus)
    table.insert(queue, {phase = phase, fromStatus = fromStatus, toStatus = toStatus})
end

--- 队列执行器：取队首执行，完成后自动推进
function XUiMusicPlayerMain:_RunNextTransStep()
    local queue = self._TransActionQueue
    if queue == nil or #queue == 0 then
        return
    end

    local step = queue[1]
    table.remove(queue, 1)

    local function nextStep()
        if #self._TransActionQueue == 0 then
            return
        end
        self:_RunNextTransStep()
    end

    if step.phase == TransitionPhase.ExitState then
        self:_ExitState(step.fromStatus, step.toStatus, nextStep)
    elseif step.phase == TransitionPhase.EnterState then
        self:_EnterState(step.fromStatus, step.toStatus, nextStep)
    elseif step.phase == TransitionPhase.RecordStatusWithNotify then
        self:_RecordStatusWithNotify(step.toStatus, nextStep)
    end
end

--- immerse ↔ immersePro 转换不播动画
local function IsImmerseTransition(fromState, toState)
    local Status = XMVCA.XMusicPlayer.Enum.MusicMainUIStatus
    return (fromState == Status.immerse and toState == Status.immersePro)
        or (fromState == Status.immersePro and toState == Status.immerse)
end

function XUiMusicPlayerMain:_ExitState(fromState, toState, next)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local Status = XMusicPlayerEnum.MusicMainUIStatus
    local state = fromState

    -- Close 逻辑（nil 为初始态：关闭所有子 View）
    local function doClose()
        if state == nil then
            self._MusicListView:Close()
            self._AlbumCollectionView:Close()
        elseif state == Status.musicList then
            self._MusicListView:Close()
        elseif state == Status.CDListExpand then
            self._AlbumCollectionView:Close()
            self._CDView:Open()
        end
        if next then next() end
    end

    local animConfig = state and self._AnimMapping and self._AnimMapping[state]
    local skipAnim = IsImmerseTransition(fromState, toState)
    if animConfig and animConfig.disable and not skipAnim then
        self:PlayAnimation(animConfig.disable, doClose)
    else
        doClose()
    end
end

--- 进入状态：ShowUIByStatus + Open 新 View → 播 enable 动画 → next
function XUiMusicPlayerMain:_EnterState(fromState, toState, next)
    local XMusicPlayerEnum = XMVCA.XMusicPlayer.Enum
    local Status = XMusicPlayerEnum.MusicMainUIStatus
    local state = toState

    -- ShowUIByStatus
    XMVCA.XMusicPlayer.Util.ShowUIByStatus(self._UIShowByStatus, state)

    -- Open 逻辑
    if state == Status.musicList then
        self._MusicListView:Open()
    elseif state == Status.immerse then
        self:_RefreshImmerseIdleRecordTime()
    elseif state == Status.CDListExpand then
        self._AlbumCollectionView:Open()
        self._CDView:Close()
    end

    -- 有动画则播完再 next，无动画直接 next
    local animConfig = self._AnimMapping and self._AnimMapping[state]
    local skipAnim = IsImmerseTransition(fromState, toState)
    if animConfig and animConfig.enable and not skipAnim then
        self:PlayAnimation(animConfig.enable, function()
            if next then next() end
        end)
    else
        if next then next() end
    end
end

function XUiMusicPlayerMain:_RecordStatusWithNotify(state, next)
    local lastStatus = self._CurStatus
    self._CurStatus = state
    self._Control:DispatchEvent(XMVCA.XMusicPlayer.EventIds.EVENT_VIEW_UPDATE_STATE, lastStatus, state)
    if next then next() end
end


return XUiMusicPlayerMain
