--[[
-- XUiCdPlayerMusicDetailPopup.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-14 20:17:50
--]]

---@class XUiCdPlayerMusicDetailPopup : XLuaUi
---@field _Control XMusicPlayerControl
---@field TxtTitle UnityEngine.UI.Text
---@field TxtContent UnityEngine.UI.Text
---@field BtnClose UnityEngine.UI.Button
---@field BtnTanchuangCloseBig UnityEngine.UI.Button
local XUiCdPlayerMusicDetailPopup = XLuaUiManager.Register(XLuaUi, "UiCdPlayerMusicDetailPopup")
function XUiCdPlayerMusicDetailPopup:OnAwake()
    self:InitComponents()
end

function XUiCdPlayerMusicDetailPopup:InitComponents()
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnTanchuangCloseBig:AddEventListener(function() self:OnBtnCloseClick() end)
end

---@param musicID number 要展示详情的歌曲ID
function XUiCdPlayerMusicDetailPopup:OnStart(musicID)
    self._MusicID = musicID
    self:Refresh()
end

function XUiCdPlayerMusicDetailPopup:OnEnable()
end

function XUiCdPlayerMusicDetailPopup:OnDisable()
end

function XUiCdPlayerMusicDetailPopup:OnDestroy()
end

function XUiCdPlayerMusicDetailPopup:Refresh()
    local co = self._Control:GetMusicPlayerconfigControl():GetMusicPlayerAlbumCOByid(self._MusicID)
    if not co then
        return
    end
    self.TxtTitle.text = CS.XTextManager.GetText("MusicPlayerMusicDetailTitle")
    self.TxtContent.text = XUiHelper.ConvertLineBreakSymbol(co.Composer)


end

function XUiCdPlayerMusicDetailPopup:OnBtnCloseClick()
    self:Close()
end

return XUiCdPlayerMusicDetailPopup
