--[[
-- XUiRoleExchangeTipPopup.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-11 12:14:14
--]]

local XUiRoleCostPreviewPopupGridExchange = require("XUi/XUiRole/XUiRoleCostPreviewPopup/XUiRoleCostPreviewPopupGridExchange")

local MAX_ASSET_COUNT = 3

---@param exchangeList table[]
---@return table[]
local function BuildExchangeList(exchangeList)
    -- exchangeList 项 {ItemId, RewardCount(总产出), ConsumeList={{Id,Count}(总消耗)}}
    local groupDic = {}
    local groupOrder = {}
    for _, info in ipairs(exchangeList or table.empty) do
        local consumeList = info.ConsumeList or table.empty
        if #consumeList ~= 1 then
            XLog.Error("XUiRoleExchangeTipPopup: Auto exchange item must consume exactly one token.", info)
        else
            local consume = consumeList[1]
            local consumeId = consume.Id
            local group = groupDic[consumeId]
            if not group then
                group = { ConsumeId = consumeId, ConsumeCount = 0, Rewards = {} }
                groupDic[consumeId] = group
                table.insert(groupOrder, group)
            end
            group.ConsumeCount = group.ConsumeCount + consume.Count
            table.insert(group.Rewards, { ItemId = info.ItemId, RewardCount = info.RewardCount })
        end
    end
    table.sort(groupOrder, function(a, b) return a.ConsumeId < b.ConsumeId end)
    return groupOrder
end

---@param exchangeList table[]
---@return number[]
local function GetConsumeItemIds(exchangeList)
    local consumeItemIds = {}
    for _, exchange in ipairs(exchangeList) do
        table.insert(consumeItemIds, exchange.ConsumeId)
    end
    return consumeItemIds
end

---@class XUiRoleExchangeTipPopup : XLuaUi
---@field BtnClose XUiComponent.XUiButton
---@field BtnCancel XUiComponent.XUiButton
---@field BtnDetermine XUiComponent.XUiButton
---@field PanelAsset UnityEngine.RectTransform
---@field GridExchange UnityEngine.RectTransform
local XUiRoleExchangeTipPopup = XLuaUiManager.Register(XLuaUi, "UiRoleExchangeTipPopup")

function XUiRoleExchangeTipPopup:OnAwake()
    self:InitComponents()
end

function XUiRoleExchangeTipPopup:InitComponents()
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnCancel:AddEventListener(function() self:OnBtnCancelClick() end)
    self.BtnDetermine:AddEventListener(function() self:OnBtnDetermineClick() end)

    self.GridExchange.gameObject:SetActiveEx(false)
    self.ExchangeGrids = {}
end

---@param data table[]
---@param confirmCb function
function XUiRoleExchangeTipPopup:OnStart(data, confirmCb)
    self.ConfirmCb = confirmCb
    self.ExchangeList = BuildExchangeList(data or table.empty)

    local consumeItemIds = GetConsumeItemIds(self.ExchangeList)
    if #consumeItemIds > MAX_ASSET_COUNT then
        XLog.Warning("XUiRoleExchangeTipPopup: Consume token count exceeds asset panel capacity.", consumeItemIds)
    end
    self.AssetPanel = XUiHelper.XUiPanelAsset(self, self.PanelAsset, table.unpack(consumeItemIds))

    self:Refresh()
end

function XUiRoleExchangeTipPopup:Refresh()
    self:RefreshExchangeGrids(self.ExchangeList)
end

function XUiRoleExchangeTipPopup:RefreshExchangeGrids(exchangeList)
    XTool.UpdateDynamicItem(self.ExchangeGrids, exchangeList, self.GridExchange, XUiRoleCostPreviewPopupGridExchange, self)
end

function XUiRoleExchangeTipPopup:OnBtnCloseClick()
    self:Close()
end

function XUiRoleExchangeTipPopup:OnBtnCancelClick()
    self:Close()
end

function XUiRoleExchangeTipPopup:OnBtnDetermineClick()
    local confirmCb = self.ConfirmCb
    self:Close()

    if confirmCb then
        confirmCb()
    end
end

return XUiRoleExchangeTipPopup
