--[[
-- XUiEquipPartnerOneClickPopup.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-30 21:08:55
--]]


---@class XUiEquipPartnerOneClickPopup : XLuaUi
---@field _Control XPartnerControl
---@field PanelAsset UnityEngine.RectTransform
---@field BtnTanchuangClose XUiComponent.XUiButton
---@field BtnClosePopup XUiComponent.XUiButton
---@field TextName UnityEngine.UI.Text
---@field BtnAutoSetting XUiComponent.XUiButton
---@field UiEquipBtnRadio XUiComponent.XUiButton
---@field BtnSure XUiComponent.XUiButton
---@field BtnTip XUiComponent.XUiButton
---@field GoBubbleDetail UnityEngine.RectTransform
---@field BtnDetailClose XUiComponent.XUiButton
---@field TxtDetail UnityEngine.UI.Text
---@field DetailListView UiObject
---@field StarUpPreview UiObject
---@field BtnStarUpPreviewClose XUiComponent.XUiButton 升星预览关闭按钮
---@field GoConsume1 UnityEngine.RectTransform
---@field RImgConsume1 UnityEngine.UI.RawImage
---@field TxtCostMoney1 UnityEngine.UI.Text
---@field GoConsume2 UnityEngine.RectTransform
---@field RImgConsume2 UnityEngine.UI.RawImage
---@field TxtCostMoney2 UnityEngine.UI.Text
---@field GoConsume3 UnityEngine.RectTransform
---@field RImgConsume3 UnityEngine.UI.RawImage
---@field TxtCostMoney3 UnityEngine.UI.Text
---@field private _DetailListView XUiEquipPartnerOneClickPopupDetailListView
---@field private _StarUpPreview XUiEquipPartnerOneKeyCultureSelectPreview
local XUiEquipPartnerOneClickPopup = XLuaUiManager.Register(XLuaUi, "UiEquipPartnerOneClickPopup")



function XUiEquipPartnerOneClickPopup:OnAwake()
    ---@type table[] 兑换材料展示列表缓存
    self._ExchangeTipList = {}
    ---@type table<number, table> 兑换计划按 ItemId 合并的临时字典缓存
    self._ExchangeMergedDic = {}
    self:InitComponents()
end

function XUiEquipPartnerOneClickPopup:InitComponents()
    -- Button
    self.BtnTanchuangClose:AddEventListener(function() self:OnBtnTanchuangCloseClick() end)
    self.BtnClosePopup:AddEventListener(function() self:OnBtnClosePopupClick() end)
    self.BtnAutoSetting:AddEventListener(function() self:OnBtnAutoSettingClick() end)
    self.UiEquipBtnRadio:AddEventListener(function() self:OnUiEquipBtnRadioClick() end)
    self.BtnSure:AddEventListener(function() self:OnBtnSureClick() end)
    self.BtnTip:AddEventListener(function() self:OnBtnTipClick() end)
    self.BtnDetailClose:AddEventListener(function() self:OnBtnDetailCloseClick() end)
    self.BtnStarUpPreviewClose:AddEventListener(function() self:OnBtnStarUpPreviewCloseClick() end)

    local assetItemIds = self._Control:GetOneKeyCultureMainControl():GetAssetPanelItemIds()
    self._PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, table.unpack(assetItemIds))

    -- 初始化气泡详情和升星预览mask为隐藏状态
    self.GoBubbleDetail.gameObject:SetActiveEx(false)
    self.BtnStarUpPreviewClose.gameObject:SetActiveEx(false)

    -- XUiNode - 升星预览
    local XUiEquipPartnerOneKeyCultureSelectPreview = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerOneKeyCultureSelectClipPopup/XUiEquipPartnerOneKeyCultureSelectPreview")
    self._StarUpPreview = XUiEquipPartnerOneKeyCultureSelectPreview.New(self.StarUpPreview, self)


    -- XUiNode
    local XUiEquipPartnerOneClickPopupDetailListView = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerOneClickPopup/XUiEquipPartnerOneClickPopupDetailListView")
    self._DetailListView = XUiEquipPartnerOneClickPopupDetailListView.New(self.DetailListView, self)
end

function XUiEquipPartnerOneClickPopup:OnStart(...)
    self:_CalcCommitData()
    self:_Refresh()
end

function XUiEquipPartnerOneClickPopup:OnEnable()
    self:_SetEvent(true)
end

function XUiEquipPartnerOneClickPopup:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipPartnerOneClickPopup:OnDestroy()
end

---region ui event

function XUiEquipPartnerOneClickPopup:OnBtnTanchuangCloseClick(eventData)
    self:Close()
end

function XUiEquipPartnerOneClickPopup:OnBtnClosePopupClick(eventData)
    self:Close()
end

function XUiEquipPartnerOneClickPopup:OnBtnAutoSettingClick(eventData)
    XLuaUiManager.Open("UiEquipOneClickAutoCommonSetting")
end

function XUiEquipPartnerOneClickPopup:OnUiEquipBtnRadioClick(eventData)
    local isAuto = self._Control:GetOneKeyCultureMainControl():IsAutoExchange()
    self._Control:GetOneKeyCultureMainControl():SetAutoExchangeWithNotify(not isAuto)
end

function XUiEquipPartnerOneClickPopup:OnBtnSureClick(eventData)
    if not self:_HasAnyCulture() then
        return
    end

    -- 存在兑换材料（拟战代币自动兑换 / 钛矿兑换碎片）时拉起兑换确认弹窗，否则拉起普通确认弹窗
    local exchangeList = self:_BuildExchangeTipList()
    if not XTool.IsTableEmpty(exchangeList) then
        XLuaUiManager.Open("UiRoleExchangeTipPopup", exchangeList, function()
            self:_OpenEnhanceProgressPopup()
        end)
        return
    end

    XUiManager.DialogTip("", XUiHelper.GetText("PartnerOneKeyCommitConfirm"), XUiManager.DialogType.Normal, nil, function()
        self:_OpenEnhanceProgressPopup()
    end)
end
 
function XUiEquipPartnerOneClickPopup:_OpenEnhanceProgressPopup()
    self:Close()
    XLuaUiManager.Open("UiEquipPartnerEnhanceProgressPopup")
end

function XUiEquipPartnerOneClickPopup:OnBtnTipClick(eventData)
    self:_ShowBubbleDetail(true)
end

function XUiEquipPartnerOneClickPopup:OnBtnDetailCloseClick(eventData)
    self:_ShowBubbleDetail(false)
end

function XUiEquipPartnerOneClickPopup:OnBtnStarUpPreviewCloseClick()
    self._StarUpPreview:Close()
    self.BtnStarUpPreviewClose.gameObject:SetActiveEx(false)
end

---endregion

---region event

function XUiEquipPartnerOneClickPopup:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_CULTURE_SELECT_CHANGE, self._OnCultureSelectChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_PARTNER_FOOD_CHANGE, self._OnPartnerFoodChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_VIEW_PARTNER_POPUP_OPEN_STARUP_PREVIEW, self._OnOpenStarUpPreview, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_CULTURE_SELECT_CHANGE, self._OnCultureSelectChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_PARTNER_FOOD_CHANGE, self._OnPartnerFoodChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_VIEW_PARTNER_POPUP_OPEN_STARUP_PREVIEW, self._OnOpenStarUpPreview, self)
    end
end

function XUiEquipPartnerOneClickPopup:_OnCultureSelectChange()
    self:_CalcCommitData()
    self:_Refresh()
end

function XUiEquipPartnerOneClickPopup:_OnPartnerFoodChange()
    self:_CalcCommitData()
    self:_Refresh()
end

function XUiEquipPartnerOneClickPopup:_OnAutoExchangeChange()
    self:_CalcCommitData()
    self:_Refresh()
end

function XUiEquipPartnerOneClickPopup:_OnOpenStarUpPreview()
    self._StarUpPreview:Open()
    self.BtnStarUpPreviewClose.gameObject:SetActiveEx(true)
end



function XUiEquipPartnerOneClickPopup:_OnPartnerDataUpdate()
    self:_CalcCommitData()
    self:_Refresh()
end

--- 是否存在本次可提交的养成内容
---@return boolean
function XUiEquipPartnerOneClickPopup:_HasAnyCulture()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local commitControl = mainControl:GetCommitControl()
    local XPartnerEnum = XMVCA.XPartner.Enum
    local hasLevelUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.LevelUp)
        and commitControl:GetLevelUpConsumeIndex() > 0
    local hasStarUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.StarUp)
        and (commitControl:GetStarUpConsumeIndex() > 0 or commitControl:HasStarUpTailFeed())
    local hasSkillLevelUp = commitControl:IsCultureSelected(XPartnerEnum.CultureType.SkillLevelUp)
        and commitControl:GetSkillConsumeIndex() > 0
    return hasLevelUp or hasStarUp or hasSkillLevelUp
end

---endregion

function XUiEquipPartnerOneClickPopup:_Refresh()
    local hasAnyCulture = self:_HasAnyCulture()
    self.BtnSure:SetButtonState(hasAnyCulture and CS.UiButtonState.Normal or CS.UiButtonState.Disable)

    self.TextName.text = XUiHelper.GetText("PartnerOneKeySelectCostMaterial")
    self._DetailListView:Refresh()
    self:_RefreshAutoExchange()
    self:_RefreshCostMoney()
    self:_RefreshBubbleDetail()
end

function XUiEquipPartnerOneClickPopup:_RefreshAutoExchange()
    local isAuto = self._Control:GetOneKeyCultureMainControl():IsAutoExchange()
    self.UiEquipBtnRadio:SetButtonState(isAuto and CS.UiButtonState.Select or CS.UiButtonState.Normal)
end

function XUiEquipPartnerOneClickPopup:_RefreshCostMoney()
    local itemIds = XDataCenter.ItemManager.ItemId
    local commitControl = self._Control:GetOneKeyCultureMainControl():GetCommitControl()

    -- 螺母
    local coinCost = self:_GetCostMoney(commitControl:GetLevelUpConsumedList(), itemIds.Coin)
        + self:_GetCostMoney(commitControl:GetStarUpConsumedList(), itemIds.Coin)
        + self:_GetCostMoney(commitControl:GetSkillConsumedList(), itemIds.Coin)
    self:_RefreshCostItem(self.GoConsume1, self.RImgConsume1, self.TxtCostMoney1, itemIds.Coin, coinCost)

    local exchangeList = self:_BuildExchangeTipList()

    -- 拟战积分
    local repeatChallengeCoinCost = 0
    for _, exchange in ipairs(exchangeList) do
        repeatChallengeCoinCost = repeatChallengeCoinCost + self:_GetCostMoney(exchange.ConsumeList, itemIds.RepeatChallengeCoin)
    end
    self:_RefreshCostItem(self.GoConsume2, self.RImgConsume2, self.TxtCostMoney2, itemIds.RepeatChallengeCoin, repeatChallengeCoinCost)

    -- 钛矿
    local tantalumIronOreCost = 0
    for _, exchange in ipairs(exchangeList) do
        tantalumIronOreCost = tantalumIronOreCost + self:_GetCostMoney(exchange.ConsumeList, itemIds.TantalumIronOre)
    end
    self:_RefreshCostItem(self.GoConsume3, self.RImgConsume3, self.TxtCostMoney3, itemIds.TantalumIronOre, tantalumIronOreCost)
end

function XUiEquipPartnerOneClickPopup:_RefreshCostItem(goConsume, imgConsume, txtCostMoney, itemId, cost)
    goConsume.gameObject:SetActiveEx(cost > 0)
    imgConsume:SetRawImage(XItemConfigs.GetItemIconById(itemId))
    txtCostMoney.text = self:_FormatCost(cost)
end

---@param costList table<{Id: number, Count: number}>
---@param coinId number
---@return number
function XUiEquipPartnerOneClickPopup:_GetCostMoney(costList, coinId)
    for _, item in ipairs(costList) do
        if item.Id == coinId then
            return item.Count
        end
    end
    return 0
end

function XUiEquipPartnerOneClickPopup:_CalcCommitData()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    mainControl:GetBaseCostControl():CalcAllCostData()
    mainControl:GetCommitControl():CalcCommit()
end

---region 气泡提示

---@param isShow boolean
function XUiEquipPartnerOneClickPopup:_ShowBubbleDetail(isShow)
    self.GoBubbleDetail.gameObject:SetActiveEx(isShow)
end

function XUiEquipPartnerOneClickPopup:_RefreshBubbleDetail()
    self.TxtDetail.text = XUiHelper.GetText("PartnerOneKeyBubbleDetail")
end

---endregion





--- 汇总本次提交涉及的兑换材料，供 UiRoleExchangeTipPopup 展示
--- 数据项格式：{ItemId(产物), RewardCount(总产出), ConsumeList={{Id(代币), Count(总消耗)}}}
---@return table[]
function XUiEquipPartnerOneClickPopup:_BuildExchangeTipList()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local commitControl = mainControl:GetCommitControl()
    local exchangeList = self._ExchangeTipList
    local mergedDic = self._ExchangeMergedDic
    table.clear(exchangeList)
    table.clear(mergedDic)

    -- 自动兑换计划（拟战代币兑换养成材料），同一产物可能有多条计划，按 ItemId 合并
    for _, plan in ipairs(commitControl:GetExchangePlanList()) do
        local merged = mergedDic[plan.ItemId]
        if not merged then
            merged = { ItemId = plan.ItemId, RewardCount = 0, ConsumeCountDic = {} }
            mergedDic[plan.ItemId] = merged
            table.insert(exchangeList, merged)
        end
        merged.RewardCount = merged.RewardCount + plan.GainCount
        for _, consume in ipairs(plan.ConsumeList) do
            merged.ConsumeCountDic[consume.ConsumeId] = (merged.ConsumeCountDic[consume.ConsumeId] or 0) + consume.ConsumeCount * plan.Times
        end
    end
    for _, merged in ipairs(exchangeList) do
        local consumeList = {}
        for consumeId, consumeCount in pairs(merged.ConsumeCountDic) do
            table.insert(consumeList, { Id = consumeId, Count = consumeCount })
        end
        table.sort(consumeList, function(a, b) return a.Id < b.Id end)
        merged.ConsumeList = consumeList
        merged.ConsumeCountDic = nil
    end

    -- 选中的钛矿（钽铁合矿）兑换碎片
    local needChipCount = commitControl:GetSelectOreExchangeChipCount()
    if needChipCount > 0 then
        local partner = mainControl:GetCurPartnerEntity()
        local chipNeedCount = partner and partner:GetChipNeedCount()
        if partner and XTool.IsNumberValid(chipNeedCount) then
            local chipItemId = partner:GetChipItemId()
            local _, exchangeChipCount, consumeId, consumeCount =
                XMVCA.XPartner.Util.GetOreExchangeChipCostByCount(chipItemId, needChipCount)
            if exchangeChipCount >= needChipCount then
                table.insert(exchangeList, {
                    ItemId = chipItemId,
                    RewardCount = exchangeChipCount,
                    ConsumeList = { { Id = consumeId, Count = consumeCount } },
                })
            else
                XLog.Error(string.format(
                    "XUiEquipPartnerOneClickPopup:_BuildExchangeTipList 无法满足碎片兑换需求, chipItemId=%s needChipCount=%s exchangeChipCount=%s",
                    tostring(chipItemId), tostring(needChipCount), tostring(exchangeChipCount)))
            end
        end
    end

    return exchangeList
end


---将代币数量缩写为 K，向下保留最多一位小数
---@param cost number
---@return string
function XUiEquipPartnerOneClickPopup:_FormatCost(cost)
    local KILO = 1000
    if cost < KILO then
        return tostring(cost)
    end

    local costInK = math.floor(cost / KILO * 10) / 10
    local costText = string.format("%.1f", costInK):gsub("%.0$", "")
    return costText .. "K"
end

return XUiEquipPartnerOneClickPopup
