--[[
-- XUiEquipPartnerOneClickPopupDetailListView.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-30 21:15:26
--]]


---@class XUiEquipPartnerOneClickPopupDetailListView : XUiNode
---@field _Control XPartnerControl
---@field LvupCostItemCellView UnityEngine.RectTransform
---@field StarUpCostItemCellView UnityEngine.RectTransform
---@field SkillLvupCostItemCellView UnityEngine.RectTransform
---@field private _LvupCostItemCellView XUiEquipPartnerOneClickPopupCostItemCellView
---@field private _StarUpCostItemCellView XUiEquipPartnerOneClickPopupCostItemCellView
---@field private _SkillLvupCostItemCellView XUiEquipPartnerOneClickPopupCostItemCellView
local XUiEquipPartnerOneClickPopupDetailListView = XClass(XUiNode, "XUiEquipPartnerOneClickPopupDetailListView")
function XUiEquipPartnerOneClickPopupDetailListView:InitComponents()
    local XUiEquipPartnerOneClickPopupCostItemCellView = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerOneClickPopup/cell/XUiEquipPartnerOneClickPopupCostItemCellView")

    self._LvupCostItemCellView = XUiEquipPartnerOneClickPopupCostItemCellView.New(self.LvupCostItemCellView, self)
    self._StarUpCostItemCellView = XUiEquipPartnerOneClickPopupCostItemCellView.New(self.StarUpCostItemCellView, self)
    self._SkillLvupCostItemCellView = XUiEquipPartnerOneClickPopupCostItemCellView.New(self.SkillLvupCostItemCellView, self)
end

function XUiEquipPartnerOneClickPopupDetailListView:OnStart(...)
    self:InitComponents()
end

function XUiEquipPartnerOneClickPopupDetailListView:OnEnable()
    self:Refresh()
end

function XUiEquipPartnerOneClickPopupDetailListView:OnDisable()
end

function XUiEquipPartnerOneClickPopupDetailListView:OnDestroy()
end

function XUiEquipPartnerOneClickPopupDetailListView:Refresh()
    local XPartnerEnum = XMVCA.XPartner.Enum
    self:_RefreshCellView(self._LvupCostItemCellView, XPartnerEnum.CultureType.LevelUp)
    self:_RefreshCellView(self._StarUpCostItemCellView, XPartnerEnum.CultureType.StarUp)
    self:_RefreshCellView(self._SkillLvupCostItemCellView, XPartnerEnum.CultureType.SkillLevelUp)
end

-- 养成已满的条目隐藏（技能需槽位选满且全部满级才隐藏）
---@param cellView XUiEquipPartnerOneClickPopupCostItemCellView
---@param cultureType XPartnerEnum.CultureType
function XUiEquipPartnerOneClickPopupDetailListView:_RefreshCellView(cellView, cultureType)
    local partnerId = self._Control:GetOneKeyCultureMainControl():GetCurPartnerId()
    local isMax = XMVCA.XPartner:GetOneKeyCultureAgency():IsCultureTypeMax(partnerId, cultureType)
    if isMax then
        cellView:Close()
        return
    end
    cellView:Open()
    cellView:Refresh(cultureType)
end

return XUiEquipPartnerOneClickPopupDetailListView
