--[[
-- XUiEquipPartnerOneKeyCultureSelectClipPopup.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-05 12:28:12
--]]

---@class XUiEquipPartnerOneKeyCultureSelectClipPopup : XLuaUi
---@field _Control XPartnerControl
---@field BtnCloseMask XUiComponent.XUiButton
---@field BtnClose XUiComponent.XUiButton
---@field PanelAsset UnityEngine.RectTransform
---@field RImgNowQuality UnityEngine.UI.RawImage
---@field GoImgArrow UnityEngine.RectTransform
---@field RImgAfterQuality UnityEngine.UI.RawImage
---@field BtnLevelupPreview XUiComponent.XUiButton
---@field BtnPreview XUiComponent.XUiButton
---@field UiEquipGridPartnerFragment UiObject
---@field BtnConfirm XUiComponent.XUiButton
---@field TxtCost UnityEngine.UI.Text
---@field StarUpPreview UiObject
---@field GoTagExchange UnityEngine.RectTransform
---@field private _GridPartnerFragmentList XUiEquipPartnerOneKeyCultureSelectCell[]
---@field private _Preview XUiEquipPartnerOneKeyCultureSelectPreview
local XUiEquipPartnerOneKeyCultureSelectClipPopup = XLuaUiManager.Register(XLuaUi, "UiEquipPartnerOneKeyCultureSelectClipPopup")


function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnAwake()
    self:InitComponents()
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:InitComponents()
    -- Button
    self.BtnCloseMask.CallBack = function() self:OnBtnCloseMaskClick() end
    self.BtnClose.CallBack = function() self:OnBtnCloseClick() end
    self.BtnLevelupPreview.CallBack = function() self:OnBtnLevelupPreviewClick() end
    self.BtnPreview.CallBack = function() self:OnBtnPreviewClick() end
    self.BtnConfirm.CallBack = function() self:OnBtnConfirmClick() end

    -- PanelAsset
    local assetItemIds = self._Control:GetOneKeyCultureMainControl():GetAssetPanelItemIds()
    self.PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, table.unpack(assetItemIds))

    self._GridPartnerFragmentList = {}
    self.UiEquipGridPartnerFragment.gameObject:SetActiveEx(false)

    -- XUiNode
    local XUiEquipPartnerOneKeyCultureSelectPreview = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerOneKeyCultureSelectClipPopup/XUiEquipPartnerOneKeyCultureSelectPreview")
    self._Preview = XUiEquipPartnerOneKeyCultureSelectPreview.New(self.StarUpPreview, self)
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnStart(...)
    self._CostNormalColor = self.TxtCost.color
    self._CostLackColor = XUiHelper.Hexcolor2Color("E43730")
    self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl():OpenFoodSelect()
    self:_Refresh()
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnEnable()
    self:_SetEvent(true)
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnDestroy()
    self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl():CloseFoodSelect()
end

---region ui event

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnBtnCloseMaskClick(eventData)
    self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl():CancelFoodSelect()
    self:Close()
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnBtnCloseClick(eventData)
    self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl():CancelFoodSelect()
    self:Close()
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnBtnLevelupPreviewClick(eventData)
    local isActive = self.StarUpPreview.gameObject.activeSelf
    if isActive then
        self._Preview:Close()
    else
        self._Preview:Open()
    end
end

--- 消耗预览：展示选中狗粮/碎片的总消耗，以及矿石兑换碎片的明细
--- 数据仅供 UiRoleCostPreviewPopup 一次性展示，直接在 View 组装弹窗数据结构
function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnBtnPreviewClick(eventData)
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local partner = mainControl:GetCurPartnerEntity()
    if not partner then
        return
    end
    local foodSelectControl = mainControl:GetFoodSelectControl()

    local chipItemId = partner:GetChipItemId()
    local chipNeedCount = partner:GetChipNeedCount() or 0

    -- 总碎片 = 狗粮 + 散碎片 + 矿石兑换格；拆出兑换部分
    local totalChips = foodSelectControl:GetFoodSelectExpCount()
    local exchangeChips = foodSelectControl:GetSelectOreExchangeChipCount()
    local ownChips = totalChips - exchangeChips

    local costList = {}
    if ownChips > 0 then
        table.insert(costList, { Id = chipItemId, Count = ownChips, IsExchange = false })
    end
    if exchangeChips > 0 then
        table.insert(costList, { Id = chipItemId, Count = exchangeChips, IsExchange = true })
    end
    for _, cost in ipairs(foodSelectControl:GetFoodSelectMoneyCostList()) do
        table.insert(costList, { Id = cost.Id, Count = cost.Count, IsExchange = false })
    end

    local sections = {}
    if not XTool.IsTableEmpty(costList) then
        table.insert(sections, { Title = XUiHelper.GetText("PartnerOneKeyStarUpTitle"), CostList = costList })
    end

    -- 矿石兑换明细
    local exchangeList = {}
    if exchangeChips > 0 then
        local _, exchangeChipCount, consumeId, consumeCount =
            XMVCA.XPartner.Util.GetOreExchangeChipCostByCount(chipItemId, exchangeChips)
        if exchangeChipCount >= exchangeChips then
            table.insert(exchangeList, {
                ItemId = chipItemId,
                RewardCount = exchangeChipCount,
                ConsumeList = { { Id = consumeId, Count = consumeCount } },
            })
        end
    end

    XLuaUiManager.Open("UiRoleCostPreviewPopup", { Sections = sections, ExchangeList = exchangeList })
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:OnBtnConfirmClick(eventData)
    self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl():ConfirmFoodSelect()
    self:Close()
end

---endregion

---region event

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_FOOD_SELECT_PREVIEW_CHANGE, self._OnFoodSelectChange, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_FOOD_SELECT_PREVIEW_CHANGE, self._OnFoodSelectChange, self)
    end
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_OnFoodSelectChange()
    self:_RefreshCost()
    self:_RefreshQuality()
    self:_RefreshExchangeTag()
end

---endregion

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_Refresh()
    self._Preview:Close()
    self.BtnCloseMask:SetButtonState(CS.UiButtonState.Normal)
    self.BtnClose:SetButtonState(CS.UiButtonState.Normal)
    self.BtnLevelupPreview:SetButtonState(CS.UiButtonState.Normal)
    self.BtnConfirm:SetButtonState(CS.UiButtonState.Normal)
    self:_RefreshQuality()
    self:_RefreshPartnerList()
    self:_RefreshCost()
    self:_RefreshExchangeTag()
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_RefreshExchangeTag()
    local foodSelectControl = self._Control:GetOneKeyCultureMainControl():GetFoodSelectControl()
    local hasSelectOreExchangeClip = false
    for index = 1, self._OreExchangeFoodCount or 0 do
        if foodSelectControl:IsOreExchangeClipSelect(index) then
            hasSelectOreExchangeClip = true
            break
        end
    end
    self.GoTagExchange.gameObject:SetActiveEx(hasSelectOreExchangeClip)
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_RefreshQuality()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local partner = mainControl:GetCurPartnerEntity()
    if not partner then
        return
    end

    local foodSelectControl = mainControl:GetFoodSelectControl()
    local curQuality = partner:GetQuality()
    local afterQuality = curQuality

    local selectCount = foodSelectControl:GetFoodSelectCount()
    if selectCount > 0 then
        local canUpCount = foodSelectControl:GetFoodSelectCanUpCount()
        afterQuality = math.min(curQuality + canUpCount, partner:GetQualityLimit())
    end

    local isQualityUp = afterQuality > curQuality
    self.RImgNowQuality:SetRawImage(XMVCA.XCharacter:GetCharacterQualityIcon(curQuality))
    self.GoImgArrow.gameObject:SetActiveEx(isQualityUp)
    self.RImgAfterQuality.gameObject:SetActiveEx(isQualityUp)
    if isQualityUp then
        self.RImgAfterQuality:SetRawImage(XMVCA.XCharacter:GetCharacterQualityIcon(afterQuality))
    end
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_RefreshPartnerList()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local partnerList = mainControl:GetQualityUpPartnerListAndClipCount()
    local partnerListCount = #partnerList

    local partner = mainControl:GetCurPartnerEntity()
    local chipItemId = partner:GetChipItemId()
    local foodSelectControl = mainControl:GetFoodSelectControl()
    local totalChips = foodSelectControl:GetLooseChipCount()
    local chipNeedCount = partner:GetChipNeedCount()
    local fullClipFoodCount = math.floor(totalChips / chipNeedCount)
    foodSelectControl:InitOreExchangeRemainChipCount(totalChips % chipNeedCount)
    local remainChipCount = foodSelectControl:GetOreExchangeRemainChipCount() or 0
    local oreExchangeFoodCount = foodSelectControl:GetOreExchangePartnerCount()
    self._OreExchangeFoodCount = oreExchangeFoodCount
    local hasLooseChipGrid = remainChipCount > 0 and oreExchangeFoodCount <= 0
    local clipFoodCount = fullClipFoodCount + (hasLooseChipGrid and 1 or 0)
    local totalCount = partnerListCount + clipFoodCount + oreExchangeFoodCount

    self:_EnsureGridCount(totalCount)

    for index = 1, totalCount do
        local grid = self._GridPartnerFragmentList[index]
        if index <= partnerListCount then
            grid:RefreshByPartner(partnerList[index])
        elseif index <= partnerListCount + clipFoodCount then
            local clipIndex = index - partnerListCount
            local curCount = chipNeedCount
            if hasLooseChipGrid and clipIndex == clipFoodCount then
                curCount = remainChipCount
            end
            grid:RefreshByPartnerClip(chipItemId, clipIndex, curCount)
        else
            local oreExchangeClipIndex = index - partnerListCount - clipFoodCount
            local exchangeChipCount = foodSelectControl:GetOreExchangeClipNeedChipCount(oreExchangeClipIndex)
            local ownChipCount = oreExchangeClipIndex == 1 and remainChipCount or 0
            local isMixed = ownChipCount > 0 and exchangeChipCount < chipNeedCount
            local curCount = isMixed and ownChipCount or chipNeedCount
            grid:RefreshByOreExchangeClip(chipItemId, oreExchangeClipIndex, curCount, isMixed,
                ownChipCount, exchangeChipCount)
        end
        grid:Open()
    end

    for index = totalCount + 1, #self._GridPartnerFragmentList do
        self._GridPartnerFragmentList[index]:Close()
    end
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_RefreshCost()
    local mainControl = self._Control:GetOneKeyCultureMainControl()
    local foodSelectControl = mainControl:GetFoodSelectControl()
    local selectCount = foodSelectControl:GetFoodSelectCount()
    if selectCount == 0 then
        self.TxtCost.text = XUiHelper.GetText("PartnerOneKeySelectPartnerTip")
        self.TxtCost.color = self._CostNormalColor
    else
        local costMoney = foodSelectControl:GetFoodSelectCostMoney()
        local coinItemId = XDataCenter.ItemManager.ItemId.Coin
        local haveMoney = mainControl:GetBaseCostControl():GetItemHaveCount(coinItemId)
        self.TxtCost.text = costMoney
        self.TxtCost.color = haveMoney < costMoney and self._CostLackColor or self._CostNormalColor
    end
end

function XUiEquipPartnerOneKeyCultureSelectClipPopup:_EnsureGridCount(count)
    local XUiEquipPartnerOneKeyCultureSelectCell = require("XUi/XUiPartnerOneKeyCulture/XUiEquipPartnerOneKeyCultureSelectClipPopup/XUiEquipPartnerOneKeyCultureSelectCell")
    while #self._GridPartnerFragmentList < count do
        local ui = CS.UnityEngine.Object.Instantiate(self.UiEquipGridPartnerFragment, self.UiEquipGridPartnerFragment.transform.parent)
        ui.gameObject:SetActiveEx(true)
        local grid = XUiEquipPartnerOneKeyCultureSelectCell.New(ui, self)
        table.insert(self._GridPartnerFragmentList, grid)
    end
end

return XUiEquipPartnerOneKeyCultureSelectClipPopup
