--[[
-- XUiEquipOneClickCulturePartnerMainPanelPartnerPlan.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-24 15:59:14
--]]

---@class XUiEquipOneClickCulturePartnerMainPanelPartnerPlan : XUiNode
---@field _Control XPartnerControl
---@field TxtPartnerName UnityEngine.UI.Text
---@field RImgRecommendQuality UnityEngine.UI.RawImage
---@field RImgCurQuality UnityEngine.UI.RawImage
---@field ImgBreak UnityEngine.UI.Image
---@field TxtMaxLevel UnityEngine.UI.Text
---@field TxtCurLevel UnityEngine.UI.Text
---@field UiEquipGridPartnerSkill1 UiObject
---@field UiEquipGridPartnerSkill2 UiObject
---@field UiEquipGridPartnerSkill3 UiObject
---@field UiEquipGridPartnerSkill4 UiObject
---@field UiEquipGridPartnerSkill5 UiObject
---@field UiEquipGridPartnerSkill6 UiObject
--- 以下是自定义部分
---@field _MainSkillGrid XUiGridSkill[]
---@field _PassiveSkillGrid XUiGridSkill[]
local XUiEquipOneClickCulturePartnerMainPanelPartnerPlan = XClass(XUiNode, "XUiEquipOneClickCulturePartnerMainPanelPartnerPlan")

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:InitComponents()
    local XUiGridSkill = require("XUi/XUiPartner/PartnerCommon/XUiGridSkill")
    local configControl = self._Control:GetConfigControl()
    local mainSkillCount = configControl:GetMainSkillCount()
    local passiveSkillCount = configControl:GetPassiveSkillCount()

    self._MainSkillGrid = {}
    self._PassiveSkillGrid = {}

    for index = 1, mainSkillCount do
        local obj = self["UiEquipGridPartnerSkill" .. index]
        if obj then
            self._MainSkillGrid[index] = XUiGridSkill.New(obj, true)
        end
    end

    for index = 1, passiveSkillCount do
        local gridIndex = index + mainSkillCount
        local obj = self["UiEquipGridPartnerSkill" .. gridIndex]
        if obj then
            self._PassiveSkillGrid[index] = XUiGridSkill.New(obj, true)
        end
    end
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:OnStart(...)
    self:InitComponents()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:OnEnable()
    self:_SetEvent(true)
    -- 被 UiPartnerMain 遮挡期间数据可能已变更（Disable 期监听已反注册），恢复时主动刷新
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:OnDestroy()
end

---region ui event

-- TODO: 按钮点击回调，如 OnBtnXxxClick

---endregion

---region event

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
    end
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_OnPartnerSelectChange(partnerId)
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_OnPartnerDataUpdate()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_OnOneKeyCultureFinish()
    self:_Refresh()
end

---endregion

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_Refresh()
    local partnerEntity = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partnerEntity then
        return
    end

    self.TxtPartnerName.text = partnerEntity:GetOriginalName()

    local curQuality = partnerEntity:GetQuality()
    self.RImgCurQuality:SetRawImage(XMVCA.XCharacter:GetCharQualityIcon(curQuality))
    self.RImgRecommendQuality:SetRawImage(XMVCA.XCharacter:GetCharQualityIcon(self._Control:GetOneKeyCultureMainControl():GetRecommendQuality()))

    local maxLevel = partnerEntity:GetBreakthroughLevelLimit()
    self.TxtMaxLevel.text = tostring(maxLevel)
    self.TxtCurLevel.text = tostring(partnerEntity:GetLevel())
    self.ImgBreak:SetSprite(partnerEntity:GetBreakthroughIcon())

    self:_RefreshSkillGrids(partnerEntity)
end

function XUiEquipOneClickCulturePartnerMainPanelPartnerPlan:_RefreshSkillGrids(partnerEntity)
    local configControl = self._Control:GetConfigControl()
    local mainSkillCount = configControl:GetMainSkillCount()
    local passiveSkillCount = configControl:GetPassiveSkillCount()
    local skillType = configControl:GetSkillType()

    local mainSkillList = partnerEntity:GetCarryMainSkillGroupList()
    local passiveSkillList = partnerEntity:GetCarryPassiveSkillGroupList()
    local skillCount = partnerEntity:GetQualitySkillColumnCount()
    local partnerId = partnerEntity:GetId()

    for index = 1, mainSkillCount do
        local grid = self._MainSkillGrid[index]
        if grid then
            grid:UpdateGrid(mainSkillList[index], partnerEntity, false, skillType.MainSkill, index + 1)
            grid:SetRedDotActive(not mainSkillList[index])
        end
    end

    for index = 1, passiveSkillCount do
        local grid = self._PassiveSkillGrid[index]
        if grid then
            local skillData = passiveSkillList[index]
            grid:UpdateGrid(skillData, partnerEntity, skillCount < index, skillType.PassiveSkill, index + 1)
            grid:SetRedDotActive(not skillData and skillCount >= index)
        end
    end
end

return XUiEquipOneClickCulturePartnerMainPanelPartnerPlan
