--[[
-- XUiEquipOneClickCulturePartnerMainPartnerModel.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-24 15:59:14
--]]

---@class XUiEquipOneClickCulturePartnerMainPartnerModel : XUiNode
---@field _Control XPartnerControl
---@field Parent XUiEquipOneClickCulturePartnerMain
---@field PanelDrag XDrag
---@field private _RoleModelPanel XUiPanelRoleModel
---@field private _PanelRoleModel UnityEngine.RectTransform
---@field private _ImgEffectHuanren UnityEngine.RectTransform
local XUiEquipOneClickCulturePartnerMainPartnerModel = XClass(XUiNode, "XUiEquipOneClickCulturePartnerMainPartnerModel")

local XUiPanelRoleModel = require("XUi/XUiCharacter/XUiPanelRoleModel")

function XUiEquipOneClickCulturePartnerMainPartnerModel:InitComponents()
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:OnStart(...)
    self._CameraNames = { "CamNearMainPad", "CamNearMainStandard", "CamNearMainWidescreen" }
    self:InitComponents()
    self:_InitScene3DRoot()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:OnEnable()
    self:_SetEvent(true)
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:OnDisable()
    self:_SetEvent(false)
    if self._RoleModelPanel then
        self._RoleModelPanel:HideAllEffects()
    end
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:OnDestroy()
end

---region ui event

---endregion

---region event

function XUiEquipOneClickCulturePartnerMainPartnerModel:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
    end
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:_OnPartnerSelectChange(partnerId)
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:_OnPartnerDataUpdate()
    self:_Refresh()
end

---endregion

function XUiEquipOneClickCulturePartnerMainPartnerModel:_Refresh()
    local partner = self._Control:GetOneKeyCultureMainControl():GetCurPartnerEntity()
    if not partner then
        return
    end
    self:_UpdateRoleModel(partner:GetCombatModel(), true)
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:_InitScene3DRoot()
    local uiModelGo = self.Parent.UiModelGo
    if not uiModelGo then
        XLog.Error("XUiEquipOneClickCulturePartnerMainPartnerModel:_InitScene3DRoot() UiModelGo is nil, 请配置 UI 的 UiModelUrl")
        return
    end
    local root = uiModelGo.transform

    self._PanelRoleModel = root:FindTransform("PanelRoleModel")
    self._ImgEffectHuanren = root:FindTransform("ImgEffectHuanren")

    self._RoleModelPanel = XUiPanelRoleModel.New(self._PanelRoleModel, self.Parent.Name, nil, true, nil, true)
    self:_AdaptScreenAspectRatio()
end

function XUiEquipOneClickCulturePartnerMainPartnerModel:_AdaptScreenAspectRatio()
    local nearRoot = self.Parent.UiModelGo.transform:FindTransform("NearRoot")
    if not nearRoot then
        return
    end
    local cameraNames = self._CameraNames 
    local ratios = string.Split(CS.XGame.ClientConfig:GetString("PassportModelAdapt"))

    local width = CS.XUiManager.RealScreenWidth
    local height = CS.XUiManager.RealScreenHeight
    local realRatio = math.max(width, height) / math.min(width, height)

    local currentIndex = 1
    for _, targetRatio in pairs(ratios) do
        if realRatio > tonumber(targetRatio) then
            currentIndex = currentIndex + 1
        else
            break
        end
    end

    for i, name in ipairs(cameraNames) do
        local camera = nearRoot:FindTransform(name)
        if camera then
            camera.gameObject:SetActiveEx(i == currentIndex)
        end
    end
end

---@param modelId string 模型名（PartnerModel.tab 的 CombatModel / StandbyModel）
---@param isShowEffect boolean 是否播放换人特效
function XUiEquipOneClickCulturePartnerMainPartnerModel:_UpdateRoleModel(modelId, isShowEffect)
    self._RoleModelPanel:UpdatePartnerModel(modelId, XModelManager.MODEL_UINAME.XUiPartnerMain, nil, function()
        if isShowEffect and self._ImgEffectHuanren then
            self._ImgEffectHuanren.gameObject:SetActiveEx(false)
            self._ImgEffectHuanren.gameObject:SetActiveEx(true)
        end
    end, false, true, true)
end

return XUiEquipOneClickCulturePartnerMainPartnerModel
