--[[
-- XUiEquipOneClickCulturePartnerMainEnhanceDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-06-24 15:59:14
--]]

local XUiPartnerOneKeyCultureDetailItemCellView = require("XUi/XUiPartnerOneKeyCulture/OneKeyCultureMain/XUiEquipOneClickCulturePartnerMain/cell/XUiPartnerOneKeyCultureDetailItemCellView")

---@class XUiEquipOneClickCulturePartnerMainEnhanceDetail : XUiNode
---@field _Control XPartnerControl
---@field CultureDetailItem1 UiObject
---@field CultureDetailItem2 UiObject
---@field CultureDetailItem3 UiObject
--- 以下是自定义部分
---@field _LvupItem XUiPartnerOneKeyCultureDetailItemCellView
---@field _StarUpItem XUiPartnerOneKeyCultureDetailItemCellView
---@field _SkillLvupItem XUiPartnerOneKeyCultureDetailItemCellView
local XUiEquipOneClickCulturePartnerMainEnhanceDetail = XClass(XUiNode, "XUiEquipOneClickCulturePartnerMainEnhanceDetail")

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:InitComponents()
    self._LvupItem = XUiPartnerOneKeyCultureDetailItemCellView.New(self.CultureDetailItem1, self)
    self._StarUpItem = XUiPartnerOneKeyCultureDetailItemCellView.New(self.CultureDetailItem2, self)
    self._SkillLvupItem = XUiPartnerOneKeyCultureDetailItemCellView.New(self.CultureDetailItem3, self)

    -- 按枚举顺序排列，用于刷新与排序
    local XPartnerEnum = XMVCA.XPartner.Enum
    self._ItemList = {
        { Item = self._LvupItem, CultureType = XPartnerEnum.CultureType.LevelUp },
        { Item = self._StarUpItem, CultureType = XPartnerEnum.CultureType.StarUp },
        { Item = self._SkillLvupItem, CultureType = XPartnerEnum.CultureType.SkillLevelUp },
    }
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:OnStart(...)
    self:InitComponents()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:OnEnable()
    self:_SetEvent(true)
    -- 被 UiPartnerMain 遮挡期间数据可能已变更（Disable 期监听已反注册），恢复时主动刷新
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:OnDisable()
    self:_SetEvent(false)
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:OnDestroy()
end

---region ui event

-- TODO: 按钮点击回调

---endregion

---region event

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_SetEvent(flag)
    local XPartnerEventId = XMVCA.XPartner.EventIds
    if flag then
        self._Control:AddEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:AddEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
    else
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_PARTNER_SELECT_CHANGE, self._OnPartnerSelectChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_REPLY_PARTNER_DATA_UPDATE, self._OnPartnerDataUpdate, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_AUTO_EXCHANGE_CHANGE, self._OnAutoExchangeChange, self)
        self._Control:RemoveEventListener(XPartnerEventId.EVENT_ONE_KEY_CULTURE_FINISH, self._OnOneKeyCultureFinish, self)
    end
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_OnPartnerSelectChange(partnerId)
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_OnPartnerDataUpdate()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_OnAutoExchangeChange()
    self:_Refresh()
end

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_OnOneKeyCultureFinish()
    self:_Refresh()
end

---endregion

function XUiEquipOneClickCulturePartnerMainEnhanceDetail:_Refresh()
    for _, entry in ipairs(self._ItemList) do
        entry.Item:Refresh(entry.CultureType)
        if not entry.Item:IsCultureDone(entry.CultureType) then
            entry.Item.Transform:SetAsLastSibling()
        end
    end
    for _, entry in ipairs(self._ItemList) do
        if entry.Item:IsCultureDone(entry.CultureType) then
            entry.Item.Transform:SetAsLastSibling()
        end
    end
end

return XUiEquipOneClickCulturePartnerMainEnhanceDetail
