--[[
-- XUiPunishaarEventSelection.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-17 16:05:40
--]]

local XUiPunishaarEventSelectionBtnEvent = require("XUi/XUiPunishaar/XUiPunishaarEventSelection/XUiPunishaarEventSelectionBtnEvent")

--- 通用二选一界面（纯视图弹窗）
--- 外部通过 XLuaUiManager.Open("UiPunishaarEventSelection", title, options, onConfirm) 打开
---   title     string                        界面标题（nil 使用默认值）
---   options   { {Name, Desc}, ... }         1~2 个选项（1 个时默认选中且隐第二选项 #49）
---   onConfirm function(selectedIndex)       确认回调，selectedIndex 为 1 或 2
--- 生命周期约定：本界面不自行 Close，开/关时机由调用方（关卡流程管理器）统一编排，
---   以保证跳转时"先盖新界面、后关本弹窗"，避免露出底层界面。
---@class XUiPunishaarEventSelection : XLuaUi
---@field _Control XPunishaarControl
---@field TxtTitle TMPro.TextMeshProUGUI
---@field BtnComfirm XUiComponent.XUiButton
---@field PanelEvent XUiButtonGroup
---@field BtnEvent1 UnityEngine.RectTransform
---@field BtnEvent2 UnityEngine.RectTransform
local XUiPunishaarEventSelection = XLuaUiManager.Register(XLuaUi, "UiPunishaarEventSelection")

local DEFAULT_TITLE = ""

function XUiPunishaarEventSelection:OnAwake()
    self.BtnComfirm:AddEventListener(handler(self, self.OnBtnComfirmClick))

    ---@type XUiPunishaarEventSelectionBtnEvent
    self.BtnEvent1 = XUiPunishaarEventSelectionBtnEvent.New(self.BtnEvent1, self)
    ---@type XUiPunishaarEventSelectionBtnEvent
    self.BtnEvent2 = XUiPunishaarEventSelectionBtnEvent.New(self.BtnEvent2, self)
end

function XUiPunishaarEventSelection:OnStart(title, options, onConfirm)
    self._Title = title
    self._Options = options or {}
    self._OnConfirm = onConfirm
    self._SelectedIndex = 1

    local count = #self._Options
    self._SingleOption = (count <= 1)  -- 仅1个选项时默认选中+隐第二 #49

    self.BtnEvent1:Open()
    if self._SingleOption then
        -- 单选项：隐第二选项，PanelEvent 只含 BtnEvent1
        self.BtnEvent2:Close()
        self.PanelEvent:Init({ self.BtnEvent1.GridBtn }, handler(self, self._OnGroupSelect))
    else
        self.BtnEvent2:Open()
        self.PanelEvent:Init(
            { self.BtnEvent1.GridBtn, self.BtnEvent2.GridBtn },
            handler(self, self._OnGroupSelect)
        )
    end
    self.PanelEvent:SelectIndex(1)

    self:_RefreshTitle()
    self:_RefreshOptions()
end

function XUiPunishaarEventSelection:OnEnable()
end

function XUiPunishaarEventSelection:OnDisable()
end

function XUiPunishaarEventSelection:OnDestroy()
    self._Title = nil
    self._Options = nil
    self._OnConfirm = nil
    self._SelectedIndex = nil
end

function XUiPunishaarEventSelection:_RefreshTitle()
    -- self.TxtTitle.text = (self._Title and not string.IsNilOrEmpty(self._Title)) and self._Title or DEFAULT_TITLE
end

function XUiPunishaarEventSelection:_RefreshOptions()
    self.BtnEvent1:Refresh(self._Options[1] or {})
    self.BtnEvent2:Refresh(self._Options[2] or {})
end

--- ButtonGroup 选中回调
---@param index number 1 或 2
function XUiPunishaarEventSelection:_OnGroupSelect(index)
    self._SelectedIndex = index
end

--- 确认选择：仅上报选择结果，不自行关闭。
--- 本界面的开/关时机由关卡流程管理器（XPunishaarRunControl）统一编排——
--- 它需保证"新界面(FightMain)盖上之后再关本弹窗"，避免关早了露出底层界面（如选关地图）。
function XUiPunishaarEventSelection:OnBtnComfirmClick()
    if self._OnConfirm then
        self._OnConfirm(self._SelectedIndex)
    end
end

return XUiPunishaarEventSelection
