--[[
-- XUiPunishaarChallengeSettlementPanelFormation.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-07-21 17:21:58
--]]

---@class XUiPunishaarChallengeSettlementPanelFormation : XUiNode
---@field _Control XPunishaarControl
---@field PanelNoneFormation UnityEngine.RectTransform
---@field PanelBagList UnityEngine.RectTransform
---@field GridCard UnityEngine.RectTransform
---@field GridSlot UnityEngine.RectTransform 单格宽度基准（透明节点，仅取 sizeDelta.x，不显示）
local XUiPunishaarChallengeSettlementPanelFormation = XClass(XUiNode, "XUiPunishaarChallengeSettlementPanelFormation")

local XUiGridShopCard = require("XUi/XUiPunishaar/XUiPunishaarFightMain/UiShop/XUiGridShopCard")

function XUiPunishaarChallengeSettlementPanelFormation:OnStart()
    self.GridCard.gameObject:SetActiveEx(false)
    self:Refresh()
end

function XUiPunishaarChallengeSettlementPanelFormation:Refresh()
    -- 最终结算阵容只显示对战区(FightArea)卡牌，不再合并背包暂存区(Bag)；
    -- 复用 XList 容器，零 per-call GC（FillAreaCardsSorted 内部已按 StartPos 排序）
    if not self._FightAreaCardsList then self._FightAreaCardsList = XTool.XListNew() end
    local count = self._Control:FillAreaCardsSorted(XMVCA.XPunishaar.EnumConst.CardAreaType.FightArea, self._FightAreaCardsList)

    local isEmpty = count == 0
    self.PanelNoneFormation.gameObject:SetActiveEx(isEmpty)

    if self._CardGridDict == nil then
        self._CardGridDict = {}
    else
        for _, v in pairs(self._CardGridDict) do v:Close() end
    end
    XUiHelper.RefreshCustomizedList(self.GridCard.transform.parent, self.GridCard, count, function(index, go)
        local grid = self._CardGridDict[go]
        if not grid then
            grid = XUiGridShopCard.New(go, self)
            self._CardGridDict[go] = grid
        end
        grid:Open()
        local card = self._FightAreaCardsList:GetValueByIndex(index)
        local cfg  = self._Control:GetTablePunishaarCard(card.TemplateId, true)
        -- 传 GridSlot 作单格宽度基准，按 Size 缩放卡宽（修复 #55：原未传 slot 致宽度不应用）
        grid:RefreshAsEquipped(card, cfg and cfg.Size or 1, self.GridSlot)
    end)
    -- 宽度按 Size 设好后重建布局，让 PanelBagList 的 HorizontalLayoutGroup 紧凑重排
    if self.PanelBagList then
        CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.PanelBagList.transform)
    end
end

return XUiPunishaarChallengeSettlementPanelFormation
